### ISSUE TITLE
doesn't show accurate line number at web browser

### ISSUE THREAD

**Issue by atian25** [visionmedia/debug#105]

**Comment by wildermuthn** [comment]
I use a browserify transform that overrides the console.log() and inserts the line number. Works pretty well for my purposes, except my regex doesn't handle all cases correctly.

This also automates enabling of each file included in my browserify bundle (related to #154).

```javascript
var through = require('through2');
var _ = require('underscore');

module.exports = function(file) {
  return through(function(buf, enc, next) {
    var parts = file.split('/');
    var filename = parts[parts.length - 1];
    if (filename === 'index.js') {
      filename = parts[parts.length - 2] + '-dir';
    }
    var bufString = buf.toString('utf8');
    var lines = bufString.split(/\r\n|\r|\n/);
    _.each(lines, function(line, i) {
      if (line.match('console') && file.match('app')) {
        var regExp = /\((.*)\)/;
        var insideParens = regExp.exec(line)[1];
        var lineNumber = '"Line ' + String(i + 1) + '"';
        lines[i] = line.replace('(' + insideParens + ')', '(' + insideParens + ',' + lineNumber + ')');
      }
    });
    if (file.match('app')) {
      var string = "var console = {log: require('debug')('" + filename + "')}\n\n" + lines.join("\r\n");
      this.push(string);
    }
		else {
			this.push(lines.join("\r\n"));
		}
    next();
  });
}
```
![screenshot] (https://www.dropbox.com/s/wbdln91i8aafl7a/Screenshot%202015-02-18%2018.43.55.png?dl=1)

**Comment by constantx** [comment]
:+1: if we can get correct line numbers with `debug` in the browser log ;)

**Comment by TooTallNate** [comment]
That's pretty cool Nate :)

**Comment by AxelDelmas** [comment]
In Chrome you can now have the correct file and line number by blackboxing 'debug.js' script in the DevTool;
https://gist.github.com/paulirish/c307a5a585ddbcc17242

Only (quite annoying) problem is that it doesn't work if the script you blackbox is bundled together in a single file with your code. I hope chrome improves this behaviour in the future.

Meanwhile it might be a good ides to expose a standalone build, since this solution won't work if you require 'debug.js' in your code.

**Comment by binarykitchen** [comment]
@wildermuthn interesting code of yours. care to make it a npm package?

@TooTallNate yeah, this is tricky, tough problem to crack. any success at all yet?

**Comment by binarykitchen** [comment]
correction: bows does not seem to preserve line number

**Comment by binarykitchen** [comment]
that's a compromise i can live with for now:

```js
    // workaround: since we cannot overwrite console.log without having the correct file and line number
    // we'll use groupCollapsed() and trace() instead to get these.
    function debug() {
        console.groupCollapsed(arguments)
        console.trace('Trace')
        console.groupEnd()
    }
```

**Comment by d-simon** [comment]
I will have to correct @binarykitchen, we just switched to bows because it indeed *does* show the line number.
We'd actually prefer debug, but alas, for now we'll stay with bows.
:+1:  for this issue!

**Comment by airtonix** [comment]
We have an internal module we created to log stuff, it reveals the line in the source code it logged from.

Policy prevents me from dumping the source code, but I can clue you into how it's done for webkit/blink and ie:


```coffee
isFunction (func)->
  return typeof func is 'function'

class Logger
  methods: [
    'log', 'error', 'debug', 'trace'
  ]
  constructor: ->
    (@bind(method) for method in @methods)
    
  bind: (method)->
    target = window.console[method]
    if isFunction(target) && isFunction(target.bind)
      @[method] = target.bind console
    else
      @[method] = Function.prototype.bind.call target, console
```

**Comment by fijiwebdesign** [comment]
I started on a possible fix for this #273.

**Comment by neojp** [comment]
I just tried #273. It works.

**Comment by thebigredgeek** [comment]
feel free to discuss further here.  I think this should be something we handle with V3 https://github.com/visionmedia/debug/issues/370
