### ISSUE TITLE
Passing several arguments to debug() looks weird

### ISSUE THREAD

**Issue by Suor** [visionmedia/debug#132]
I am debugging SQL queries like:

``` js
var debug = require('debug')('pg-bricks');
debug(query, params);
```

And I got query grayed, but not params:

![pg-bricks-logging](https://cloud.githubusercontent.com/assets/284103/3992215/ea9e9c12-28f5-11e4-8b10-f3273f647ada.png)

**Comment by devinus** [comment]
It's not really a decorated `console.log` at that point then...
