### ISSUE TITLE
configurable debug environmental variable

### ISSUE THREAD

**Issue by dotdat** [visionmedia/debug#134]
DEBUG as an environmental variable is very generic. It could possibly cause collisions with other software running on the same machine. Is there a way to change DEBUG to another environmental variable or could something be added to configure this variable?

**Comment by mehwww** [comment]
+1
Happened to meet a cloud service SDK that debug like this
```javascript
if (process.env.DEBUG) {
  console.log('  ')
}
```
It make me crazy when I debug my code with endless `emit httpUploadProgress`
