### ISSUE TITLE
how to avoid the tedious initialization?

### ISSUE THREAD

**Issue by stablum** [visionmedia/debug#154]
also posted here: http://stackoverflow.com/questions/26777433/node-js-debug-module-how-to-avoid-this-tedious-initialization

I am wondering if there is any way to prevent this tedious and overly redundant inizialization in each module:

```
require('debug').enable('module-name:log module-name:ERROR');
var log = require('debug')('module-name:log');
var error = require('debug')('module-name:ERROR');
```

As you can see it's redundant on two different levels: I need to "enable" the loggers before instantiating them, sending the same name twice as strings, and I need to write the module name. Is there any way to do this automagically?

**Comment by dmarcelino** [comment]
Hi @stablum, I've just replied to your stackoverflow question. If you are using `debug` outside the browser you can use [debug-logger](https://github.com/appscot/debug-logger) to lazily instantiate multiple instances of `debug` to log at different levels as you would do with console. It's essentially a wrapper for `debug` with no other dependencies.

Example:
```javascript
var log = require('debug-logger')('myapp');

log.trace("I'm a trace output");
log.debug("I'm a debug output");
log.log("I'm a log output");
log.info("I'm an info output");
log.warn("I'm a warn output");
log.error("I'm an error output");
```

would print:

``` shell
myapp:trace I'm a trace output +0ms
myapp:debug I'm a debug output +2ms
myapp:log   I'm a log output +0ms
myapp:info  I'm an info output +0ms
myapp:warn  I'm a warn output +1ms
myapp:error I'm an error output +0ms
```

More info at the project page,
Regards

**Comment by ashwell** [comment]
I know this is a year later, but I just wrote this to help facilitate creating debug instances for stdout and stderr...

```js

const debug = require( 'debug' );

module.exports = function( namespace ) {
  const
    log = debug( `${ namespace }:log` ),
    error = debug( `${ namespace }:error` );

  log.log = console.log.bind( console );

  return { log, error };
};
```

**Comment by thebigredgeek** [comment]
Closing this for now.  Feel free to discuss further the V3 API RFC issue: https://github.com/visionmedia/debug/issues/370
