### ISSUE TITLE
Global vs. per-prefix ms diffs

### ISSUE THREAD

**Issue by fgnass** [visionmedia/debug#155]
I have an app with a whole bunch of modules that all use `debug` for logging. The modules that use exactly the same debug-version share a common ms counter as they are deduped by npm. This leaves me with about 3 different counters which makes the log pretty hard to decode.

The per-prefix diffs also had the advantage that you could easily identify how long different async tasks took to finish, you just had to give them different prefixes.

Of course there's also a valid case for global diffs. so maybe adding an option to give a debug instance its own ms counter would be a viable approach? I'd love to hear your thoughts!

**Comment by soyuka** [comment]
+1 a namespace diff could be more interesting, especially if you have parallel calls, diff isn't reflecting the thruth if those are globals.

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/issues/370 < child debug instances + time configuration should solve this.  Feel free to discuss there
