### ISSUE TITLE
security error on safari

### ISSUE THREAD

**Issue by yields** [visionmedia/debug#167]
When a user disables localstorage / cookies in safari `window.onerror` is invoked with security error.
I'm not sure what the correct thing this module should do though, i'm just opening this issue to see what you think ;)

**Comment by TooTallNate** [comment]
Hmmm, well we already have `try/catch` around the localStorage access calls. I wonder if anybody has documented a workaround for this before...

**Comment by yields** [comment]
Oh the error is thrown here: https://github.com/visionmedia/debug/blob/master/browser.js#L24 not sure if this happens in other browsers too.

**Comment by TooTallNate** [comment]
Oh ok. So lets try throwing a try/catch around that part of the code as
well? (Ideally hoisting it out into its own function so that the entire
module doesn't get de-optimized because of the module-level try/catch).
