### ISSUE TITLE
Way to force use debug from file

### ISSUE THREAD

**Issue by reggi** [visionmedia/debug#169]
Is there any way I can force use debug from the file itself so I don't have to pass `DEBUG` from the command line?

**Comment by TooTallNate** [comment]
If you set `process.env.DEBUG` _before_ doing any `require('debug')` calls then it _should_ work.

I'd say the better way to go would be export the variable in your `.bashrc` file:

```
export DEBUG="foo*, bar*"
```

**Comment by mooyoul** [comment]
You can use `debug.enable('*');` from your code to enable debug without setting `DEBUG` environment variable.

**Comment by TooTallNate** [comment]
Oh ya there's that too :)

**Comment by reggi** [comment]
Thanks!
