### ISSUE TITLE
outputting to the browser console

### ISSUE THREAD

**Issue by gnaryak** [visionmedia/debug#170]
Hi - The documentation in Readme.md about how to output debug statements to the browser console appears to be incomplete. It would be great if you could update Readme.md to change from:

Debug works in the browser as well, currently persisted by localStorage. For example if you have worker:a and worker:b as shown below, and wish to debug both type debug.enable('worker:*') in the console and refresh the page, this will remain until you disable with debug.disable().

to

Debug works in the browser as well, currently persisted by localStorage. Consider the situation shown below where you have worker:a and worker:b, and wish to debug both. Somewhere in the code on your page, include:
window.myDebug = require("debug");
("debug" is a global object in the browser so we give this object a different name.) When your page is open in the browser, type the following in the console:
myDebug.enable("worker:*")
Refresh the page. Debug output will continue to be sent to the console until it is disabled by typing myDebug.disable() in the console.

**Comment by gnaryak** [comment]
I created a [pull request](https://github.com/visionmedia/debug/pull/171) for this change.

Thanks.

**Comment by r4j4h** [comment]
+!

**Comment by pjuke** [comment]
YES YES YES +1

**Comment by thebigredgeek** [comment]
Already fixed and merged via PR above
