### ISSUE TITLE
Method to create a writable stream

### ISSUE THREAD

**Issue by jugglinmike** [visionmedia/debug#173]
I'd like to label the output streams of a child process as debugging information. For instance:

``` js
var spawn = require('child_process').spawn;
var debug = require('debug');

var seleniumOutput = debug.stream('selenium');
var cp = spawn('java', ['-jar', 'selenium.jar'], {
  stdio: ['ignore', seleniumOutput, seleniumOutput]
});
```

Would that be in-scope for this module?

**Comment by jugglinmike** [comment]
This is actually easy enough to implement without a debug stream:

```js
var spawn = require('child_process').spawn;
var debug = require('debug');

var seleniumOutput = debug('selenium');
var cp = spawn('java', ['-jar', 'selenium.jar']);
cp.stdout.on('data', function(chunk) { seleniumOutput(String(chunk)); });
cp.stderr.on('data', function(chunk) { seleniumOutput(String(chunk)); });
```

So probably not worth an addition to debug's API.

**Comment by Qix-** [comment]
This is a pretty niche use-case since `debug` wraps output and streams don't necessarily have the construct of individual messages unless in object mode.

Neat solution to your problem, though :)

**Comment by jugglinmike** [comment]
Makes sense. Thanks for following up!
