### ISSUE TITLE
log(message) goes to stderr.

### ISSUE THREAD

**Issue by JiangJie** [visionmedia/debug#177]
I wrote the following test code and ran it.
```javascript
const debug = require('debug');
const log = debug('log');
const error = debug('error');
error.log = console.error.bind(console);
log('hello world!');
error('here is error message');
```
But the log and error message all went to stderr which was unexpected.
I found the code in file node.js.
```javascript
var fd = parseInt(process.env.DEBUG_FD, 10) || 2;
var stream = 1 === fd ? process.stdout :
             2 === fd ? process.stderr :
             createWritableStdioStream(fd);
```
Default logs will go to stderr since the environment variable DEBUG_FD was not set.
Why use stderr?

**Comment by TooTallNate** [comment]
stderr is the default intentionally. Programs use stdout for structured output which debug output could break.
