### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by nolanlawson** [visionmedia/debug#178]
Hey, sorry to nag, but just wondering when the next release will be? We're looking forward to https://github.com/visionmedia/debug/commit/2c384416fb68ecbad32dee68a1e9e9d073ad2d08 because it'll fix web workers in PouchDB. :)

**Comment by dougwilson** [comment]
And I think people would like #172 and #175 / #176

**Comment by TooTallNate** [comment]
I'll try to get to it tonight or tomorrow. Thanks for the ping.

**Comment by dougwilson** [comment]
Oh, and @TooTallNate apparently I have commit access here now, so feel free to let me know if I can lend a hand, but otherwise I'll simply leave this repo be :)

**Comment by jonathanong** [comment]
was gonna do stuff but apparently there are no tests, so i'm scared.

**Comment by dougwilson** [comment]
2.1.1 was published to npm
