### ISSUE TITLE
How to disable color in the browser?

### ISSUE THREAD

**Issue by ibc** [visionmedia/debug#179]
I use `debug` in several libraries that I put together via `browserify()`. Now I would like to insert a mechanism so all the logs get (also) stored into a JS variable so they can be later sent somewhere. And obviously I plan to override the global `console.xxxxx()` methods for that.

So I would prefer to disable colorized output (%c symbols).

BTW, any other suggestion for what I want to achieve? Thanks a lot.

**Comment by jprichardson** [comment]
Would love this as well. Doesn't look possible: https://github.com/visionmedia/debug/blob/master/browser.js#L44

@TooTallNate would you accept a PR to fix this?

**Comment by TooTallNate** [comment]
Yea

**Comment by jandrieu** [comment]
@TooTallNate There's a PR that fixes this #247. For your consideration.

**Comment by thebigredgeek** [comment]
Check out middleware proposal here: https://github.com/visionmedia/debug/issues/370
