### ISSUE TITLE
Git bash

### ISSUE THREAD

**Issue by dfcreative** [visionmedia/debug#180]
I use [git bash](https://msysgit.github.io/) for a system console, and debug doesn’t work there. `set DEBUG=*` doesn’t help.
In cmd.exe it works just fine.

**Comment by TooTallNate** [comment]
> and debug doesn’t work there

How exactly are you invoking it?

**Comment by dougwilson** [comment]
Git bash is literally bash; you set environment variables with bash syntax instead of Windows cmd.exe syntax. The syntax you are looking for is `export DEBUG=*`.
