### ISSUE TITLE
Stdout is printed to stderr

### ISSUE THREAD

**Issue by VipSaran** [visionmedia/debug#181]
The test:
```
var debug = require('debug');
var log = debug('app:log');
var error = debug('app:error');
error.log = console.error.bind(console);

log('goes to stdout!');
error('goes to stderr');
```

The result:
```
$ DEBUG=* node debug-test.js 2> /dev/stdout 1> /dev/null
  app:log goes to stdout! +0ms
  app:error goes to stderr +3ms
```

The expected result would be:
```
$ DEBUG=* node debug-test.js 2> /dev/stdout 1> /dev/null
  app:error goes to stderr +3ms
```

Or, if you wanted to verify via your stder.js example (from README), the result is also NOK:
```
$ DEBUG=* node stderr.js 2> /dev/stdout 1> /dev/null
  app:log goes to stdout! +0ms
  app:error goes to stderr +4ms
  app:log still goes to stdout! +1ms
  app:log now goes to stderr via console.warn +0ms
  app:error still goes to stderr, but via console.warn now +1ms
```

**Comment by icodeforlove** [comment]
+1

I'm experiencing this as well.

**Comment by dmarcelino** [comment]
Hi @VipSaran, @icodeforlove, I believe the example got outdated. If you look at [node.js#L35](https://github.com/visionmedia/debug/blob/master/node.js#L35) you'll see stderr (FD=2) is the default stream and not stdout (FD=1).

To achieve what you are looking for try the below:
``` javascript
var debug = require('debug');
var log = debug('app:log');
log.log = console.log.bind(console);
var error = debug('app:error');

log('goes to stdout!');
error('goes to stderr');
```

Alternatively you can also try [debug-logger](https://github.com/appscot/debug-logger) which does this sort of setup for you.

**Comment by TooTallNate** [comment]
Ya we should probably just remove that example I guess.

**Comment by dmarcelino** [comment]
Hi @TooTallNate, we can also update the examples, check #186. Cheers

**Comment by TooTallNate** [comment]
Thanks @dmarcelino

**Comment by dmarcelino** [comment]
No worries

**Comment by VipSaran** [comment]
@dmarcelino , the example you have pasted:
```
var debug = require('debug');
var log = debug('app:log');
log.log = console.log.bind(console);
var error = debug('app:error');

log('goes to stdout!');
error('goes to stderr');
```
works as expected with redirected streams.

But the `examples/stdout.js`, even though it's recently updated, has uncorrect output. See https://github.com/visionmedia/debug/pull/186#issuecomment-79305006.
