### ISSUE TITLE
Clarification on object formatting

### ISSUE THREAD

**Issue by lgomez** [visionmedia/debug#185]
Hi!

I've searched for this but can't figure it out and have a feeling I'm just using it the wrong way. I read #125 but is there a way to output objects formatted like `debug("obj: %s", util.inspect(obj));` does but retain the coloring that one gets with `debug("obj: %o", response);`?

`debug("obj: %s", util.inspect(obj));` gives me a nested object with no coloring where `debug("obj: %o", response);` gives me the same object all on one single line but colored nicely.

Thank you!

**Comment by lgomez** [comment]
I realize I can pass a colors option like so: `debug("obj: %s", util.inspect(obj, {colors: true}));` but I'm wondering if `debug("obj: %o", response);` can already achieve the same effect.

Thanks!

**Comment by TooTallNate** [comment]
Not really. The `debug("obj: %s", util.inspect(obj, {colors: true}));` method is probably the quickest way.
