### ISSUE TITLE
Allow disabling milisecond diff

### ISSUE THREAD

**Issue by steelbrain** [visionmedia/debug#187]
Just like the title says

**Comment by alampros** [comment]
+1

**Comment by maxdow** [comment]
+1

**Comment by cheshirecatalyst** [comment]
+1

**Comment by bucaran** [comment]
You can't at this moment, but you can simply use `console.log` or `console.error` for that if your instrumentation needs are so simple.

**Comment by steelbrain** [comment]
@bucaran `console.log`/`console.error` doesn't have all the other features :(

**Comment by medikoo** [comment]
:+1:

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/issues/370 < Middleware should allow you to do this quite easily
