### ISSUE TITLE
browser: Using chrome.storage.local prevents debugging in chrome extensions

### ISSUE THREAD

**Issue by stephenmathieson** [visionmedia/debug#188]
I've got a handful of chrome extensions using debug.  Since a98c28309582135d1849ecc787a9052e1e7fa7e1 landed, I haven't been able to use this package.

Thoughts on either reverting commit in question, or providing some mechanism for disabling [this behaviour](https://github.com/visionmedia/debug/blob/2.1.3/browser.js#L21-L22)?

/cc @marmolejo

**Comment by stephenmathieson** [comment]
Something is simple (but awkward) as this would do for me:

```js
var debug = require('debug')('my thing');
debug.storage = localStorage;
```

**Comment by chunpu** [comment]
Why not delete `chrome.storage.local` thing and just use `localStorage`! it never work in chrome extension,

**Comment by stephenmathieson** [comment]
+1 to @chunpu's suggestion
