### ISSUE TITLE
request/question: is there a way for debug to log to a file?

### ISSUE THREAD

**Issue by gnowxilef** [visionmedia/debug#192]
based on the readme, i do not see a way for debug to log to a file.

**Comment by stephenmathieson** [comment]
yep, you can:

```
$ DEBUG_FD=3 node your-app.js 3>whatever.log
```

and all debug statements will be piped into `whatever.log`

**Comment by DanielOchoa** [comment]
I was looking for the same thing and I just stumbled here. This is something really useful to know. Should it be mentioned on the README perhaps? I could make a quick PR if the answer is yes.

**Comment by TooTallNate** [comment]
Yes

**Comment by reggi** [comment]
I'm attempting to do this now, and It makes not working.

Here's what I've been trying, which could be used to make more helpful docs.

```
thomas@workstation:node-image-learning$ DEBUG_FD=3 DEBUG=* node -e 'var debug = require("debug")("test"); debug("hello world")' > temp.txt
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: write EBADF
    at Object.exports._errnoException (util.js:749:11)
    at exports._exceptionWithHostPort (util.js:772:20)
    at WriteWrap.afterWrite (net.js:753:14)
thomas@workstation:node-image-learning$ DEBUG_FD=3 node -e 'var debug = require("debug")("test"); debug("hello world")' > temp.txt
thomas@workstation:node-image-learning$ DEBUG_FD=3 node -e 'var debug = require("debug")("test"); debug("hello world")' 3> temp.txt
thomas@workstation:node-image-learning$ DEBUG_FD=* node -e 'var debug = require("debug")("test"); debug("hello world")' *> temp.txt
thomas@workstation:node-image-learning$ DEBUG_FD=test node -e 'var debug = require("debug")("test"); debug("hello world")' test> temp.txt
```

Also posted this [stackoverflow](http://stackoverflow.com/questions/29448156/write-the-contents-of-node-debug-log-to-file) question.

**Comment by reggi** [comment]
Thought it might have something to do with  the eval (`-e`) and not running from a file and tried all the following, with no luck as well.

```
thomas@workstation:node-image-learning$ DEBUG_FD=3 node log.js 3> temp.txt 
thomas@workstation:node-image-learning$ DEBUG_FD=3 node log.js > temp.txt 
thomas@workstation:node-image-learning$ DEBUG_FD=3 node log.js
thomas@workstation:node-image-learning$ DEBUG=* node log.js 
  test hello world +0ms
 thomas@workstation:node-image-learning$ DEBUG_FD=3 node log.js 3> temp.txt 
thomas@workstation:node-image-learning$ DEBUG_FD=3 node log.js > temp.txt 
thomas@workstation:node-image-learning$ DEBUG_FD=3 node log.js
thomas@workstation:node-image-learning$ DEBUG=* node log.js 
  test hello world +0ms
```

**Comment by stephenmathieson** [comment]
@reggi this works fine:

```
stephenmathieson at MBP in /tmp/debug-192
$ DEBUG_FD=3 DEBUG=foo node -e "require('debug')('foo')('hello')" 3> foo.txt
stephenmathieson at MBP in /tmp/debug-192
$ cat foo.txt 
Sat, 04 Apr 2015 15:45:35 GMT foo hello
stephenmathieson at MBP in /tmp/debug-192
```

**Comment by reggi** [comment]
@stephenmathieson Thanks for the clarification, I believe I was behind a version when I used both `DEBUG_FD` and `DEBUG` together I got that error. Then when I upgraded I stopped using `DEBUG` and wasn't getting any output. Its working now, thanks a bunch! :banana: :banana: :banana: :banana: :banana:

**Comment by stephenmathieson** [comment]
@reggi glad it's figured out

**Comment by speedster-kiev** [comment]
I've stuck with the same problem with only one difference. If I'm running my application with node - everything is cool and debug works, but if I runnig my application with nodemon - I receive exactly the same error.

Any advises?

**Comment by tasoss** [comment]
hello.is it possible to do something like that on windows ?thanks!
