### ISSUE TITLE
Weird output in Firefox/Mac

### ISSUE THREAD

**Issue by pronebird** [visionmedia/debug#196]
Hi,

Did anyone notice that Firefox outputs logs in a very funky way? It's standard console in FF 37.

Is there something wrong with my Firefox? Is it possible to fix that?

![screenshot 2015-04-17 18 15 58](https://cloud.githubusercontent.com/assets/704044/7206031/ed7879ea-e52d-11e4-9d13-a213b8719db5.png)

**Comment by thebigredgeek** [comment]
I haven't seen this.  Closing.
