### ISSUE TITLE
How to get file:linenumber in debug() output?

### ISSUE THREAD

**Issue by MichaelJCole** [visionmedia/debug#198]
Is this already implemented?

Thanks!

**Comment by karloluis** [comment]
Not that I know off. I believe that you can subtag your debugs though.. 

require(debug)("SUPERTAG") 
debug("subtag")("Debug notes")

But I might be hallucinating.

**Comment by bucaran** [comment]
@MichaelJCole This is not possible now, but you can always `console.trace()` anywhere in your code.

@karloluis This is not possible either, unfortunately.

**Comment by jwebcat** [comment]
A simple solution to this without modifying library code for Chrome, is to blackbox the debug.js script and you will still get the debugging message but you will get the line number of the js it got called from not the same line 444 from debug.js where log() is defined.

**Comment by bucaran** [comment]
@jwebcat Thanks! Very useful.

**Comment by jandrieu** [comment]
FWIW, (and as mentioned in issue #105 ) the blackboxing won't work for inline scripts such as created with browserify.  There's an update in the works for blackboxing in Chromium, so maybe this will get fixed soon. https://code.google.com/p/chromium/issues/detail?id=563578

**Comment by Yalhu** [comment]
@jwebcat Thanks! Very helpful.
