### ISSUE TITLE
Help on format

### ISSUE THREAD

**Issue by mike-aungsan** [visionmedia/debug#199]
```
console.log('text %s', obj);   // this will print out 
```

with debug,

```
var debug           = require('debug')('label');
debug(('text %s', obj);   // this does not print. any working example?
```

**Comment by stephenmathieson** [comment]
you have to enable debugs, either with the `DEBUG` env var, or `localStorage.debug`

**Comment by mike-aungsan** [comment]
yes I did. export DEBUG=* or set DEBUG=*

debug(('text %s', obj); 
Sorry I should make it clear, it does print mean it does not print obj. It just print text -> 'text'

**Comment by dougwilson** [comment]
What is the output from `console.log('text %s', obj);`?

**Comment by bucaran** [comment]
@mike-aungsan 

Are you wrapping `*` in quotes `" "`? Also, the syntax is a bit different depending on your shell:

  POSIX shells:
  ```sh
  DEBUG="*"
  ```

  Fish:
  ```sh
  env DEBUG="*"
  ```
