### ISSUE TITLE
Highlight some parts of messages

### ISSUE THREAD

**Issue by njakob** [visionmedia/debug#200]
Since colors are helping a lot to visually looking for information in the console, would it be great to also have the ability to highlight some important parts of a message; such as numbers or keywords ?

**Comment by bucaran** [comment]
Try

```js
debug("%o", obj)
```

It will color highlight the object depending on its type, RegExp are red, numbers are yellow, strings are green, etc.

Other than that you will need to use plain old control characters.

See [clor](https://github.com/bucaran/clor) or [chalk](https://github.com/sindresorhus/chalk) for a simple solution to this.

**Comment by njakob** [comment]
That's what I ended up to use, thanks for the tips !
