### ISSUE TITLE
document DEBUG_COLORS and DEBUG_FD default

### ISSUE THREAD

**Issue by amitport** [visionmedia/debug#205]
I'm using jetbrains' webstorm, in order to get debug work with colors in webstorm's run configuration I had to set `DEBUG_COLORS=true` and set `DEBUG_FD=1` (since webstorm is tty and does not support colors in console error stream)

This was an headache, considering the default of `DEBUG_FD` is not mentioned and `DEBUG_COLORS` is not mentioned at all.

(opening this issue adds some documentation... I don't have time to write a real pr)

**Comment by mattlyons0** [comment]
Thank You!
I had this problem as well and realized DEBUG_COLORS but didn't find DEBUG_FD
Note DEBUG_COLORS can also be 1, just to shorten it up a little.
