### ISSUE TITLE
How can I use debug in the browser with AngularJS and Bower?

### ISSUE THREAD

**Issue by andreicristianpetcu** [visionmedia/debug#210]
Hello, 

Is there a tutorial on how to use it in the browser with AngularJS?
`window.myDebug = require("debug");` does not work for me since I do not use the npm package management in the browser, I use bower for that.

I managed to make it work fine in the nodejs backend.

Thank you!

**Comment by stephenmathieson** [comment]
when in non-commonjs env, it's exposed as `window.debug`

**Comment by nmccready** [comment]
plunkr here http://plnkr.co/edit/C4PcSxUhLKywBzuKUqLu?p=preview wow, this should be in the Readme.md

**Comment by andreicristianpetcu** [comment]
Thank you @nmccready

**Comment by nmccready** [comment]
If you do not have CommonJS loaded is there anyway to not override window.debug? I am looking for options to not browserify my lib.
See: https://github.com/nmccready/angular-simple-logger/issues/4

**Comment by Nexxado** [comment]
@nmccready Thank you.
made me realize that the npmjs version isn't what i need,
simply took the file from this repo's dist folder.
