### ISSUE TITLE
Properly printout JSON objects

### ISSUE THREAD

**Issue by murdockcrc** [visionmedia/debug#214]
Perhaps I am missing something in the configuration, but when I try to debug a native JSON object, I get the result `[object Object]`. Reproduction steps:
1. Create a conventional JSON literal:

```
var options = {
            url: config.wooCommence.urls[config.env],
            consumerKey: config.wooCommence.accounts.api[config.env].consumerKey,
            consumerSecret: config.wooCommence.accounts.api[config.env].consumerSecret,
            version: 'v3'
            };
```
1. Try to output it with debug:
   `debug('woocommerce client using options: ' + options);`
2. You will get this result:
   `wooHelper woocommerce client using options: [object Object] +0ms`

Workaround:
I can get the information I want by using this workaround, which is too verbose and, in my opinion, unnecessary:
`debug('woocommerce client using options: ' + JSON.stringify(options, null, 4));`

So just wanted to ask if there is a better way to get the content of JSON objects using debugger, or if it would make sense to add a method to simplify the output of JSON literals.

**Comment by madebyherzblut** [comment]
Since debug uses `console.*` (browser) and `util.format` (node) internally, you can use the `%j` placeholder for a quick JSON output: 

```javascript
debug('woocommerce client using options: %j', options);
```

However, If you need pretty printing keep using `JSON.stringify`.

**Comment by mooyoul** [comment]
That's not debug's fault. It's behavior of concat strings in Javascript.
`'woocommerce client using options: ' + options'` equal as `'woocommerce client using options: ' + options.toString()'`.

If you want to debug Object literal properly, Use @madebyherzblut 's  workaround.
