### ISSUE TITLE
Why does formatArgs prepend with date if useColors = false?

### ISSUE THREAD

**Issue by bepper08** [visionmedia/debug#216]
Unsure why formatArgs prepends log message with a date stamp when useColors is false. Am I missing something?

``` javascript
/**
 * Adds ANSI color escape codes if enabled.
 *
 * @api public
 */

function formatArgs() {
  var args = arguments;
  var useColors = this.useColors;
  var name = this.namespace;

  if (useColors) {
    var c = this.color;

    args[0] = '  \u001b[3' + c + ';1m' + name + ' '
      + '\u001b[0m'
      + args[0] + '\u001b[3' + c + 'm'
      + ' +' + exports.humanize(this.diff) + '\u001b[0m';
  } else {
    args[0] = new Date().toUTCString()
      + ' ' + name + ' ' + args[0];
  }
  return args;
}
```

**Comment by gramakri** [comment]
We face this issue when running a node program via systemd. We end up with double dates in journactl logs (one from systemd itself and another from the above code).

**Comment by gramakri** [comment]
See also #161 and #157

**Comment by thebigredgeek** [comment]
Date configuration and output parsing via middleware should be supported in V3 and solve this.

Check it out here: https://github.com/visionmedia/debug/issues/370

Closing for now
