### ISSUE TITLE
Can't run on Windows 8.1 x64

### ISSUE THREAD

**Issue by Sogl** [visionmedia/debug#219]
Hi!

I saw this thread and tried all from it:
https://github.com/visionmedia/debug/issues/58

My attempt:

```
Артем@SOGL c:\projects\loopback-zero-to-hero
$ set DEBUG=*

Артем@SOGL c:\projects\loopback-zero-to-hero
$ DEBUG=server:boot:* node .
"DEBUG" is not an internal or external
command, operable program or batch file.

Артем@SOGL c:\projects\loopback-zero-to-hero
$
```

Also tried this from README.md:

```
set DEBUG=*,-not_this
```

How to make it work on Windows?

**Comment by devjet** [comment]
Hi
inside your file.js

**process.env.DEBUG = "*,-not_this";**
var dbug = require('debug')('app');
dbug('Hello, %s!', 'world');
...

then you don't need "set DEBUG=*" option

Worked for me.

**Comment by gggin** [comment]
@Sogl  same problem in win10

**Comment by gggin** [comment]
hi, I use webpack then run set DEBUG=* node xx this maybe a generate a tricky file 
use webpack DefinePlugin to prevent this problem!

**Comment by xgdgsc** [comment]
Not working for me on Windows 10. `process.env.DEBUG = "*,-not_this";` also doesn' t work.

**Comment by thebigredgeek** [comment]
We need more info about the environment you are running.  Debug works fine on my tests on windows 7 and 8.  Closing for now

**Comment by 2beens** [comment]
Still having the same issues on Win10. 
I have tried every method mentioned here (and elsewhere), but nothing seems to work, I still get the message: "'DEBUG' is not recognized as an internal or external command,
operable program or batch file."
Gist link which contains the npm complete log:
https://gist.github.com/2beens/871a90f07b8a6a1e83d5c612efeda661
