### ISSUE TITLE
Can I disable the time field?

### ISSUE THREAD

**Issue by pulkitsinghal** [visionmedia/debug#221]
Is it possible to turn-off the time spent between one debug() call and the next ... that is spit out by default in the `debug` module?

**Comment by stephenmathieson** [comment]
#208

**Comment by dcsan** [comment]
for others, that is 

    DEBUG_DIFF=0 ....

**Comment by pulkitsinghal** [comment]
@dcsan Thank You! Perhaps I misunderstood something, I tried:
`DEBUG_DIFF=0 DEBUG=loopback:* node server/server.js`

And the time field is still present in the logs.

**Comment by dkebler** [comment]
three months later and #208 is apparently not merged. (tried it).
Will it be? would like to turn off this feature.  

Or better yet how about off by default.

**Comment by Morriz** [comment]
+1

**Comment by world** [comment]
`console.log("merge please");`

**Comment by GitTom** [comment]
+1

**Comment by thebigredgeek** [comment]
Currently, no.  But with middleware this might be possible.  See here... https://github.com/visionmedia/debug/issues/370

**Comment by cbdeveloper** [comment]
Is this still not possible to disable?

I'm getting double timestamp logs on my Cloud Run server (which logs a timestamp by default already).

![image](https://user-images.githubusercontent.com/43407798/107153804-509dd100-6967-11eb-93ed-11a6131d93d3.png)

**Comment by Qix-** [comment]
@cbdeveloper please see some of the pinned issues regarding customizing output.
