### ISSUE TITLE
remove all prefixes?

### ISSUE THREAD

**Issue by dcsan** [visionmedia/debug#222]
I'm trying to use debug to debug my tests. is there a way to remove all the timestamp and info before my message? I get a bunch of:

```
Sun, 13 Sep 2015 04:05:29 GMT mbot:WeChatAdapter .... debug msg
```

at the beginning of every line.

i guess i could pipe the output through sed but maybe there are some option params to reduce the clutter that can be passed to debug directly?

**Comment by dcsan** [comment]
```
DEBUG="mbot:*" DEBUG_DIFF=0 \
    jasmine-node --watch src --color --autotest $FILE1 | sed  's/.* mbot/-/g'
```
doesn't seem to do it for me.

**Comment by pulkitsinghal** [comment]
@dcsan - I don't think `debug` spits out that timestamp, something else must be appending it.

**Comment by dcsan** [comment]
dunno, i switched to log4js and havent looked back.

**Comment by thebigredgeek** [comment]
V3 is implementing the concept of middleware which should make this pretty easy.  Check it out here: https://github.com/visionmedia/debug/issues/370
