### ISSUE TITLE
Support Multi-Parameters

### ISSUE THREAD

**Issue by luqin** [visionmedia/debug#230]
like this:

``` js
import debug from 'debug/browser';

let error = debug('app:error');
error.log = console.error.bind(console);

error('1', 2, [1, 2]);
```

**Comment by TooTallNate** [comment]
That should already work fine. What are you experiencing?

**Comment by emilhem** [comment]
It seems like it works but it's producing the following output:
```
  app:error 1 +5ms 2 [ 1, 2 ]
```

The +5ms I think should be at the end.

I'm using version 2.2.0

**Comment by agirorn** [comment]
I'm guessing that you are getting the rest of the arguments by accident since debug only outputs the first argument and inlines all other arguments based on format. #140 #190 #293

```javascript
debug('format: %s -- %s', 'string 1', 'string 2') // -> 'format: -- string 1 -- string 2'
```

You could fix your code with this:

```javascript
error('1 %s %o', 2, [1, 2]); // -> 'app:error 1 2 [ 1, 2 ] +42s'
```
