### ISSUE TITLE
impact on production, how to use debug (use as devDependency?)

### ISSUE THREAD

**Issue by thisconnect** [visionmedia/debug#233]
I first used debug as devDependency, but obviously that would not work.

What is the perf impact on a debug call in production, i.e. process.env.DEBUG not set or NODE_ENV = production?

Is it recommended to wrap debug in a separate file and use `require('./debug.js')`, that way it could be a devDependency.

```javascript
if (!!process.env.DEBUG || process.env.NODE_ENV != 'production'){
    try {
        module.exports = require('debug');
        return;
    } catch(e){}
}

module.exports = function(){
    return function(){};
};
```
Would anybody recommend using or not using debug like that?

Thanks for your help

**Comment by stephenmathieson** [comment]
why bother? just don't set the debug env in production

**Comment by thisconnect** [comment]
@stephenmathieson so you have debug as dependecy (instead of devDependecy) and call it everywhere even if when process.env.DEBUG is not set?

**Comment by thisconnect** [comment]
```javascript
var debug = require('debug')('debug');
console.log(debug.toString());
// logs
// function disabled() {
//  }
```

OK without DEBUG it is actually an empty function, (if my test is correct). So no impact other than calling an empty function. If this is correct, I guess my only question is, is this correct and do people use debug as regular dependency.

**Comment by stephenmathieson** [comment]
why not have it as a regular dependency?  i guess i don't understand the actual issue here

**Comment by thisconnect** [comment]
The impact of calling debug without `process.env.DEBUG` is negligible, as if I understand it correctly, it is like calling an empty function everywhere. Closing…
