### ISSUE TITLE
why process.env['DEBUG'] = 'myprj:*'; does not work on windows?

### ISSUE THREAD

**Issue by eriknyk** [visionmedia/debug#235]
Hi in my project for development env I'm setting process.env['DEBUG'] = 'myprj:*'; explicitly
it works fine on OSX and Linux but not on Windows,.. can you tell me why?
and if there is another alternative than using external command SET on windows, I think if 
process.env['DEBUG'] = 'myprj:*'; works on osx and linux it should be works on windows too.

Best Regards.

**Comment by TooTallNate** [comment]
Can you show me your code that's using debug?

**Comment by mrpeu** [comment]
It should work. I have it running on Win7
