### ISSUE TITLE
Can't save debug output to a file

### ISSUE THREAD

**Issue by wodog** [visionmedia/debug#236]
i write this `# DEBUG=* node debug-text.js > out` in my linux.
but nothing find in out file.

How can i  get debug output file ?

**Comment by TooTallNate** [comment]
The debug output goes to `stderr`. So you could do `DEBUG=* node debug-text.js 2> out` (note the 2 in front of the `>` sign).

Also see https://github.com/visionmedia/debug#save-debug-output-to-a-file.
