### ISSUE TITLE
Enabling debuggin requires page reload

### ISSUE THREAD

**Issue by nbansalvox** [visionmedia/debug#238]
Hello,

I'm using a javascript library which is internally using Node debug module to enable debugging. I have noticed that calling .debug.enabled() doesn't enable the logs immediately, I need to reload the page to enable debug logs.
Is there a way that debugging is enabled on the first page load itself?

P.S: I'm running a plain javascript app, not a node app.

Regards,
Nitesh

**Comment by ibc** [comment]
There are some pull requests for this, but the author has decided to ignored them. For example https://github.com/visionmedia/debug/pull/209.
