### ISSUE TITLE
Presence of "document" can't be assumed for web workers

### ISSUE THREAD

**Issue by nolanlawson** [visionmedia/debug#240]
Currently `debug` fails in a web worker, because `document` is not available.

Background: https://github.com/pouchdb/pouchdb/issues/4612

**Comment by botverse** [comment]
Same happens with any non node scope that doesn't have access to document:

As mentioned in this issue, web workers. 
Service workers 
Webkit based environments like electron #303 
React Native #286

**Comment by nikcorg** [comment]
Fix for workers is in https://github.com/visionmedia/debug/pull/139 since late 2014.

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/pull/298 < Already live.  Closing
