### ISSUE TITLE
[Freature Request] Make `debug()` return the first argument?

### ISSUE THREAD

**Issue by jluchiji** [visionmedia/debug#248]
I thought sometimes it could be convenient to use `debug` as a wrapper, where it would return its first arguments as is. For example:

```
const fs = require('fs');
const debug = require('debug')('myproj');

const path = './some/file.txt';
fs.readFileSync(debug(path));
```

The above code would print the value of `path` and return it, passing it to `fs.readFileSync`. This approach could be useful when function arguments are themselves expressions, and it is necessary to quickly print its value without copy-pasting the expression to create a temporary variable.

Considering that at this moment `debug()` seems to return `undefined`, I think this is a change that can be implemented.

I'd love to hear your opinions on this one.

**Comment by evan-king** [comment]
Would you really want it to be the first argument, or maybe the last?

```javascript
const fs = require('fs');
const debug = require('debug')('myproj');

const path = './some/file.txt';
fs.readFileSync(debug('loading data from', path));
```

**Comment by mooyoul** [comment]
Why don't you wrap `debug` function?
You can archive goal like this way:

```
'use strict';

const debug = (namespace) => {
  const log = require('debug')(namespace);
  return (...args) => {
    log.apply(null, args);

    return args[0];
  };
};
```

<img width="553" alt="2016-04-09 6 08 38" src="https://cloud.githubusercontent.com/assets/2101743/14397663/a846a2ba-fe19-11e5-9d57-ae6551cf7a39.png">
> Note that `--harmony` flag was used.

**Comment by mooyoul** [comment]
/ping @TooTallNate I think this issue can be closed :)
