### ISSUE TITLE
Being able to list which debug are available.

### ISSUE THREAD

**Issue by SkinyMonkey** [visionmedia/debug#255]
I just created a thin wrapper around debug that could be useful when discovering/debugging an unknown project.
I tried to use wildcards but it's very messy.

```
const debug = function (name) {
  if (process.env.DEBUG && process.env.DEBUG == 'help') {
    console.log('available debug ' + name);
  }
  return require('debug')(name);
}
```

(The implementation is not the best i'm sure but it's not the point)
Is there any feature like this?
Do you think it could be useful?

**Comment by thebigredgeek** [comment]
We don't want to keep references to debug instances internally, as that is technically a leak, so I don't think we are going to implement anything like this for the time being
