### ISSUE TITLE
Disabling debug in Google Chrome

### ISSUE THREAD

**Issue by opportunato** [visionmedia/debug#256]
Hello!

I've been getting a log like this in dev environment.
<img width="322" alt="screen shot 2016-01-26 at 17 30 52" src="https://cloud.githubusercontent.com/assets/1570637/12583230/b55b5cee-c452-11e5-97de-c2c3c563d7ba.png">

As far as I know from the source code, fluxible is using debug for debugging. And so I've been wondering, how do I turn off debug debugging in a dev environment? What is the root cause of this happening? How do I debug this debug?

**Comment by stephenmathieson** [comment]
do

```js
localStorage.debug = ''
````

to remove all debug output, or

```js
localStorage.debug = '-Fluxible'
```

to remove the specific debugger

**Comment by opportunato** [comment]
Worked, thank you very much!
