### ISSUE TITLE
multiple instances on the same namespace get different colors

### ISSUE THREAD

**Issue by zacronos** [visionmedia/debug#258]
If I create multiple instances with the same namespace, they will each acquire a different color.  This is very counter-intuitive to me; if I am creating multiple loggers on the same namespace then by definition I want them to be treated as a single unit.  If I wanted them to be separate, I would if nothing else use different namespaces with a common prefix.

Example:

``` js
var debug = require('debug');
debug.enable('foo');

// shouldn't these use the same color?
var logger1 = debug('foo');
var logger2 = debug('foo');
```

I'm currently working around this in my app by wrapping `debug` with some code that caches the result by namespace, but it really seems like this functionality should be internal to `debug`.

I'm happy to submit a PR for this, if I get feedback that others agree this should be changed.

**Comment by stephenmathieson** [comment]
why would you want multiple debuggers with the same name?  the entire purpose of the name is to be unique

in your example, you could do:

```js
var logger1 = debug('foo')
var logger2 = logger1

logger1('hi')
logger2('hello')
```

...but that seems pretty pointless imo

**Comment by zacronos** [comment]
@stephenmathieson, of course that's a simplified example.

Agreed, the purpose of the name is to be unique, so IF someone creates 2 loggers with the same name, that means the loggers should be the same -- either 2 instances with the same color, or perhaps even get the same instance should be returned.  Neither is true right now.

As a better example, if I have 2 different modules and I wish them to use the same logger, right now I either have to tolerate them getting different colors, or else create my own way of caching/passing the logger so they can share an instance.

**Comment by stephenmathieson** [comment]
> if I have 2 different modules and I wish them to use the same logger

that would defeat the purpose of naming the loggers... how would you be able to tell them apart?

**Comment by zacronos** [comment]
From my perspective, the question of "how would you be able to tell them apart?" is exactly backwards.  The point is that if make 2 calls to `debug()` with the same name, I **shouldn't** be able to tell the resulting loggers apart.  I should either get the same logger back each time, or I should get 2 logger instances that have the same color/behavior (even if technically `logger1 !== logger2`).  Currently, that's not what happens.

As to explaining why I might want to do this...  it seems only tangentially relevant, but here goes.

Let's say I have a service with 2 files of helpers used by that service (maybe 1 dedicated to webhook/event handling, and 1 dedicated to db interactions, while the main file creates an API for high-level interactions).  I want logging from all 3 files to have the same color, for visual grouping.  I also don't expect it to ever be useful to turn logging on or off in one of those files without having it for all 3.  In that setup, the logical thing to do is to use the same logger/name in all 3 files.

The reason I want to group some of the logging together rather than just using an additional namespace suffix, is that this is a very large project -- with over 500 files of code.  I don't need to have control over every single file individually.  I don't really want to have 500+ different logging names.  And most importantly, I can't have 500+ visually distinct colors.  I already have a logging decorator that prefixes each line of logging with the originating file name and line number.  So I want my logging names to correspond to logical code areas, not simply 1 per file.  Some files may use more than 1 logger.  Some loggers may get used from more than 1 file.

**Comment by d-oliveros** [comment]
+1

**Comment by pabigot** [comment]
Another +1.  It hadn't even occurred to me that:

    const debugWarn = require('debug')('X:warn')

in two source files that comprise part of the `X` system would not resolve to the same debug instance, until I started seeing unexpected behavior and found this issue.

**Comment by duanefields** [comment]
+1, for what it's worth where I see this is simply splitting my project into lots of small files, all using the same 1 or 2 different debugging namespaces. Rather than random, I think hashing on the name and using a deterministic strategy seems appropriate.

**Comment by lchenay** [comment]
+1 on this feature.

**Comment by thebigredgeek** [comment]
This should be fixed.
