### ISSUE TITLE
npm WARN enoent ENOENT: no such file or directory, open '<root>/node_modules/supertest/package.json'

### ISSUE THREAD

**Issue by synthecypher** [visionmedia/debug#261]
I installed `supertest` before installing `debug` and it fixed this error.

Maybe make it a dependency of this module?

**Comment by mooyoul** [comment]
No. That's not an issue of `debug` package.
I think it's related to NPM v3's changed installation behavior.

You can resolve that issue by following methods:
1. Ensure dependencies described correctly on `package.json`
2. Just type `npm install` and hit Enter.
3. Check issue still exists. and If issue not resolved, continue these methods.
4. type `npm cache clean` and hit Enter
5. type `sudo npm install -g npm ` and hit Enter.
6. Retry `npm install` and hit Enter.

if issue not resolved even tried these methods, Please reply with your Node.js version, NPM version, Operating System, and `package.json` which is using.

**Comment by FaShapouri** [comment]
@mooyoul I have that problem and tried your solution. But my problem did not resolve.
I am using mac os 10.11.4 and Node 6.2.2 and npm 3.9.5

The node_modules is in user/muser/node_modules/
I see mysql package in this folder
But when I try `nam install`, below message appears on terminal:
```
npm WARN enoent ENOENT: no such file or directory, open '/Users/muser/package.json'
npm WARN muser No description
npm WARN muser No repository field.
npm WARN muser No README data
npm WARN muser No license field.
```
There is no package.json at  `'/Users/muser/package.json' `

What is wrong in my setup? and how can I fix it.

**Comment by mooyoul** [comment]
@FaShapouri It seems trying `npm install` in uninitialized npm package directory.
you should initialize package with `npm init`.
If you want to use debug without package initialize, just use `npm install debug`.

**Comment by Okezie** [comment]
Simply try npm install npm@latest -g  it  worked  for me cheers.

**Comment by TooTallNate** [comment]
This module does not use `supertest`, and thus is not an issue for debug. Closing.

**Comment by MuhammdRiscoR80** [comment]
Try to change your node.js version

**Comment by osa9j** [comment]
i am having problem installing npm ...it keep getting this:
npm WARN enoent ENOENT: no such file or directory, open '/Users/jamesosaedebiri/package.json'

**Comment by pierinocipolloni** [comment]
Indeed what it wants is a package.json file, obtained by typing npm init. Then I was able to do an npm install with success.

**Comment by anilkumarsoni** [comment]
WARN enoent ENOENT: no such file or directory, open '/home/nodeuser/hapi-mysql-unchained/node_modules/request/package.json'
npm WARN hapi-mysql-unchained@1.0.0 No description
npm WARN hapi-mysql-unchained@1.0.0 No repository field.
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v4.2.0
npm ERR! path /home/nodeuser/hapi-mysql-unchained/node_modules/node-pre-gyp/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/home/nodeuser/hapi-mysql-unchained/node_modules/node-pre-gyp/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/home/nodeuser/hapi-mysql-unchained/node_modules/node-pre-gyp/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/nodeuser/hapi-mysql-unchained/node_modules/node-pre-gyp/node_modules' }

**Comment by mukun-bhatta** [comment]
1. node.js version - v7.7.1
2. npm version - 4.3.0
3. operating system ubuntu 14.04
4. package.json at /home/mukun/package.json is not there

**Comment by shmooth** [comment]
if you are pretty new to Node/github/etc., you might be doing what I did -- cloned a repo and then forgot to cd into the repo directory -- so npm can't find a package.json file, so it gives you that big convoluted error message.

i was operating in my main 'dev' directory:

`~/dev$ npm install`

but i needed to be in my cloned git directory:

`~/dev/quiztool$ npm install`

**Comment by MarcioDuran** [comment]
ubuntu@ubuntu:~$ npm install debug 
npm ERR! Linux 4.8.0-22-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v7.7.2/bin/node" "/home/ubuntu/.nvm/versions/node/v7.7.2/bin/npm" "install" "debug"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log

**Comment by sudosoph** [comment]
`npm init`

http://weaintplastic.github.io/web-development-field-guide/Development/Frontend_Development/Setting_up_your_project/Setup_Dependency_Managers/Node_Package_Manager/Initialize_NPM_on_a_new_project.html

**Comment by sudosoph** [comment]
If you don't initialize your repo using `npm init` and complete package.json fields properly (or leave some blank), you might still get warnings. I followed this template and errors are gone: https://docs.npmjs.com/getting-started/using-a-package.json

**Comment by WJLkalin** [comment]
you can try "npm install -g bootstrap@4.0.0-alpha.6", i did it successfully in this way.

**Comment by amaljose01** [comment]
Please try,  npm install npm@latest -g

the output you will get as below

C:\Users\*****\AppData\Roaming\npm\npm -> C:\Users\*****\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\*****\AppData\Roaming\npm
`-- npm@4.4.4
  +-- abbrev@1.1.0
  +-- ansi-regex@2.1.1
  +-- ansicolors@0.3.2
  +-- ansistyles@0.1.3
  +-- aproba@1.1.1
  +-- archy@1.0.0
  +-- asap@2.0.5
  +-- bluebird@3.5.0
  +-- call-limit@1.1.0
  +-- chownr@1.0.1
  +-- cmd-shim@2.0.2
  +-- columnify@1.5.4
  | `-- wcwidth@1.0.0
  |   `-- defaults@1.0.3
  |     `-- clone@1.0.2
  +-- config-chain@1.1.11
  | `-- proto-list@1.2.4
  +-- debuglog@1.0.1
  +-- dezalgo@1.0.3
  +-- editor@1.0.0
  +-- fs-vacuum@1.2.10
  +-- fs-write-stream-atomic@1.0.10
  +-- fstream@1.0.11
  +-- fstream-npm@1.2.0
  | `-- fstream-ignore@1.0.5
  |   `-- minimatch@3.0.3
  |     `-- brace-expansion@1.1.6
  |       +-- balanced-match@0.4.2
  |       `-- concat-map@0.0.1
  +-- glob@7.1.1
  | +-- fs.realpath@1.0.0
  | +-- minimatch@3.0.3
  | | `-- brace-expansion@1.1.6
  | |   +-- balanced-match@0.4.2
  | |   `-- concat-map@0.0.1
  | `-- path-is-absolute@1.0.1
  +-- graceful-fs@4.1.11
  +-- has-unicode@2.0.1
  +-- hosted-git-info@2.2.0
  +-- iferr@0.1.5
  +-- imurmurhash@0.1.4
  +-- inflight@1.0.6
  +-- inherits@2.0.3
  +-- ini@1.3.4
  +-- init-package-json@1.9.5
  | `-- promzard@0.3.0
  +-- JSONStream@1.3.1
  | +-- jsonparse@1.3.0
  | `-- through@2.3.8
  +-- lazy-property@1.0.0
  +-- lockfile@1.0.3
  +-- lodash._baseindexof@3.1.0
  +-- lodash._baseuniq@4.6.0
  | +-- lodash._createset@4.0.3
  | `-- lodash._root@3.0.1
  +-- lodash._bindcallback@3.0.1
  +-- lodash._cacheindexof@3.0.2
  +-- lodash._createcache@3.1.2
  +-- lodash._getnative@3.9.1
  +-- lodash.clonedeep@4.5.0
  +-- lodash.restparam@3.6.1
  +-- lodash.union@4.6.0
  +-- lodash.uniq@4.5.0
  +-- lodash.without@4.4.0
  +-- mississippi@1.3.0
  | +-- concat-stream@1.6.0
  | | `-- typedarray@0.0.6
  | +-- duplexify@3.5.0
  | | +-- end-of-stream@1.0.0
  | | | `-- once@1.3.3
  | | `-- stream-shift@1.0.0
  | +-- end-of-stream@1.1.0
  | | `-- once@1.3.3
  | +-- flush-write-stream@1.0.2
  | +-- from2@2.3.0
  | +-- parallel-transform@1.1.0
  | | `-- cyclist@0.2.2
  | +-- pump@1.0.2
  | +-- pumpify@1.3.5
  | +-- stream-each@1.2.0
  | | `-- stream-shift@1.0.0
  | `-- through2@2.0.3
  |   `-- xtend@4.0.1
  +-- mkdirp@0.5.1
  | `-- minimist@0.0.8
  +-- move-concurrently@1.0.1
  | +-- copy-concurrently@1.0.3
  | `-- run-queue@1.0.3
  +-- node-gyp@3.5.0
  | +-- minimatch@3.0.3
  | | `-- brace-expansion@1.1.6
  | |   +-- balanced-match@0.4.2
  | |   `-- concat-map@0.0.1
  | `-- nopt@3.0.6
  +-- nopt@4.0.1
  | `-- osenv@0.1.4
  |   +-- os-homedir@1.0.2
  |   `-- os-tmpdir@1.0.2
  +-- normalize-git-url@3.0.2
  +-- normalize-package-data@2.3.6
  | `-- is-builtin-module@1.0.0
  |   `-- builtin-modules@1.1.1
  +-- npm-cache-filename@1.0.2
  +-- npm-install-checks@3.0.0
  +-- npm-package-arg@4.2.1
  +-- npm-registry-client@7.4.6
  | `-- concat-stream@1.6.0
  |   `-- typedarray@0.0.6
  +-- npm-user-validate@0.1.5
  +-- npmlog@4.0.2
  | +-- are-we-there-yet@1.1.2
  | | `-- delegates@1.0.0
  | +-- console-control-strings@1.1.0
  | +-- gauge@2.7.2
  | | +-- object-assign@4.1.0
  | | +-- signal-exit@3.0.2
  | | +-- string-width@1.0.2
  | | | +-- code-point-at@1.1.0
  | | | `-- is-fullwidth-code-point@1.0.0
  | | |   `-- number-is-nan@1.0.1
  | | +-- supports-color@0.2.0
  | | `-- wide-align@1.1.0
  | `-- set-blocking@2.0.0
  +-- once@1.4.0
  +-- opener@1.4.3
  +-- osenv@0.1.4
  | +-- os-homedir@1.0.2
  | `-- os-tmpdir@1.0.2
  +-- path-is-inside@1.0.2
  +-- read@1.0.7
  | `-- mute-stream@0.0.5
  +-- read-cmd-shim@1.0.1
  +-- read-installed@4.0.3
  | `-- util-extend@1.0.3
  +-- read-package-json@2.0.5
  | `-- json-parse-helpfulerror@1.0.3
  |   `-- jju@1.3.0
  +-- read-package-tree@5.1.5
  +-- readable-stream@2.2.3
  | +-- buffer-shims@1.0.0
  | +-- core-util-is@1.0.2
  | +-- isarray@1.0.0
  | +-- process-nextick-args@1.0.7
  | +-- string_decoder@0.10.31
  | `-- util-deprecate@1.0.2
  +-- readdir-scoped-modules@1.0.2
  +-- realize-package-specifier@3.0.3
  +-- request@2.81.0
  | +-- aws-sign2@0.6.0
  | +-- aws4@1.6.0
  | +-- caseless@0.12.0
  | +-- combined-stream@1.0.5
  | | `-- delayed-stream@1.0.0
  | +-- extend@3.0.0
  | +-- forever-agent@0.6.1
  | +-- form-data@2.1.2
  | | `-- asynckit@0.4.0
  | +-- har-validator@4.2.1
  | | +-- ajv@4.11.4
  | | | +-- co@4.6.0
  | | | `-- json-stable-stringify@1.0.1
  | | |   `-- jsonify@0.0.0
  | | `-- har-schema@1.0.5
  | +-- hawk@3.1.3
  | | +-- boom@2.10.1
  | | +-- cryptiles@2.0.5
  | | +-- hoek@2.16.3
  | | `-- sntp@1.0.9
  | +-- http-signature@1.1.1
  | | +-- assert-plus@0.2.0
  | | +-- jsprim@1.3.1
  | | | +-- extsprintf@1.0.2
  | | | +-- json-schema@0.2.3
  | | | `-- verror@1.3.6
  | | `-- sshpk@1.11.0
  | |   +-- asn1@0.2.3
  | |   +-- assert-plus@1.0.0
  | |   +-- bcrypt-pbkdf@1.0.1
  | |   +-- dashdash@1.14.1
  | |   +-- ecc-jsbn@0.1.1
  | |   +-- getpass@0.1.6
  | |   +-- jodid25519@1.0.2
  | |   +-- jsbn@0.1.1
  | |   `-- tweetnacl@0.14.5
  | +-- is-typedarray@1.0.0
  | +-- isstream@0.1.2
  | +-- json-stringify-safe@5.0.1
  | +-- mime-types@2.1.14
  | | `-- mime-db@1.26.0
  | +-- oauth-sign@0.8.2
  | +-- performance-now@0.2.0
  | +-- qs@6.4.0
  | +-- safe-buffer@5.0.1
  | +-- stringstream@0.0.5
  | +-- tough-cookie@2.3.2
  | | `-- punycode@1.4.1
  | `-- tunnel-agent@0.6.0
  +-- retry@0.10.1
  +-- rimraf@2.6.1
  +-- semver@5.3.0
  +-- sha@2.0.1
  +-- slide@1.1.6
  +-- sorted-object@2.0.1
  +-- sorted-union-stream@2.1.3
  | +-- from2@1.3.0
  | | `-- readable-stream@1.1.14
  | |   +-- core-util-is@1.0.2
  | |   +-- isarray@0.0.1
  | |   `-- string_decoder@0.10.31
  | `-- stream-iterate@1.1.1
  +-- strip-ansi@3.0.1
  +-- tar@2.2.1
  | `-- block-stream@0.0.8
  +-- text-table@0.2.0
  +-- uid-number@0.0.6
  +-- umask@1.1.0
  +-- unique-filename@1.1.0
  | `-- unique-slug@2.0.0
  +-- unpipe@1.0.0
  +-- update-notifier@2.1.0
  | +-- boxen@1.0.0
  | | +-- ansi-align@1.1.0
  | | | `-- string-width@1.0.2
  | | |   +-- code-point-at@1.1.0
  | | |   `-- is-fullwidth-code-point@1.0.0
  | | |     `-- number-is-nan@1.0.1
  | | +-- camelcase@4.0.0
  | | +-- cli-boxes@1.0.0
  | | +-- string-width@2.0.0
  | | | `-- is-fullwidth-code-point@2.0.0
  | | +-- term-size@0.1.1
  | | | `-- execa@0.4.0
  | | |   +-- cross-spawn-async@2.2.5
  | | |   | `-- lru-cache@4.0.2
  | | |   |   +-- pseudomap@1.0.2
  | | |   |   `-- yallist@2.0.0
  | | |   +-- is-stream@1.1.0
  | | |   +-- npm-run-path@1.0.0
  | | |   +-- object-assign@4.1.1
  | | |   +-- path-key@1.0.0
  | | |   `-- strip-eof@1.0.0
  | | `-- widest-line@1.0.0
  | |   `-- string-width@1.0.2
  | |     +-- code-point-at@1.1.0
  | |     `-- is-fullwidth-code-point@1.0.0
  | |       `-- number-is-nan@1.0.1
  | +-- chalk@1.1.3
  | | +-- ansi-styles@2.2.1
  | | +-- escape-string-regexp@1.0.5
  | | +-- has-ansi@2.0.0
  | | `-- supports-color@2.0.0
  | +-- configstore@3.0.0
  | | +-- dot-prop@4.1.1
  | | | `-- is-obj@1.0.1
  | | `-- unique-string@1.0.0
  | |   `-- crypto-random-string@1.0.0
  | +-- is-npm@1.0.0
  | +-- latest-version@3.0.0
  | | `-- package-json@3.1.0
  | |   +-- got@6.7.1
  | |   | +-- create-error-class@3.0.2
  | |   | | `-- capture-stack-trace@1.0.0
  | |   | +-- duplexer3@0.1.4
  | |   | +-- get-stream@3.0.0
  | |   | +-- is-redirect@1.0.0
  | |   | +-- is-retry-allowed@1.1.0
  | |   | +-- is-stream@1.1.0
  | |   | +-- lowercase-keys@1.0.0
  | |   | +-- safe-buffer@5.0.1
  | |   | +-- timed-out@4.0.1
  | |   | +-- unzip-response@2.0.1
  | |   | `-- url-parse-lax@1.0.0
  | |   |   `-- prepend-http@1.0.4
  | |   +-- registry-auth-token@3.1.0
  | |   | `-- rc@1.1.7
  | |   |   +-- deep-extend@0.4.1
  | |   |   +-- minimist@1.2.0
  | |   |   `-- strip-json-comments@2.0.1
  | |   `-- registry-url@3.1.0
  | |     `-- rc@1.1.7
  | |       +-- deep-extend@0.4.1
  | |       +-- minimist@1.2.0
  | |       `-- strip-json-comments@2.0.1
  | +-- lazy-req@2.0.0
  | +-- semver-diff@2.1.0
  | `-- xdg-basedir@3.0.0
  +-- uuid@3.0.1
  +-- validate-npm-package-license@3.0.1
  | +-- spdx-correct@1.0.2
  | | `-- spdx-license-ids@1.2.0
  | `-- spdx-expression-parse@1.0.2
  |   +-- spdx-exceptions@1.0.4
  |   `-- spdx-license-ids@1.2.0
  +-- validate-npm-package-name@3.0.0
  | `-- builtins@1.0.3
  +-- which@1.2.12
  | `-- isexe@1.1.2
  +-- wrappy@1.0.2
  `-- write-file-atomic@1.3.1


later install bootstrap, try below
$ npm install -g bootstrap@4.0.0-alpha.6

C:\Users\******\AppData\Roaming\npm
`-- bootstrap@4.0.0-alpha.6
  +-- jquery@3.2.1
  `-- tether@1.4.0

**Comment by jitendragupta2** [comment]
while publishing my package was having package.json... so why it is not downloaded when i am installing my package

**Comment by ctoxyz** [comment]
New to node... setup EC2 > AMAZON linux.. Node setup.. tried all kinds of version..

no matter what i do, errors are obtained during install..

tried npm init... tried diff versions of all parts... still I can't get a successful install & test code always fails.

Errors below.  Please advise

npm install pdfkit
npm WARN saveError ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm WARN ec2-user No description
npm WARN ec2-user No repository field.
npm WARN ec2-user No README data
npm WARN ec2-user No license field.
npm WARN ec2-user Invalid dependency: png-js undefined

No matter what I install or how, i get these:

npm WARN saveError ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ec2-user/package.json'

**Comment by mihai-ciupina** [comment]
You have to cd into location where package.json is; like assets in phoenix 1.3.x

**Comment by abdulmanan123** [comment]
Angular 2 project not run forever show these errors:
npm ERR! path /package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-05-30T12_02_40_976Z-debug.log
error: Forever detected script exited with code: 254
error: Script restart attempt #1
npm ERR! path /package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by jimmymixer** [comment]
OS: Mac Sierra 10.12.5
Node v8.0.0.0
NPM v5.0.0

I'm having the same problem as well.  I can't seem to resolve this.  I've tried both with and without sudo.  I do have other programs installed in my computer.  Don't know if that has something to do with it.  I have all of the Python Stack and Ruby Stack installed.  Now trying to get all the MEAN Stack components installed.  

Below is what I'm getting back.   Any help would be greatly appreciated.  When it talks about dependencies, I have no idea what that is..  Sorry for my poor knowledge.

TERMINAL:
Jaes-MacBook-Pro:bower_install jaepark75$ sudo npm install jquery
Password:
npm WARN saveError ENOENT: no such file or directory, open '/Users/jaepark75/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/jaepark75/package.json'
npm WARN jaepark75 No description
npm WARN jaepark75 No repository field.
npm WARN jaepark75 No README data
npm WARN jaepark75 No license field.
npm WARN jaepark75 Invalid dependency: balanced-match undefined
npm WARN jaepark75 Invalid dependency: block-stream undefined
npm WARN jaepark75 Invalid dependency: brace-expansion undefined
npm WARN jaepark75 Invalid dependency: concat-map undefined
npm WARN jaepark75 Invalid dependency: fs.realpath undefined
npm WARN jaepark75 Invalid dependency: fstream undefined
npm WARN jaepark75 Invalid dependency: glob undefined
npm WARN jaepark75 Invalid dependency: graceful-fs undefined
npm WARN jaepark75 Invalid dependency: hammerjs undefined
npm WARN jaepark75 Invalid dependency: inflight undefined
npm WARN jaepark75 Invalid dependency: inherits undefined
npm WARN jaepark75 Invalid dependency: materialize-css undefined
npm WARN jaepark75 Invalid dependency: minimatch undefined
npm WARN jaepark75 Invalid dependency: minimist undefined
npm WARN jaepark75 Invalid dependency: mkdirp undefined
npm WARN jaepark75 Invalid dependency: node-archiver undefined
npm WARN jaepark75 Invalid dependency: once undefined
npm WARN jaepark75 Invalid dependency: path-is-absolute undefined
npm WARN jaepark75 Invalid dependency: rimraf undefined
npm WARN jaepark75 Invalid dependency: tar undefined
npm WARN jaepark75 Invalid dependency: wrappy undefined

updated 1 package in 4.539s

**Comment by karbon62** [comment]
Hi,  

I've got the same problem here and tried to run the following commands above to fix this. "Clean Cache" & "re-install". Unfortunately it didn't fix it for me. Seems to have spawned another issue. 

/Users/Karbon62/.npm/_logs/2017-06-05T14_42_36_153Z-debug.log

**Comment by karbon62** [comment]
Before running the commands to fix this, my console was giving me this error: 

file:///Users/Karbon62/.npm/_logs/2017-06-05T12_47_17_209Z-debug.log

**Comment by tylo6** [comment]
OS: Mac Sierra 10.12.5
Node v8.0.0.0
NPM v5.0.2

i've the same probelm than jimmymixer whitout sucess.
If any have a idea to dig… Thank

**TERMINAL**:
_MacBook-Air-de-happy:~ happy$ npm install airsonos -g
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/airsonos -> /usr/local/lib/node_modules/airsonos/bin/index.js
+ airsonos@0.2.6_

then i installed latest "minimatch", "serve-favicon" and "react"
then

**TERMINAL**:
_MacBook-Air-de-happy:~ happy$ airsonos
Searching for Sonos devices on network...

/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
Error: Internal Server Error
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/request/request.js:129:22)_

**Comment by travisgillespie** [comment]
This npm [video](https://docs.npmjs.com/getting-started/installing-npm-packages-locally) helped me. 
- Create a _package.json_ file and store it in the folder where you will install the npm package. Keep it simple for now. Again the video above helped.
{
	"name": "node",
	"version": "1.0.0"
}

- Open Terminal: as @mihai-ciupina said... cd to the location where you want to store the package locally. If you type _ls_ you should see the _package.json_ file you just created.
- Type: _npm install <package_name>_. The video discusses variations you can type.
- I'm not sure why, but my folder also created a package-lock.json file. I will have to do some more reading on this topic.

**Comment by mocombeg** [comment]
Im trying to install gulp and I keep having thises issues:
Ive tried many remedies including: npm install npm@latest and still no progress.

C:\Users\home>npm install npm@latest -g
C:\Users\home\AppData\Roaming\npm\npm -> C:\Users\home\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
+ npm@5.0.3
updated 1 package in 24.356s

C:\Users\M-Corp>npm install gulp
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\home\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\home\package.json'
npm WARN home No description
npm WARN home No repository field.
npm WARN home No README data
npm WARN home No license field.

+ gulp@3.9.1
updated 1 package in 2.495s

C:\Users\home>

**Comment by avriLee** [comment]
u just need to create package.json file in the needing directory, and enter `npm init`. It's ok, and i tried successfully. Hope for u...

**Comment by LabAviator** [comment]
Did anyone find a solution to this yet?

**Comment by michael-ecb** [comment]
Simply remove node_modules then run again 'npm install'

**Comment by chethankumaril** [comment]
when i run
`$ npm install express`, i got the following error.

> rank@rank-ThinkCentre-M73:~$ npm install express
npm ERR! Linux 3.16.0-57-generic
npm ERR! argv "/home/rank/.nvm/versions/node/v5.0.0/bin/node" "/home/rank/.nvm/versions/node/v5.0.0/bin/npm" "install" "express"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 127.0.0.1:8080
npm ERR!     at Object.exports._errnoException (util.js:860:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:883:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
npm ERR!  { [Error: connect ECONNREFUSED 127.0.0.1:8080]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 8080 }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rank/npm-debug.log
rank@rank-ThinkCentre-M73:~$

**Comment by Qix-** [comment]
`debug` is not a repository to post your generic NPM-related problems; it's a specific package that has nothing to do with most of the comments here.

Locking due to chatter. If you're having lots of problems with NPM, might I suggest [StackOverflow](https://stackoverflow.com/questions/tagged/npm) (please **search first** before asking a question).
