### ISSUE TITLE
Bad usage of arguments hits performance: "Not optimized: Bad value context for arguments value" on chrome

### ISSUE THREAD

**Issue by murillo128** [visionmedia/debug#262]
Doing a performance tuning of my app, i found that debug was consuming way to much time.

It is probably caused by:

```
    var args = Array.prototype.slice.call(arguments);

    args[0] = exports.coerce(args[0]);
```

That yields a warning on profiler: "Not optimized: Bad value context for arguments value"

More info here:

http://techblog.dorogin.com/2015/05/performance-loss-on-incorrect-arguments-using.html

**Comment by murillo128** [comment]
Seems that the patch would be quite easy:
```
var i, args = new Array(arguments.length-1);
for (i = 1; i < arguments.length; ++i) { args[i - 1] = arguments[i]; }
```

**Comment by stephenmathieson** [comment]
quick fix: don't enable debugs in performance sensitive envs

**Comment by thebigredgeek** [comment]
I believe we implemented optimizations for this.  Closing
