### ISSUE TITLE
Is debug.namespace a public api ?

### ISSUE THREAD

**Issue by benpptung** [visionmedia/debug#268]
Hi :) 
Recently, I've noticed that most of my modules are using debug module.

```
const debug = require('debug')('moduname:xxx');
```

So I am wondering if I can reuse the `debug.namespace` in the same module ?
For example, maybe in a production environment, I need to `log.info()` or `log.warn()` something, can I write it like the following? So, I can keep debug namespace more consistent with logging information.

```
var libname = debug.namespace;
log.info(`${libname} underlying socket closed, reconnecting...`);
```

I know I can do it now. However, I am wondering if the `namespace` property will be changed in the future, because I see no documentation regarding this `debug.namespace` property. 

Thank you for your answer and this awesome tool. :)

**Comment by thebigredgeek** [comment]
@benpptung not sure if this will change
