### ISSUE TITLE
Add %O formatter

### ISSUE THREAD

**Issue by oncletom** [visionmedia/debug#278]
As of https://developer.chrome.com/devtools/docs/console-api#consolelogobject-object

> %O	Formats the value as an expandable JavaScript object.

Unless if it not a "standard"? I guess the formatting should be the same as if the object was passed as the first argument of `debug`.

```js
const payload = { hello: 'world' };

debug('%O', payload);
// ===
debug(payload)
```

Any opinion on this?

**Comment by oncletom** [comment]
Hm, it appears that actually this is the same as the `%o` formatter. Maybe just aliasing it to match other console implementations?

**Comment by TooTallNate** [comment]
For Node.js you mean? Ya sure, patch welcome.
