### ISSUE TITLE
RFC: 3.0 stdout moved off of APIs that are pending removal

### ISSUE THREAD

**Issue by ChALkeR** [visionmedia/debug#280]
It was never documented and was supposed to be internal.
Used at [node.js#L164](https://github.com/visionmedia/debug/blob/master/node.js#L164).

Refs: https://github.com/nodejs/node/pull/6749

**Comment by thebigredgeek** [comment]
lets discuss here

**Comment by ChALkeR** [comment]
I'm not quite sure what's going on with the «won't fix»/reopening/renaming and the proposed discussion, but I do have a quick question — does that line get called for a significant amount of `debug` users or not?

**Comment by TooTallNate** [comment]
@ChALkeR We're going to remove the offending code. Please see #406.

**Comment by ChALkeR** [comment]
@TooTallNate Thanks. Could you clarify for what usecases was that line called? Only when `DEBUG_FD` was set to something other than `1` and `2`, or for something even more specific?

**Comment by TooTallNate** [comment]
Correct, only when `DEBUG_FD` was something other than 1 or 2, which was a very low number people (in any...). I've never used it.

**Comment by TooTallNate** [comment]
@ChALkeR That said, even though debug no longer will use `createWritableStdioStream()`, it would be nice if Node.js exposed that kind of thing for other use-cases.

**Comment by TooTallNate** [comment]
Gonna close this btw, since the relevant PRs have been merged at this point.

**Comment by thebigredgeek** [comment]
Sgtm
