### ISSUE TITLE
Ability to disable ansi decoration part

### ISSUE THREAD

**Issue by jabaz** [visionmedia/debug#281]
I use Visual Studio Code to create and debug my application, and it doesn't support ansi color decoration.
When i write `console.log(\x1b[36;1m%s\x1b[0m, 'working')`
It prints this:
![11bc6a60-2221-11e6-9102-1f3f0600d9bd](https://cloud.githubusercontent.com/assets/13858505/15533048/61d86176-226b-11e6-8f9b-0d292724abc8.png)
But without decoration `console.log(\x1b[36m%s\x1b[0m, 'working')`
![3295fa1c-2221-11e6-9213-3e8dba93ceaa](https://cloud.githubusercontent.com/assets/13858505/15533121/c5716782-226b-11e6-8f07-1fda2433e73d.png)

Same goes if i use this debug extension, to print out, it shows sameway those ansi codes, with decoration.
![image](https://cloud.githubusercontent.com/assets/13858505/15533644/3c265674-226e-11e6-97af-e4911310481c.png)

So it would be good, to be able to disable use of ansi decorations and use only colors.

**Comment by stephenmathieson** [comment]
you can do:

```
$ DEBUG_COLORS=0 DEBUG=something node whatever.js
```

see https://github.com/visionmedia/debug/blob/2.2.0/node.js#L45-L53

**Comment by jabaz** [comment]
Yes i know but it's not so readable anymore

**Comment by jabaz** [comment]
I added pull request https://github.com/visionmedia/debug/pull/285, to be able to disable ansi decoration.
Just add `DEBUG_DISABLE_COLORDECOR=1` environment variable!

**Comment by thebigredgeek** [comment]
Closing this for now
