### ISSUE TITLE
How to transport logs from server to browser / color formaters

### ISSUE THREAD

**Issue by drcmda** [visionmedia/debug#284]
Right now on the server i'm trying

```
debug.log = function(txt) {
    console.log(txt)
    io.emit('log', txt);
}
```

But when triggered on the client i end up with console output like

```
[32;1mawv3:usr [0m[7m[33m/#-6U5EKGpLF5hn78tAAAK >> StoreState[39m[27m[32m +14ms[0m
```

Is there an option or API that can switch between stdout and console formaters?

**Comment by thebigredgeek** [comment]
Check out middleware discussion here:
https://github.com/visionmedia/debug/issues/370

Closing for now

**Comment by kilianc** [comment]
@drcmda I love debug so much that I built rtail around it: https://github.com/kilianc/rtail
