### ISSUE TITLE
Unable to output all logs to stdout

### ISSUE THREAD

**Issue by fantasy8-me** [visionmedia/debug#287]
I follow below example config the log to `console.log.bind(console)`, but found only it only works if I use `log('goes to stdout');`

```
var log = debug('app:log');
// set this namespace to log via console.log
log.log = console.log.bind(console); // don't forget to bind to console!
log('goes to stdout');

...
debug('app:log')('I want it goes to stdout too') //but it doesn't
```

After some study
https://github.com/visionmedia/debug/blob/master/debug.js#L121
https://github.com/visionmedia/debug/blob/master/debug.js#L70

Found the logger instance return by `debug([namespace])` is not always the same instance, can we enhance the lib to always return same instance for same namespace

**Comment by thebigredgeek** [comment]
@fantasy8-me we don't want to store references to debug instances internally as that could create leaks when the lib is used to create instances on the fly.  I think a better use case for you would be to create a debug instance and import it everywhere it is needed.  Closing this for now
