### ISSUE TITLE
Stringing building overhead

### ISSUE THREAD

**Issue by jduprey** [visionmedia/debug#290]
Feature request..

If debug is not enabled for a module the function is a no-op and adds very little overhead.  However, since you can only pass a string parameter, even if debug is disabled adding debug lines can add string building/concatenation overhead.

It would be a nice feature if this:
debug(req.method + ' ' + req.url);

.. could be done like this:
debug("%s %s", req.method, req.url);

This would avoid string processing and conversion when debug is disabled.

Otherwise, every debug statement that combines multiple values into a string in the debug parameter is wasted effort.

Thoughts?

**Comment by SimoneGianni** [comment]
AFAIK it already works like this, i always use that syntax, maybe I'm missing something in your report?

**Comment by TooTallNate** [comment]
Indeed, this already works exactly as described.

**Comment by jduprey** [comment]
You are right!  Sorry.

```
var dbg = window.debug('app:mod1');
dbg("%s %s", "one", "two");
```

Console:
```
app:mod1 one two +0ms
```
