### ISSUE TITLE
Nothing output

### ISSUE THREAD

**Issue by QianJin2013** [visionmedia/debug#291]
I am using Node.JS 6.2.2.
I can not believe this lib does not output anything now:

```
var debug = require('debug')('xxx');
debug("hihi");
```

It breaks many other dependent libs.

This works in several months ago, but not now.

I have traced into the code, but debug("xxx") will cause calling a function named `disabled`.

It seems i have to enable it explicitly?

**Comment by stephenmathieson** [comment]
yep, you have to enable it explicitly (which is the whole point of the lib):

`DEBUG=xxx node app.js`

**Comment by QianJin2013** [comment]
No problem. Thank you for your quick response.
I had used this lib indirectly from other lib, so not aware of this point. 
OK, i can use it directly now.

**Comment by stephenmathieson** [comment]
cool, glad we figured it out!!
