### ISSUE TITLE
Curried version for usage with promises and callbacks

### ISSUE THREAD

**Issue by naholyr** [visionmedia/debug#292]
In async operations you often have to just log something without breaking the chain. Take this example:

``` js
somePromise
.then(doSomething)
.then(doSomethingElse)
```

Now suppose I just want to debug the value between "doSomething" and "doSomethingElse", I'll have to add this:

``` js
somePromise
.then(doSomething)
.then(value => {
  debug('ze value', value)
  return value
}, err => {
  debug('ze error', err)
  throw err
})
.then(doSomethingElse)
```

Same with callbacks:

``` js
asyncOperation(cb)

// would become
asyncOperation((err, value) => {
  debug('ze result', err, value)
  cb(err, value)
})
```

I'd suggest to add some handy shortcuts to handle that in `debug`:

``` js
somePromise
.then(doSomething)
.then(debug.asap('ze result'), debug.asap('ze error'))
.then(doSomethingElse)

asyncOperation(debug.asap('ze result', cb))
```

Dumb implementation:

``` js
debug.asap = (message, cb) => {
  if (!cb) {
    // promise version
    return val => {
      debug(message, val)
      if (val instanceof Error) {
        throw val
      } else {
        return val
      }
    }
  } else {
    // callback version
    return (err, val) => {
      debug(message, err, val)
      cb(err, val)
    }
  }
}
```

What do you think? Not sure at all about the name, but I think it would be a nice addition to this library as it's a very common use case of a widely-used tool.

**Comment by stephenmathieson** [comment]
+1 for a wrapper

**Comment by sebinsua** [comment]
I actually created this last year: [**`tap-debug`**](https://github.com/sebinsua/tap-debug)

It does what you're looking for, plus has a few extra features for more complex logs.

**Comment by thebigredgeek** [comment]
Not sure that we'd really wanna do something like this in the core lib.  It seems like async/await being around the corner is the real solution here, as you won't need curry to make the code look clean for async stuff
