### ISSUE TITLE
Security issue dependance

### ISSUE THREAD

**Issue by Peltoche** [visionmedia/debug#294]
Hey! You have a security issue with the dependance ms. You should upgrade it to >=3.0.0.

More info: https://nodesecurity.io/advisories/46

**Comment by elmigranto** [comment]
Could you elaborate? The only regexes I see are used for parsing `process.env` and if an attacker managed to change it, you have a bigger problem.

**Comment by jdalton** [comment]
The [recommendation](https://nodesecurity.io/advisories/46) is to upgrade to `0.7.1` or later.

**Comment by jdalton** [comment]
Which has already [been done](https://github.com/visionmedia/debug/commit/e8fe71b473632420e04a4b0c046b4a950fa002d6) so this issue can be closed.
