### ISSUE TITLE
add DEBUG_TIMESTAMP to decouple timestamps and colors when using DEBUG_COLORS

### ISSUE THREAD

**Issue by kilianc** [visionmedia/debug#295]
The only way I have to turn off timestamps ATM is to enable colors with `DEBUG_COLORS=1`. It would be nice to be able to turn off timestamps without turning the colors on.

My use case is a containerized environment where the logging timestamp is handled by whom spawns the containers.

**Comment by thebigredgeek** [comment]
Check out middleware V3 discussion here:

https://github.com/visionmedia/debug/issues/370

In the mean time I will gladly review a PR
