### ISSUE TITLE
set DEBUG=*,-not_this

### ISSUE THREAD

**Issue by BruceHem** [visionmedia/debug#300]
What does -not_this do?

**Comment by dvlsg** [comment]
It's a negation. So any `debug` method which has the `'not_this'` namespace will not be used. 

```js
const hen = require('debug')('hen');
const cow = require('debug')('cow');
const duck = require('debug')('duck');
hen('Cluck!');
cow('Moo!');
duck('Quack!');
```

Then assuming `DEBUG=*,-duck`, you would see similar to the following output:

```
hen Cluck! +0ms
cow Moo! +3ms
```

You can use more than one, as well, ie - `DEBUG=*,-duck,-hen`. It's useful when you want to include everything *except* a few of your debug namespaces, and you don't feel like typing the rest of them all out.

**Comment by BruceHem** [comment]
@dvlsg hahaha, just that i get now, thanks
