### ISSUE TITLE
%o is not documented in Readme.md

### ISSUE THREAD

**Issue by rafis** [visionmedia/debug#302]
'%o' is not documented. Or even better would be to not to pass arguments to `util.inspect` directly, but pass them through own formatter depending on type of argument, if it is an Object or Array then format using `formatter.o`:

```
debug('myObj=', myObj); // doesn't work because '%o' is not documented
debug('myObj=%o', myObj); // works because '%o' is now documented and people knows about it
```

**Comment by thebigredgeek** [comment]
@rafis would you like to create a PR for this?

**Comment by thebigredgeek** [comment]
Docs should be added [here](https://github.com/visionmedia/debug/pull/322)
