### ISSUE TITLE
`debug/browser` throws when used in electron preload scripts

### ISSUE THREAD

**Issue by Pupix** [visionmedia/debug#303]
As the title says, when logging, the `debug/browser` file checks [here](https://github.com/visionmedia/debug/blob/master/browser.js#L42) for `WebkitAppearance` in `document.documentElement.style`  , but at that time in the page's lifecycle `documentElement` is not yet defined and I get this
`TypeError: Cannot read property 'style' of null`.

Guess there could be a check for chromium based apps, where if both `document` and `process` exist, you are good to go.

Cheers,
Pupix

**Comment by thebigredgeek** [comment]
I believe this was fixed [here](https://github.com/visionmedia/debug/pull/324).  Closing
