### ISSUE TITLE
Use +NNNms instead of Date for non TTY

### ISSUE THREAD

**Issue by acorbel** [visionmedia/debug#306]
Hi,

I'm using this lib to debug my app (on AWS Lambda) and I need to check its performance for each step within a Lambda function. The function's execution time is about 500ms so the Date info is no more relevant. 

Do you know how to tail the "+NNNms" instead of the Date when stdout is not a TTY?

Thanks.

**Comment by thebigredgeek** [comment]
Discussion above for V3
