### ISSUE TITLE
Can I use this module on a cloud storage service like Azure?

### ISSUE THREAD

**Issue by slidenerd** [visionmedia/debug#308]
First of all, thanks for the brilliant effort. I was wondering how can I set the PATH on a cloud setup such as Azure.  Thanks for your answer in advance

**Comment by TooTallNate** [comment]
I'm not entirely sure what you mean by PATH. I think you mean environment variables, and if so, then _yes_ should be the answer to your question, however it might be a provider specific way to set those variables so you might want to consult google on how to do that (here's the first one http://stackoverflow.com/questions/34608769/how-and-where-to-define-an-environment-variable-on-azure).
