### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by wzup** [visionmedia/debug#309]
How do I enable colors in console? I do not have any colors in output.

My settings.

```
var debug = require('debug')('app:www');
debug('Listening on ' + port);
```

`Nodemon` config:

```
    "env": {
        "NODE_ENV": "development",
        "DEBUG": "app:*"
    },
```

Now I run `nodemon`:

```
$ nodemon
```

Output. No colors. How to enable?

![mingw64__ 2016-10-02 20 07 06](https://cloud.githubusercontent.com/assets/3880497/19020464/07ad3410-88dc-11e6-80c5-3f5f6ddb6b9e.png)

And your picture:

![image](https://cloud.githubusercontent.com/assets/3880497/19020366/de47c94e-88d8-11e6-93b1-597286038098.png)

**Comment by FredyC** [comment]
`DEBUG_COLORS=1` as env variable

**Comment by ptim** [comment]
are you not in a TTY, perchance?

>When stdout is not a TTY, Date#toUTCString() is used, making it more useful for logging the debug information as shown below:

**Comment by TooTallNate** [comment]
What operating system? What terminal emulator?

**Comment by thebigredgeek** [comment]
Closing this for now.  Will open back up if @wzup provides more info.
