### ISSUE TITLE
Client side?

### ISSUE THREAD

**Issue by wzup** [visionmedia/debug#310]
Can the plugin operate client side? For now I see it doesn't work.

My client side code:
```
const debug = require('debug')('app:foo');

function bar() {
    debug('function called');  // this doesn't output anything in Chrome console
}

bar()
```

**Comment by FredyC** [comment]
You need to enable it ... `localStorage.setItem('debug', '*')`

**Comment by TooTallNate** [comment]
^ And then refresh the page.
