### ISSUE TITLE
No output on macOS Sierra

### ISSUE THREAD

**Issue by kujiraOo** [visionmedia/debug#311]
Apparently after update to macOS Sierra there is no output in the console anymore. 

```
var debug = require('debug')('index');
debug('should print smth');
console.log(debug);
```
```
$ DEBUG=index
$ node index.js
{ [Function: disabled] enabled: false, namespace: 'index' }
$ 
```

**Comment by kujiraOo** [comment]
Worked with 

`export DEBUG=index`

**Comment by TooTallNate** [comment]
Not really much we can do about that unfortunately. We just read the env variable straight from `process.env`.
