### ISSUE TITLE
New maintainers?

### ISSUE THREAD

**Issue by paulirish** [visionmedia/debug#313]
It looks like this repo has fallen behind a little bit. 

Today I was coming to the repo because web worker support is broken and it looks like there are _three_ open PRs that can fix it. The [oldest PR](https://github.com/visionmedia/debug/pull/139) for it has been open for over two years.

@TooTallNate are you interested in adding some new maintainers to the project?

**Comment by TooTallNate** [comment]
> @TooTallNate are you interested in adding some new maintainers to the project?

Definitely 👍

**Comment by paulirish** [comment]
Nice. In that case, is anyone reading this interested?

**Comment by thebigredgeek** [comment]
I am also down.  Lemme know how I can help @TooTallNate

**Comment by jetzhliu** [comment]
wonderful

**Comment by TooTallNate** [comment]
@thebigredgeek added you as a collaborator

**Comment by thebigredgeek** [comment]
Thanks!

**Comment by paulirish** [comment]
@thebigredgeek can i just say... you have been DOMINATING as a maintainer here! Just seriously awesome. Thank you!

**Comment by thebigredgeek** [comment]
Haha yeah except for the random 5 alarm fire drills haha.  Thanks though @paulirish :p
