### ISSUE TITLE
Format to print an object at infinite depth?

### ISSUE THREAD

**Issue by olalonde** [visionmedia/debug#316]
Is there a format that will print a given object without keys being equal `[Object]` (e.g. that doesn't care about depth?). I tried `debug('%o', obj)` but that only will print up to a certain depth.

**Comment by joniba** [comment]
IMO [327](https://github.com/visionmedia/debug/pull/327) doesn't resolve this issue. What if I want to manage inspection depth for a specific debug log or namespace? Environment variables will change formatting for all logs in all namespaces.

**Comment by Qix-** [comment]
@joniba That's such an edge case I'd worry about polluting the API. This should be achievable with a custom logger though. Feel free to chime in on #582 about this 😄
