### ISSUE TITLE
Refactor to ES6 with minimal transpilation

### ISSUE THREAD

**Issue by thebigredgeek** [visionmedia/debug#319]
Familiar syntax for easier contributions

**Comment by thebigredgeek** [comment]
@TooTallNate  not too sure about whether this is worth pursuing, but my gut tells me that a more up-to-date syntax might make contributions easier.  However, this could definitely be at the expense of consumability, which we might not want to sacrifice.

**Comment by TooTallNate** [comment]
Definitely +1, but runtime-free (like `async-to-gen`) would be ideal.

**Comment by jdalton** [comment]
Might dig [babel-preset-env](https://github.com/babel/babel-preset-env).

**Comment by thebigredgeek** [comment]
@jdalton does babel force a runtime?  I know the transpiled code looks somewhat gnarly?

Thoughts @TooTallNate ?

**Comment by jdalton** [comment]
> does babel force a runtime?
It generates some helpers for this and that but they're private (not leaked).
