### ISSUE TITLE
Organized schema for CHANGELOG.md

### ISSUE THREAD

**Issue by thebigredgeek** [visionmedia/debug#320]
@TooTallNate @DevSide 

Thinking we should probably do a better job organizing changelog.  I'm gonna take a stab at it for 2.3.0, which I am about to release.  I'll link the changelog here so we can discuss it

**Comment by TooTallNate** [comment]
Agreed that a more curated changelog then simply auto-generated from the commits since last tag is ideal. Also:

 - http://keepachangelog.com/en/0.3.0/
 - http://blog.clojurewerkz.org/blog/2013/09/07/how-to-write-a-useful-change-log/

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/blob/master/CHANGELOG.md < I grouped by category but we should probably go a bit beyond that
