### ISSUE TITLE
feature: make it possible to set the global DEBUG rule in runtime

### ISSUE THREAD

**Issue by fogine** [visionmedia/debug#326]
Currently, once a debug function is exported from the debug module eg.:

```javascript
var debug = require('debug')('worker');
```

It's not possible to globally change enabled/disabled state of the debug function.

This'd come handy when you want to change the debug setup at runtime.
In other words, if a node process is established with disabled debug, I'd like to have an option to set the global DEBUG rule and enable some debug functions without restarting the node process.

**Comment by thebigredgeek** [comment]
@fogine we have an open PR linked above.  Feel free to jump into the conversation :)
