### ISSUE TITLE
What names are available?

### ISSUE THREAD

**Issue by ackmanx** [visionmedia/debug#329]
I only get output with the word Chinese in the name, followed by a colon. I don't see anywhere in usage that explains why this would be.

Usage shows...
`var debug = require('debug')('http')`
`var debug = require('debug')('worker');`
`var error = debug('app:error');`

Logs correctly for me...
`const debug = require('debug')('Chinese:www')`
`const debug = require('debug')('Chinese:foo')`

No logs at all...
`const debug = require('debug')('Foo:www')`
`const debug = require('debug')('Foo')`

**Comment by thebigredgeek** [comment]
Interesting.  This might be a bug.  Care to submit a PR @ackmanx ?

Thoughts @TooTallNate ?

**Comment by monolithed** [comment]
```js
process.env.DEBUG = 'name:*';

let debug = require('debug')('name:cache');

debug('test');
```

That's my workaround and I cannot confirm these problems.

**Comment by TooTallNate** [comment]
I don't get it. You have 2 `const debug`s? Are these in different files?

**Comment by thebigredgeek** [comment]
@TooTallNate I assumed that was a typo.  @monolithed did you mean to declare the same variable names twice?

**Comment by ackmanx** [comment]
@monolithed Your code works. It is the `process.env.DEBUG` being set. After digging around for that I found DEBUG was being set to `Chinese:*` in my IntelliJ Run Configuration (although I never put that there).

**Comment by monolithed** [comment]
> @monolithed did you mean to declare the same variable names twice?

Nope, I does not matter, off course. I would say that there is no problem :)
