### ISSUE TITLE
Since 2.3.1/2.3.2 localStorage "debug" is removed every time (wrong Electron check)

### ISSUE THREAD

**Issue by ibc** [visionmedia/debug#330]
After upgrading my `debug` dependency from 2.3.0 to 2.3.2 nothing works again.

My index.html runs the following code **before** running any JS library:

```html
<script>
   localStorage.setItem('debug', '*');
</script>

<!-- Load JS libs now -->
```

It has worked with any previous version of the debug library. Now it doesn't and nothing it logged.

In fact, once the the JS library (which includes the  `debug` dependency) is loaded, `localStorage.getItem('debug')` returns false.

This is critical.

**Comment by ibc** [comment]
My JS app uses browserify. However I've checked that `lib/browser.js` is loaded (as it must be), so that's not the problem.

**Comment by ibc** [comment]
The issue is here, in `lib/browser.js` (I've added some console warns):

```js
function load() {
  var r;
  try {
    r = exports.storage.debug;
    console.warn('1 - r:%o', r);
  } catch(e) {}

  // If debug isn't set in LS, and we're in Electron, try to load $DEBUG
  if ('env' in (typeof process === 'undefined' ? {} : process)) {
    r = process.env.DEBUG;
    console.warn('2 - r:%o', r);
  }

  return r;
}
```

I'm using [envify](https://www.npmjs.com/package/envify) which **INDEED** declares `process` as a local variable in order to allow the JS app in the browser check `process.env` stuff. That does NOT mean that we are on Electron.

Please, fix that. If Electron checks are needed do it, but don't break other valid usages of `process`.

**Comment by jordalgo** [comment]
Any word on getting this fix into new version ?

**Comment by ibc** [comment]
Guys, this is a terrible issue for which there is already a fix in master. Please, publish a new NPM version of debug module.

**Comment by TooTallNate** [comment]
2.3.3 published
