### ISSUE TITLE
Time locale config

### ISSUE THREAD

**Issue by thebigredgeek** [visionmedia/debug#332]
Let's discuss API for time locale configuration

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/issues/306

**Comment by notgiorgi** [comment]
I made this before it makes into the next release: https://github.com/notgiorgi/node-debug-timezone

**Comment by thebigredgeek** [comment]
@notgiorgi nice.  Do you wanna write up a spec proposal and post it here?

**Comment by whtiehack** [comment]
@notgiorgi  thx for the package.  https://github.com/notgiorgi/node-debug-timezone

**Comment by lmj0011** [comment]
it still needs some work: https://github.com/notgiorgi/node-debug-timezone/issues/1
