### ISSUE TITLE
seems to incorrectly detect webpack build as node env (instead of browser)

### ISSUE THREAD

**Issue by quinn** [visionmedia/debug#336]
this code:

```
if (typeof process !== 'undefined' && process.type === 'renderer') {
  module.exports = require('./browser.js');
} else {
  module.exports = require('./node.js');
}
```

seems to choose to `module.exports = require('./node.js')` inside of a webpack build being built for the browser (even in dev mode, without using the define plugin)

**Comment by TooTallNate** [comment]
Something about your webpack config is making it not respect the `browser` field in the package.json file (similar to #328). This happens by default.

**Comment by quinn** [comment]
thanks, that helped me figure this out. I had `'/index.js'` in the list for `module.extensions` which prevented webpack from checking the package.json
