### ISSUE TITLE
LocalStorage.debug overwritten by process.env.DEBUG

### ISSUE THREAD

**Issue by nikoskleidis** [visionmedia/debug#337]
I have properly set debug in localstorage.
In load() function of _browser.js_ the value of the _debug_ item I have in my localstorage is overwritten by **process.env.DEBUG** which is **undefined** in my case. 
I believe that this statement is not working as expected:
`if ('env' in (typeof process === 'undefined' ? {} : process)) {
    r = process.env.DEBUG;
  }`
or it should be rewritten as:
`if ('env' in (typeof process === 'undefined' ? {} : process)) {
    r = process.env.DEBUG || r;
  }`

Thanks

**Comment by thebigredgeek** [comment]
@nikoskleidis can you submit a PR please?

**Comment by nikoskleidis** [comment]
I think this has been fixed in 20c37fdc169eeb42f34d22b11362f66a6a64b19e
