### ISSUE TITLE
wrong usage of chrome.storage.local

### ISSUE THREAD

**Issue by andreineculau** [visionmedia/debug#339]
debug sets the storage to `chrome.storage.local` if present, but then assumes that it can read it via `.debug`, which is incorrect.

It should be `.get('debug', cb)`

**Comment by thebigredgeek** [comment]
@andreineculau can you put in a pull request?

**Comment by Qix-** [comment]
Closing as it's stale and I haven't seen problems with it get reported lately. Please let me know if this is not the case.
