### ISSUE TITLE
More noob-friendly lead paragraph

### ISSUE THREAD

**Issue by dandv** [visionmedia/debug#340]
> With debug you simply invoke the exported function to generate your debug function, passing it a name which will determine if a noop function is returned, or a decorated console.error, so all of the console format string goodies you're used to work fine. A unique color is selected per-function for visibility.

This made me go "huh?" and I had to parse it several times to understand what's going on. Given how popular this module is, a less abrupt first paragraph would be great.

**Comment by thebigredgeek** [comment]
@dandv would you like to put in a pull request?
