### ISSUE TITLE
Document the invocation format for debug()

### ISSUE THREAD

**Issue by dandv** [visionmedia/debug#341]
New to the package. I've read the README and it's not specified how *exactly* to call `debug`. The [lead paragraph](https://github.com/visionmedia/debug/issues/340) mentions "console format string goodies" so one might be inclined to call `debug('The value of foo is ', foo, ' and that of bar is ', bar)`, but examples use `+` to concatenate strings.

Would be nice to document the exact syntax for `debug()`. Thanks :)

**Comment by thebigredgeek** [comment]
@dandv can you put in a pull request?

**Comment by yamikuronue** [comment]
Does PR #373 address this or would you like more clarification?
