### ISSUE TITLE
Prepend function name and line number to debug message

### ISSUE THREAD

**Issue by hutch120** [visionmedia/debug#343]
Hi All,

Love this project! Sorry if this has already been covered... I did take a look at the issue list and found mostly people saying not implemented, or suggesting browser related solutions. I'm working in NodeJS, and having a function name and line number on each debug message really helps development efforts.

I'm wondering what the implications of adding the following which I've just started using in a recent NodeJS project? Especially the use of arguments.callee which I've read is depreciated. Is there an alternative?

I would love to be able to turn this on as an option, rather than have to append it to every debug message as shown below.

```
const debug = require('debug')('MyApp:MyModule')
debug(__dstring + "My debug message")
```
Outputs: `MyApp:MyModule myFunction 44 My debug message`

__dstring is defined like this:

```
Object.defineProperty(global, '__dstring', {
  get: function () {
    try {
      var orig = Error.prepareStackTrace;
      Error.prepareStackTrace = function (_, stack) {
        return stack;
      };
      var err = new Error;
      Error.captureStackTrace(err, arguments.callee);
      var stack = err.stack;
      Error.prepareStackTrace = orig;
      return stack[1].getMethodName() + " " + stack[1].getLineNumber() + " ";
    } catch (err) {
      return ""
    }
  }
});
```

References:
http://stackoverflow.com/questions/11386492/accessing-line-number-in-v8-javascript-chrome-node-js

**Comment by likun7981** [comment]
how about [this](https://github.com/likun7981/debugger)

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/issues/370 < seems like a solid case for V3 middleware API :).  Feel free to jump into the conversation

**Comment by Leftium** [comment]
My [@leftium/gg](https://github.com/Leftium/gg) module automatically sets the namespace based on filename+function name. You can also customize the namespace with template variables like `$LINE` and `$FILE`. (And there is actually a feature that allows you to open your editor to the exact spot in the source file simply by clicking the ms diff!)

It used to be built on top of this debug module, but now uses an internal TS port of debug with some minor modifications (moved ms diff to beginning of output; also ported/passes all relevant debug tests!)

There are two ways this was achieved:
- **Currently:** At *build-time* an optional Vite plugin rewrites calls to gg() with the meta info (expression, function name, filename, line number, column number, etc...)
- **Previously:** At runtime the call stack was parsed for the meta info.

**Live demo:** https://gg.leftium.com/?gg

**Screenshot:** (The GG dev console is optional, but supports richer output.)

<img width="854" height="889" alt="Image" src="https://github.com/user-attachments/assets/56b013d3-c194-46c5-b025-f2fd5dcb793b" />
