### ISSUE TITLE
Can't load debug module in browser because it requires tty

### ISSUE THREAD

**Issue by jasonburrows** [visionmedia/debug#344]
I'm trying to use the debugger in a browser, but when I try to import the module with `import * as debug from 'debug'` I get the error: `Error loading http://localhost:3000/tty as "tty" from http://localhost:3000/node_modules/debug/node.js`.  This stops my app from loading (Angular2).

tty is part of node, so it isn't going to be in the browser ever.  How can you import the debug module in the browser without causing it to try to import items that cannot (from what I understand) be available in the browser?

**Comment by TooTallNate** [comment]
What module loader are you using? Webpack, or ?

**Comment by jasonburrows** [comment]
Right - SystemJS.  

I've aded `'debug':'npm:debug'` to my map section and:
        'debug': {
            main: './index.js',
            defaultExtension: 'js'
      }

to my packages section.

**Comment by TooTallNate** [comment]
well you want your main to be `./browser.js`

**Comment by TooTallNate** [comment]
Note the [`browser` field in the package.json file](https://github.com/visionmedia/debug/blob/3ad8df75614cd4306709ad73519fd579971fb8d9/package.json#L28), which browserify, webpack, and probably other module loaders respect by default.

**Comment by jasonburrows** [comment]
If I omit `main:` from the packages section for `debug` (or remove the section for `debug` from there) I get a 404 on `/node_modules/debug/`.  If I change it to `      'debug': {
        main: './browser.js',
        defaultExtension: 'js'
      }`

I get `Error loading http://localhost:3000/ms as "ms" from http://localhost:3000/node_modules/debug/debug.js`.  

...so then I added a map and package entry for `ms` and it works. ...but, at least for me, SystemJS isn't using `browser.js` by default.  That likely has nothing to do with you though so thanks for your help!
