### ISSUE TITLE
spell mistake

### ISSUE THREAD

**Issue by githoniel** [visionmedia/debug#360]
i install this package from NPM ,this is my dependency
```
 "dependencies": {
    "babel-core": "^6.14.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-transform-runtime": "^6.12.0",
    "babel-preset-es2015": "^6.14.0",
    "babel-runtime": "^6.11.6",
    "co": "^4.6.0",
    "debug": "^2.2.0",
    ....
```

when run my project i get error 'namespae is not defined'
then I found that 
Line 126 in debug.js
```js
  debug.color = selectColor(namespae);
```

should be 

```js
  debug.color = selectColor(namespace);
```

**Comment by zoltan-nz** [comment]
already fixed here: https://github.com/visionmedia/debug/issues/347

**Comment by githoniel** [comment]
@zoltan-nz  it seem i'm late , thank you~~~

**Comment by zoltan-nz** [comment]
@githoniel those guys were so quick! this little glitch shows how awesome is the open source community. :) brilliant team!
