### ISSUE TITLE
Typo in debug.js

### ISSUE THREAD

**Issue by HarshBhatia** [visionmedia/debug#361]
`
  debug.namespace = namespace; 
  debug.enabled = exports.enabled(namespace);
  debug.useColors = exports.useColors();
  debug.color = selectColor(namespae);
`

Typo at debug.js:126  "namespae"

**Comment by Isanderthul** [comment]
Please read other comments and issues before filing duplicates.

**Comment by Isanderthul** [comment]
https://github.com/visionmedia/debug/issues/347

**Comment by zoltan-nz** [comment]
Keep it open, so everybody can read that this typo is already fixed and new 2.4.1 version is released...

**Comment by Waize** [comment]
our npm has problems to fetch the version 2.4.1 
do you have any experiences how long we should wait?

**Comment by thebigredgeek** [comment]
@Waize it shouldn't take too long.  Just give it a bit of time.  NPM can be sluggish from time to time
