### ISSUE TITLE
 t.useColors is not a function

### ISSUE THREAD

**Issue by akvanhar** [visionmedia/debug#369]
Your most recent update seems to have broken our build.

It is throwing the following error:
`Uncaught TypeError: t.useColors is not a function`

**Comment by thebigredgeek** [comment]
@akvanhar can you be more specific?  What input causes this error?  Would love to slap in a test case and fix this for you

**Comment by akvanhar** [comment]
Sadly, I can't provide you with any more details, as we don't use debug directly in our code, but this seems to be arising out of babel-core.

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/pull/368

**Comment by akvanhar** [comment]
Yes. This looks to be the same issue.

**Comment by thebigredgeek** [comment]
Should be fixed

**Comment by mmazzarolo** [comment]
@thebigredgeek fixed?
