### ISSUE TITLE
`useColor` bug

### ISSUE THREAD

**Issue by dickeylth** [visionmedia/debug#371]
https://github.com/visionmedia/debug/blob/master/debug.js#L119

which may throw

```
Uncaught TypeError: exports.useColors is not a function
    at createDebug (debug.js:119)
    at Object.<anonymous> (url.js:7)
    at Object.<anonymous> (url.js:47)
    at __webpack_require__ (bootstrap 6dcc159…:583)
    at fn (bootstrap 6dcc159…:107)
    at Object.<anonymous> (websocket.js:4)
    at Object.<anonymous> (websocket.js:98)
    at __webpack_require__ (bootstrap 6dcc159…:583)
    at fn (bootstrap 6dcc159…:107)
    at Object.<anonymous> (transport-list.js:5)
```

https://github.com/visionmedia/debug/commit/e58d54b46f6b446afd5262d67faea2308e952908#diff-9fd8b683aa0fd2f9b1cb7245c42c96efR125

I think that any pr submitted to this module should trigger automatic unit test run before merged in case of potential error.

**Comment by cbfx** [comment]
i shimmed the `exports.useColors` function locally and also had an error thrown complaining that `exports.colors` was not an array. when both of those were supplied, the package built without errors. going to lock down a previous version until this is resolved.

```js
exports.colors = [];
exports.useColors = function() {
  return true;
};
```

**Comment by TooTallNate** [comment]
You guys are doing something... wrong. How are you consuming debug? `useColors` comes from either the `node.js` file or the `browser.js` file, which should be your main entry points, depending on environment.

**Comment by thebigredgeek** [comment]
Yeah this is definitely user error.  You guys should be importing debug as per the docs, not through random chosen files.  Closing this

**Comment by dickeylth** [comment]
After debugging for serveral hours I finally figured out what's wrong here, I used webpack and configured:

```
{
  plugins: [
    new webpack.ResolverPlugin([
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin(".bower.json", ["main"]),
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
    ])
  ]
}
```

and when building the [`bower.json` of `debug`](https://github.com/visionmedia/debug/blob/master/bower.json#L3) takes precedence over package.json, but the `debug`'s `bower.json`'s `main` field point to `./debug.js`, and that's why the webpack using `debug/debug.js` directly when resolve `debug` module.

Maybe it should be fixed in `bower.json` and change it to `./browser.js`?

**Comment by dickeylth** [comment]
ref: https://github.com/webpack/webpack/issues/1042

**Comment by dickeylth** [comment]
https://github.com/webpack/webpack/issues/1042

**Comment by mmazzarolo** [comment]
@dickeylth, how did you fix it?  
I'm having your same issue `Uncaught TypeError: exports.useColors is not a function` since 3 days ago :(

**Comment by dickeylth** [comment]
@mmazzarolo I changed my webpack config from:

```
{
  plugins: [
    new webpack.ResolverPlugin([
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin(".bower.json", ["main"]),
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
    ])
  ]
}
```

to

```
{
  plugins: [
    new webpack.ResolverPlugin([
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("package.json", ["browser", "main"]),
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin(".bower.json", ["main"]),
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
    ])
  ]
}
```

and everything worked again.

**Comment by mmazzarolo** [comment]
@dickeylth You're a life saver. Thanks, adding `"browser"` did the trick.

**Comment by dickeylth** [comment]
https://github.com/visionmedia/debug/issues/384
