### ISSUE TITLE
updating dist/

### ISSUE THREAD

**Issue by freewil** [visionmedia/debug#372]
I noticed `dist/` isn't being updated on each release. 

I see at least 2 options:
* Add a release script (could be extremely small 1-liner possibly) to update it, before each package.json bump and tag

* Remove it from repo, have it built/published via travis

**Comment by TooTallNate** [comment]
I'd prefer to just remove it personally. Who's using the dist file currently and for what?

**Comment by TooTallNate** [comment]
And if it's for `<script>` tag usage, I'd recommend using the browserify CDN instead: https://wzrd.in/standalone/debug@latest

**Comment by freewil** [comment]
I noticed it was there, so I decided to use it for browser usage. But I agree, we should add/list alternative places to install from for browser to README and delete dist/.

I can open a PR to do this later today.

Cool - didn't know about browserify CDN.

**Comment by thebigredgeek** [comment]
@freewil yah if you open a PR today I will gladly merge it. Thanks man
