### ISSUE TITLE
Add `.babelrc` (and similar) to `.npmignore`

### ISSUE THREAD

**Issue by yofreke** [visionmedia/debug#381]
I suddenly started getting build errors on the new version of debug.  It's likely because `babel-loader` is seeing the `.babelrc` in `node_modules/debug`, which is then for some reason causing issues (because it cannot find presets relative to that babelrc).

While I plan on working around this using config, I do still have the question: Do these config files describing source structure belong in the npm package?

**Comment by escwald** [comment]
I had this issue as well, but it was "fixed" when I upgraded my npm with 
`npm install npm@latest -g`

I have also added a pull request (#383) that should hide the .babelrc, but still make it work with the tests that use it.

**Comment by yamikuronue** [comment]
My PR will fix this by removing Babel entirely.

**Comment by yofreke** [comment]
Ty all
