### ISSUE TITLE
exports.useColors is not a function

### ISSUE THREAD

**Issue by DaveGee** [visionmedia/debug#384]
Everything was working fine Friday. Had to reinstall fresh all my npm packages this morning, and I got this error in my webpack-dev-server

As I didn't change anything to my package.json (and I'm not using directly `debug`) I suspect an update in the last days broke things.
The only package I have using the most recent `debug` version is `babel-core@6.17.0` (-> `debug@2.4.5`)

My `webpack@1.13.2` and `webpack-dev-server@1.16.2` use `debug@2.2.0`

I have no idea how to solve this issue right now, so if someone has clues I'd be happy to help

![image](https://cloud.githubusercontent.com/assets/1523011/21308355/e1ce3344-c5d9-11e6-8e6c-e0076b8ca2e8.png)

Extract of debug.js causing the problem :

![image](https://cloud.githubusercontent.com/assets/1523011/21308556/bdbccd52-c5da-11e6-8997-b3eab8395892.png)

**Comment by DaveGee** [comment]
For now I had to `npm shrinkwrap` and fix the version number of `debug` to `2.3.0` for my build to work again.
There was also `superagent`, `eslint` and other packages that were using `debug > 2.2.0`

**Comment by thebigredgeek** [comment]
Interesting.  Will look into this tonight.  We need more test coverage if anyone is willing to put in PRs

**Comment by thebigredgeek** [comment]
To be clear, we had around 40 outstanding pull requests, and even more issues.  The last couple of weeks I've been trying to "unstagnate" the project a bit, but the lack of test coverage has proven to be brutal.

**Comment by dickeylth** [comment]
https://github.com/visionmedia/debug/issues/371

**Comment by dickeylth** [comment]
https://github.com/visionmedia/debug/issues/371#issuecomment-267526469

**Comment by thebigredgeek** [comment]
^if that is the solution, I am wondering how you imported debug?

**Comment by DaveGee** [comment]
I am not using debug directly. it's a dependency of packages I use (babel, eslint, superagent, and probably others)
As I have no control on this packages' own `packages.json`, "shrinkwrapping" is the only "solution" I found to workaround the issue

**Comment by thebigredgeek** [comment]
It looks like `bower.json` was referencing the wrong file.  Wondering if you had this installed via bower @DaveGee ?

**Comment by DaveGee** [comment]
I do not use bower. I have **not** installed or referenced `debug` in my project, neither using bower, neither using npm. debug is a **dependency** of packages I use (I can provide you the list, or even my package.json)
So when I build my application with webpack, `debug` ends up in my code because of npm's dependency hell somehow

**Comment by dickeylth** [comment]
@DaveGee see my link above: https://github.com/visionmedia/debug/issues/371#issuecomment-267526469

**Comment by dickeylth** [comment]
@DaveGee Maybe it's relevant with your webpack configuration

**Comment by willdawsonme** [comment]
@DaveGee If you have the following line in your webpack config, `bower.json` needs to be changed to `.bower.json`.

```new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])```

Otherwise, updating to the latest version of debug should fix the issue. The bower.json entrypoint was pointing to `debug.js`, which when installed with npm was the wrong file. In the new version, bower.json correctly points to `src/browser.js`.

**Comment by DaveGee** [comment]
This is insane. Adding the lines about bower.json in the config of webpack solves the issue apparently, although I repeat : **I do not use `bower`, and have no `bower.json`, nor `.bower.json` file anywhere in my own code**

So I must add a config line about a tool I don't use for my code to work. Anyone has an explanation about this ? 

Thanks for your help

I'll look more into this, as I won't let my config files get messy with unrelated stuff. I think I prefer the `shrinkwrap` way

**Comment by willdawsonme** [comment]
It was a suggestion if you had that line in your webpack config. There are other possibilities and I could help you troubleshoot, but the easiest solution is to try 2.5.1 which was released today.

**Comment by DaveGee** [comment]
No problem. I'll try to update my modules today and keep you updated. Thanks

**Comment by DaveGee** [comment]
Apparently the new release (2.5.1) solves the issue!
Thanks!

**Comment by TooTallNate** [comment]
@DaveGee For posterity, I'm curious as to what your `webpack.config.js` file looks like.

**Comment by fab1an** [comment]
I have a similar problem: https://github.com/tachyons-css/react-native-style-tachyons/issues/26
