### ISSUE TITLE
Proposal: remove DEBUG_FD

### ISSUE THREAD

**Issue by TooTallNate** [visionmedia/debug#386]
I implemented it a while ago, but personally have never needed to use it. Does anybody else use it?

Removing support for `DEBUG_FD` seems like it would be the simplest way to fix #280, since that's the only place where `SyncWriteStream` is used.

**Comment by thebigredgeek** [comment]
I think that's fine.  Doesn't really seem like this many configuration opens should be provided anyway.  The API should be simple while also extensible

**Comment by TooTallNate** [comment]
There is this part in the README: 

>   __Note:__ Certain IDEs (such as WebStorm) don't support colors on stderr. In these cases you must set `DEBUG_COLORS` to `1` and additionally change `DEBUG_FD` to `1`.

But seems like more of a WebStorm issue IMO.

**Comment by thebigredgeek** [comment]
Yeah agreed.  And in this case I am not sure how many of our users actually use webstorm.  Wish there were metrics haha

**Comment by thebigredgeek** [comment]
We should probably move this [here](https://github.com/visionmedia/debug/issues/370)

**Comment by TooTallNate** [comment]
Removal should go into v3, and we should have a deprecation warning in a v2 release to let anyone potentially using the env var to stop or speak up.

**Comment by thebigredgeek** [comment]
@TooTallNate you wanna add the warning?  Creating a v3 branch now
