### ISSUE TITLE
2.5.0 incompatible with babel-core

### ISSUE THREAD

**Issue by mking-clari** [visionmedia/debug#389]
`babel-core` [directly imports `debug/node`](https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/logger.js). However, this export was removed in 2.5.0.

You can reproduce the issue with [this repo](https://github.com/mking-clari/debug-babel). The following error is shown:
```
ERROR in Cannot find module 'debug/node'
```

**Comment by maxzhang** [comment]
please fix it imimmediately.

**Comment by maxzhang** [comment]
update version to 3.x ?

**Comment by thebigredgeek** [comment]
Just pushed 2.5.1.  However, babel-core shouldn't be consuming node directly.  That was the point of the `index.js` in previous versions.  Will file an issue there

**Comment by thebigredgeek** [comment]
Can you confirm https://github.com/visionmedia/debug/blob/master/node.js

**Comment by thebigredgeek** [comment]
@mking-clari @maxzhang

**Comment by azu** [comment]
It seem work fine. Thanks.

**Comment by Lellansin** [comment]
![I don't know](http://starecat.com/content/wp-content/uploads/my-code-doesnt-work-i-have-no-idea-why-my-code-works.jpg)

**Comment by yejiayu** [comment]
babel-core use debug **^2.1.1**.......

**Comment by thebigredgeek** [comment]
Well that was fun.  I submitted an issue over there.  Not sure why the folks at babel were referencing internal src files haha

**Comment by ljharb** [comment]
Everything that's reachable is part of the public API, documented or not. Thanks for the quick fix!

**Comment by thebigredgeek** [comment]
@ljharb no problem, but I don't agree that every single source file is part of the "public API".  If that is the case, then there is no private API in any codebase.  The point of the index file was to delegate between node and browser

**Comment by ljharb** [comment]
Indeed, that's accurate - unless you only distribute bundle files (one for each entry point you want to preserve) or use closure encapsulation, there's no private APIs in any codebase. It's a reasonable compromise, however, to only consider all top-level entry points automatically public, and to treat nested entry points as public only when documented.

**Comment by thebigredgeek** [comment]
That makes sense, but I think in this case the problem was a bit simpler than that.  See [this](https://github.com/babel/babel/blob/de975b9660014a4533c90190b297352495636530/CHANGELOG-6to5.md#3015)

**Comment by jesstelford** [comment]
@thebigredgeek Exceptional work on the really fast fix and publish - thank you for dedicating your time and efforts to the project that we all rely on 👍

**Comment by gurkerl83** [comment]
Hi,
I experienced the same thing with debug/browser. It was working up until the code was moved to the src directory - so it was working with version 2.4.5 - in 2.5.0 it is broken. Please add a file called browser.js in the main directory with the content 

module.exports = require('./src/browser');

Thanks!

**Comment by ljharb** [comment]
@gurkerl83 try v2.5.1
