### ISSUE TITLE
Basic support for progress indicators

### ISSUE THREAD

**Issue by medikoo** [visionmedia/debug#392]
I have a use case for logs that show progress of long-going resolution of some _synchronous_ tasks.

It may expose as:

![screen shot 2016-12-21 at 09 38 07](https://cloud.githubusercontent.com/assets/122434/21382476/3fe44dfa-c761-11e6-8b38-728a8be01f65.png)

The API could be as:

```javascript
var debug = require('debug')('foo');

debug.open('setup-x');
..
debug.progress();
..
debug.progress();
..
debug.progress('|');
..
debug.progress();
..
debug.close();
```

Above will result with something as:

```
foo setup-x ..|. 24s
```

I think support shouldn't go beyond that (e.g. involve control characters that introduce deletion etc.) and functionality should be intended purely for eventual _sync_ operations which keeps process stuck for noticeable moments.

At some point I even created a [debug extension](https://github.com/medikoo/debug-ext#debug-ext) that provides such functionality.

Is there a chance to have something like this considered for [v3.0](https://github.com/visionmedia/debug/issues/370), I think it may not be possible to achieve easily with proposed middlewares functionality.

**Comment by thebigredgeek** [comment]
Hmm, why not use [node-progress](https://github.com/visionmedia/node-progress)?

**Comment by medikoo** [comment]
@thebigredgeek I'll consider node-progress, thanks for suggestion, it indeed may suit better this case
