### ISSUE TITLE
Wrong JSPM install

### ISSUE THREAD

**Issue by PavelPZ** [visionmedia/debug#394]
After installing 
```jspm install npm:debug```
then coresponding ```jspm_packages\npm\debug@2.5.1.json``` contains
```
{
  "main": "browser.js",
  "format": "cjs",
...
```
instead of
```
{
  "main": "src/browser.js",
  "format": "cjs",
...
```

This yields to runtime error:
```
Error: XHR error (404 Not Found) loading http://.../jspm_packages/npm/debug@2.5.1/browser.js
```
(correct browser.js file is ```http://.../jspm_packages/npm/debug@2.5.1/src/browser.js```)

Is it JSPM or DEBUG issue? I am using JSPM 0.17.0-beta.32.

**Comment by thebigredgeek** [comment]
Hmm interesting.  I think this is probably related to JSPM.
