### ISSUE TITLE
[RFC] Formal schema/process for CHANGELOG and release docs

### ISSUE THREAD

**Issue by thebigredgeek** [visionmedia/debug#400]
discuss!

**Comment by TooTallNate** [comment]
Lately at work we've been using GitHub Releases instead of a changelog file. We released a new tool to help: https://github.com/zeit/release. I'm biased obviously but we should give it a shot!

**Comment by Qix-** [comment]
Agreed - changelogs are artifacts of git histories and releases are much better suited for this.

Can this issue be closed? It's quite old.

**Comment by Qix-** [comment]
Yes, it can. :)
