### ISSUE TITLE
[RFC] Test automated coverage across environments

### ISSUE THREAD

**Issue by thebigredgeek** [visionmedia/debug#403]
@yamikuronue curious to hear your thoughts here

**Comment by yamikuronue** [comment]
How do you mean "environment" here? There's two factors here: one, your coverage, and two, your test environment matrix.

**Comment by thebigredgeek** [comment]
environment meaning web worker, various browsers, node, electron, etc

**Comment by yamikuronue** [comment]
The coverage is going to be the same across all environments as long as you run the same tests. What you want is to draw up a matrix of what you support, and make sure the tests are run in all of them. You may want a service like Sauce Labs or Browserstack to be involved here.

**Comment by thebigredgeek** [comment]
Oh I see the confusion.  Yeah I shouldn't have put the word "coverage" in the issue name haha.  Whoops

**Comment by yamikuronue** [comment]
No worries, now I've got a handle on what you wanted :D 

I don't know much about web workers I'm afraid; my expertise is firmly toward back-end. Karma should be able to test cross-browser, but I don't know which binaries Travis has available, we'll want to look into that one. 

This post talks about how to test an electron app, looks like we'll need another test target: http://rhysd.hatenablog.com/entry/2015/08/07/181418 

I'm quite optimistic about this one :)

**Comment by Qix-** [comment]
Any movement here or is this out of date? cc @thebigredgeek @yamikuronue

**Comment by Qix-** [comment]
I'm concluding this is well out of date at this point.
