### ISSUE TITLE
Allow enable programmatically

### ISSUE THREAD

**Issue by dtomasi** [visionmedia/debug#416]
It would be nice to enable debug in browsers programmatically.

I would prefer something like that:
```
const debug = require('debug').enable('MyRootNamespace:MyServices:*');

// or for multiple namespaces
const debug = require('debug').enable(
   [
      'MyRootNamespace:MyServices:*',
      'MyRootNamespace:MyDataSources:*'
   ]
);
```
The solution to use localStorge does not work in Safari´s private mode anyway. Would be nice to have also the debug messages there ... 

Also it would be nice to have the ability to deny enabling debug by setting localStorage.debug. The source code of my current project is only provided in a uglified version to protect my intellectual property and business secret. I don´t want anyone can enable debug information by setting localStorage.debug to '*'.

**Comment by alFReD-NSH** [comment]
I think `require('debug').enable('MyRootNamespace:MyServices:*');` already works.

**Comment by vespakoen** [comment]
It also doesn't work in other runtimes that don't have localstorage (ExtendScript for example, a JS for controlling Adobe applications)

**Comment by dtomasi** [comment]
For those who can't wait, like me ;-)

I did a little change in my fork that allows to lately enable namespaces. see: https://github.com/dtomasi/debug/commit/f64af5669b2cb2184d99ac4d25cf4d216df78f2b

Within the initialization of my script I use something like that:

```js
// Get the Module not the function it exposes
var debugModule = require('debug');
// Set storage to null. This stops the use of localStorage within my bundle
debugModule.storage = null;
// Disable all
debugModule.disable();

if (myConfig.debug) {
    debugModule.enable(myConfig.debug);
}
```

Cheers

**Comment by TooTallNate** [comment]
@dtomasi We're heading towards dynamic debug instances in #440.

But tangentially related:

> The source code of my current project is only provided in a uglified version to protect my intellectual property and business secret.

This is particularly frightening! Obscurity __DOES NOT EQUAL__ security!!! If you have secret values or code then they should be secured behind server-side API calls, and _not bundled_ with client-side code.

**Comment by TooTallNate** [comment]
This now works in debug v3. Please open a new issue for any future troubles.
