### ISSUE TITLE
Colorization is broken in vscode

### ISSUE THREAD

**Issue by Stumblor** [visionmedia/debug#421]
It looks as though colorization of debug logs is only partly working in vscode - seems to output okay for the ms timings but not okay for the namespace:

![screen shot 2017-02-07 at 20 51 39](https://cloud.githubusercontent.com/assets/3416626/22710955/46d930d0-ed77-11e6-9aef-cc19b8b85909.png)

**Comment by Stumblor** [comment]
The configuration I'm using:

```
"configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/bin/www",
            "env": { 
                "DEBUG": "ss:*",
                "DEBUG_COLORS": "true"
            },
            "cwd": "${workspaceRoot}",
            "port": 3000
        }
    ]
```

**Comment by Stumblor** [comment]
I've found that removing the *;1* in the formatArgs function resolves it:

![image](https://cloud.githubusercontent.com/assets/3416626/22793368/9033ffb4-eee7-11e6-919e-73b78cd57e47.png)

I'm not au fait enough with ANSI colour codes to know the implications of this. Help greatly appreciated!

**Comment by TooTallNate** [comment]
Pretty sure the `;1` is "bold". We've had reports of issues with it in the past.

**Comment by 0x80** [comment]
@Stumblor I don't get any debug output in my VSCode console. Even though the environment variable is set correctly. Are you still getting output with the latest version?

**Comment by Stumblor** [comment]
@0x80 Yes still getting (non colored) output when using 2.6.3.

**Comment by 0x80** [comment]
@Stumblor Weird. I don't get it. Not meaning to hijack this thread but maybe you see something funny about this:

```json
{
  "version": "0.2.0",
  "configurations": [{
      "name": "Launch",
      "type": "node",
      "request": "launch",
      "protocol": "inspector",
      "program": "${workspaceRoot}/src/index.js",
      "stopOnEntry": false,
      "args": [],
      "cwd": "${workspaceRoot}",
      "preLaunchTask": null,
      "runtimeExecutable": null,
      "runtimeArgs": [
        "--nolazy",
        "--require", "babel-register"
      ],
      "env": {
        "NODE_ENV": "development",
        "DEBUG": "scrape-from-contentful"
      },
      "console": "internalConsole",
      "sourceMaps": true,
      "outFiles": []
    }
  ]
}
```

When I run this from my terminal it works fine:
`DEBUG=scrape-from-contentful node --require babel-register ./src/index.js`

This command gives the same output in the integrated terminal in vscode, but nothing when I start the debugger. I've also tried appending  :* like you have, but it makes no difference. I must be missing something.

**Comment by 0x80** [comment]
I set console to "integratedTerminal" and there things work fine for me. I like it since it's a bit less magic too. You see exactly how the commands are executed.

**Comment by tony-kerz** [comment]
i'm running vscode `1.14.1` and i don't get any output when using default of `console: internalConsole`, using `integratedTerminal` does show output, but it would be nice to have it work with the default setting of `internalConsole`

**Comment by Qix-** [comment]
This is a bug in VSCode. Please open an issue there - we use very standard output mechanisms.
