### ISSUE TITLE
check if debug running in the script?

### ISSUE THREAD

**Issue by gmarzloff** [visionmedia/debug#423]
Hi, is there a simple way to check if a script is/isn't being run in debug mode (similar to preprocessor instructions)? 

pseudocode:
```
#ifdebug 
  doThis();
#endif
```

**Comment by jcalfee** [comment]
Sometimes debug output data are expensive to create.  We need a way to test the debug pattern to see if it is enabled before trying to log it:
```javascript
const hexDebug = newDebug('myapp:hexDump')
if(hexDebug.isEnabled())
    hexDebug(b.printDebug())
```

**Comment by TooTallNate** [comment]
It's `hexDebug.enabled` in @jcalfee's example.
