### ISSUE TITLE
Redirect console.log output to debug namespace

### ISSUE THREAD

**Issue by bertolo1988** [visionmedia/debug#426]
I am maintaining an app that uses [npmlog](https://github.com/npm/npmlog) as a to organize useful information.

I wanted to standardize my app console output. I was wondering if i could, somehow, redirect the console.log output to a debug namespace.
Is this possible?

**Comment by TooTallNate** [comment]
How about something like:

```javascript
const log = require('debug')('log')
console.log = function () {
  log.apply(null, arguments)
}
```
