### ISSUE TITLE
Does debug support es6? 

### ISSUE THREAD

**Issue by ronanhancock** [visionmedia/debug#427]
hi,

I'm using debug in an application thats code happens to be in es6, im importing the module like so:

`import Debug from 'debug';`

then from there i'm doing the following: 

`
const httpDebug  = Debug('http'); 
const appDebug   = Debug('app'); 
const errorDebug = Debug('error'); 
`

then exporting them like so: 

`
export {
  httpDebug, 
  appDebug, 
  errorDebug
}
`
and im also running set DEBUG=* & my_npm_command and it still wont work, any suggestions or will i have to prepose to change the code style?

**Comment by ronanhancock** [comment]
Literally, just fixed it!

**Comment by juliocanares** [comment]
@ronanhancock  what did  u do to fix it?
