### ISSUE TITLE
Error: `from` shouldn't be larger than `to`

### ISSUE THREAD

**Issue by cggaurav** [visionmedia/debug#430]
```
/home/travis/build/project-x/auth/node_modules/debug/src/debug.js:200
  if (val instanceof Error) return val.stack || val.message;

Error: `from` shouldn't be larger than `to`
```

This happens when my integration test run for a simple node service on Travis. I am not able to figur out `value` though.

**Comment by Qix-** [comment]
This is pretty out of date and the only time I've seen this reported. Going to close - please let me know if you still have this problem.
