### ISSUE TITLE
[Feature] enable/disable debugging dynamically

### ISSUE THREAD

**Issue by geonanorch** [visionmedia/debug#433]
Often when one is investigating a 'live' issue, one would rather not restart node to enable debugging: this might make the problem disappear until it is triggered again later. Instead debug configuration should be alterable dynamically through some kind of listener (e.g. file watch, socket &ndash;the implementation of the listener is not the purpose of this issue, though that would make a nice addition!).

Support for such dynamic changes would be easy to add in `debug.js`, here the output of `diff -n` for the [current codebase](https://github.com/visionmedia/debug/commit/78ae6c94122a5c23263b6ea6def0d7ead474fc66):
```
a21 1
exports._debuggers = Object.create(null);
a126 1
  exports._debuggers[namespace] = debug;
a155 10
  for (const namespace in exports._debuggers) {
      exports._debuggers[namespace].enabled = false;
      exports.names.some( (pattern) => {
          const match = pattern.test(namespace);
          if (match) {
              exports._debuggers[namespace].enabled = true;
          }
          return match;
      });
  }
```

With above one can change the debug settings from any place in the code using the same values as passed through the `DEBUG` environment variable at initialization time:
```
const debugCore = require('debug');
debugCore.enable('mymod*');
```

See also issue #419 (and possibly #416 and #425).

**Comment by TooTallNate** [comment]
Please try out v3.0.0, which includes https://github.com/visionmedia/debug/commit/bf88540737e3908eeac253ffd2bbde0b46d5b56d.

**Comment by geonanorch** [comment]
Thanks, will do! Initial feedback in the meantime:
- unless I missed it in `README.md`, the feature is not documented
- the feature is not listed under the release notes for 3.0.0

All the same, thank you for considering and implementing my request :-)
