### ISSUE TITLE
Feature: save debug output to stream/file

### ISSUE THREAD

**Issue by jacargentina** [visionmedia/debug#434]
There is some way to easily make all the output to be saved on a given stream/file ? But! I dont want to do that on the "console way" because i would want, on my running app instance (a website) to enable/disable some configuration, and then magically i'm getting debugging info from my already-running instance.

**Comment by thebigredgeek** [comment]
This is probably best handling with something like `syslogd`, not a file.  Is there a reason you want to use a file?
