### ISSUE TITLE
Uncaught Type Error coming from browser.js

### ISSUE THREAD

**Issue by Camyll** [visionmedia/debug#436]
TypeError: Cannot read property 'style' of null  happening when document.documentElement is null because there is no null check. Would like to put in a PR to fix it if you guys decide not to.

**Comment by thebigredgeek** [comment]
Yup, feel free to submit a PR :)

**Comment by thebigredgeek** [comment]
@Camyll are you down to help us with a PR?

**Comment by Camyll** [comment]
@thebigredgeek  sure I can probably get to it by the end of the week. It's just a simple null check for document.documentElement that needs to be added. Checking if it's undefined is not enough

**Comment by thebigredgeek** [comment]
We could just check a boolean cast.  That would be the most error proof.  Seems like this kind of stuff continues to creep up

**Comment by Camyll** [comment]
@thebigredgeek yeah just let me know if you guys want to make the change, if not I can try and get to it soon. Sorry I keep forgetting

**Comment by fourpixels** [comment]
@thebigredgeek @Camyll any info on that?

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/pull/447 <- just waiting on a sanity check

**Comment by fourpixels** [comment]
Great, thanks!

**Comment by Qix-** [comment]
Looks like #447 was merged. Please let me know if it didn't solve the problem.
