### ISSUE TITLE
Using 'import' syntax has problems when using rollup for browser deployments.

### ISSUE THREAD

**Issue by jasonburrows** [visionmedia/debug#438]
When importing and using debug via an import statement such as:

```
import * as debugModule from 'debug';

let debug = debugModule('componentname');
```

Rollup gives the error: 

`Cannot call a namespace ('debugModule')`

It seems that suggested solutions for similar situations (people report this problem with moment) are to not use the '* as' syntax.  So do this:

`import debugModule from 'debug'; // (or import debug from 'debug' - neither work as there's no default export)`

or 

`import { Debug } from 'debug'; //or whatever you'd like to try to import - there are a few explicit exports to select from but none give you the function required to actually get a debugger it seems.`

The only way I've gotten it to work (or at least that I haven't yet encountered problems with) is to call it like this after the import:

```
import * as debugModule from 'debug';
let debug = debugModule.call(this, 'componentName');
```

I very well might just be missing what I should be importing from debug, but otherwise this may be a bug (at least if you intend to support browser deployments that use rollup).

**Comment by thebigredgeek** [comment]
Interesting.  This sounds like a bug with Rollup.  I haven't encountered with Webpack + Babel or just Babel by itself... both server and client side.

**Comment by jasonburrows** [comment]
I turns out this was actually a problem with @types/debug.  If I simply remove that package, the import works properly.  So this is the wrong project for the bug, I apologize - but it was not clear where the issue was coming from until I tried removing @types/debug.

**Comment by thebigredgeek** [comment]
@jasonburrows that's really strange. It sounds like rollup might be trying to import the types module as `debug` rather than the actual debug module?  I would still bet on the bug being related to Rollup :)

**Comment by StreetStrider** [comment]
I'm using Rollup and one of my dependencies use `debug`.
Current error when using debug + Rollup is:
> Non-existent export 'default' is imported from node_modules/debug/src/browser.js

Seemes to be the consequences of this dynamic shenanighans:
```js
exports = module.exports = require('./debug');
exports.init = init;
// etc..
```
This looks like a pretty style and works well in CJS bundlers, but not in static bundlers, like Rollup. It's kinda discouraging, since `debug` is not my dep, so I can't inject it directly, or use via script tag or fix it in any other quick-and-dirty way. I can't even throw it away. I'm using another module which depends on `debug` and I have very few ways to control/fix this issue.
