### ISSUE TITLE
process.env.DEBUG still ignored in Electron

### ISSUE THREAD

**Issue by blahah** [visionmedia/debug#439]
Even with `v2.6.3`, after #431 was merged, debug still ignores the `DEBUG` env var in electron. I have to manually transfer the env var to localstorage to make it work:

```js
localStorage.setItem('debug', process.env.DEBUG)
```

**Comment by thebigredgeek** [comment]
Hmm.  paging @paulcbetts, any idea here?  I would have thought #431 should have fixed this?

**Comment by blahah** [comment]
Sorry I didn't provide more info before - was racing to a deadline. I'll take a deeper look now and see if I can suggest / PR a solution

**Comment by paulcbetts** [comment]
Dunno, this works for me in v2.6.3

**Comment by blahah** [comment]
@paulcbetts yeah I think the latter may have been happening. I now can't recreate the bug. What is always happening is that whatever I set as `DEBUG=` gets auto-transferred to localStorage, but not by my code. I'll keep an eye out, but I think this can be closed for now.

Thanks all :)

**Comment by thebigredgeek** [comment]
Yay Javascript!  I wonder how often people end up running 20+ versions of debug on their server hahaha
