### ISSUE TITLE
"document is not defined" on react-native

### ISSUE THREAD

**Issue by fab1an** [visionmedia/debug#448]
This was a problem already and resurfaced: https://github.com/tachyons-css/react-native-style-tachyons/issues/41#issuecomment-297790972

#374, #286, #303

**Comment by thebigredgeek** [comment]
Was this not fixed in the hotfixed released yesterday?

**Comment by thebigredgeek** [comment]
@fab1an I am closing this because I believe it was fixed and I haven't heard back from you

**Comment by fab1an** [comment]
@thebigredgeek Thanks, I didn't check it out, but just removed the `debug` dependency from my library, because I was logging seldomly anyway and this already broke twice :(.

Thanks for your efforts, though!
