### ISSUE TITLE
Not showing different color on each log

### ISSUE THREAD

**Issue by vijaypatoliya** [visionmedia/debug#449]
In `app.js` file I define debug like below.

```js
var debug = require('debug')('Project1:app');
debug('test app.js');
```

I used window system to first define env like set `DEBUG=Project1:*`

Its showing log without different colors for each log line. Only showing all log white white color

```
debug version: "debug": "^2.6.6",
```

**Comment by Qix-** [comment]
How are you running your application?

**Comment by tomatau** [comment]
same problem.
ran npm dedupe, checked find-duplicate-dependencies and only one version of debug.

```
debug.enable(process.env.DEBUG) // *
console.log(debug.useColors()) // true
```

starting with `node server.js` and it's using a typescript register which shouldn't affect debug.

**Comment by tomatau** [comment]
installing supports-color fixed my issue, but it shouldn't be necessary and makes no sense as to why it would...?

**Comment by TooTallNate** [comment]
@tomatau without `supports-colors`, I'm curious what `debug.colors` is set to for you.

**Comment by tomatau** [comment]
Yes I checked that too, it was an array of 1 to 6 from what i remember

**Comment by TooTallNate** [comment]
Ok well I mean I think it has something to do with your setup in this case. Perhaps your terminal is configured to ignore the common ANSI colors, but the 256 color codes do work.

**Comment by tomatau** [comment]
That doesn't make sense according to my edit ^ the colours work if I specify a colour. And also it is showing colour, just always the same one.

**Comment by TooTallNate** [comment]
Ok so create a debug instance and see what `debug.color` is set to please

**Comment by tomatau** [comment]
always 4 without `supports-color`, random with it available

**Comment by TooTallNate** [comment]
And what are the namespaces? I believe things are working correctly. This issue is that you happen to have a namespace collision in the [`selectColor()` function](https://github.com/visionmedia/debug/blob/a0601e5e65ca80ce2f39b1243db332c64c124214/src/debug.js#L36-L52) because without `supports-colors` there's only 6 colors to choose from. The 256 color range is a lot less likely to create a collision.

**Comment by tomatau** [comment]
I've tried multiple namespace strings and have worked with them fine before. I'm porting a working universal app to typescript, the existing project worked fine

**Comment by TooTallNate** [comment]
Well I have nothing to go off of unless you give me some examples.

**Comment by tomatau** [comment]
```js
// file1.ts
import * as debug from 'debug'

const log = debug('first')
console.log(log.color) // 4

// file2.ts
import * as debug from 'debug'

const log = debug('second')
console.log(log.color) // 4

// file3.ts
import * as debug from 'debug'

const log = debug('third')
console.log(log.color) // 4

// file4.ts
import * as debug from 'debug'

const log = debug('lorem-ipsum-dolla-dolla')
const secondLogInFile = debug('foo')
console.log(log.color) // 4
console.log(log.color) // a random number between 1 and 6
```

**Comment by TooTallNate** [comment]
So I get:

```
$ DEBUG=* node t
6
5
1
6
6
```

With this script:

```js
const debug = require('./');

let log = debug('first')
console.log(log.color) // 4

// file2.ts

log = debug('second')
console.log(log.color) // 4

// file3.ts

log = debug('third')
console.log(log.color) // 4

// file4.ts

log = debug('lorem-ipsum-dolla-dolla')
secondLogInFile = debug('foo')
console.log(log.color) // 4
console.log(secondLogInFile.color) // a random number between 1 and 6
```

Not sure what I'm missing… 🤔

**Comment by tomatau** [comment]
Using the same file behaves differently

**Comment by TooTallNate** [comment]
Can you try with vanilla Node.js to see if it makes a difference?

**Comment by tomatau** [comment]
It works on the project fine before porting to TS. Just rebuilding a boilerplate in TS has brought up this inconsistency

**Comment by TooTallNate** [comment]
Ok well thanks for the report, but it would appear to be a TypeScript issue then. Gonna close this for now 🍻

**Comment by TooTallNate** [comment]
Also please make sure you're using the latest version of `debug`.

**Comment by Yalhu** [comment]
d1 and dlog are the same color: green. Version 3.1.0
```
var d1=debug('debug:debug1');
var d2=debug('debug:debug2');
...
var dlog=debug('debug:log');
dlog.log=console.log.bind(console);
```

**Comment by iamsagar7** [comment]
Sometime `npm start `doesn't work 

>try: `nodemon app.js`
It worked for me
