### ISSUE TITLE
Suddenly stopped working on Node.js 0.6

### ISSUE THREAD

**Issue by dougwilson** [visionmedia/debug#450]
Up to version 2.3.3 this module worked fine in Node.js 0.6, but now it no longer does. I'm not sure if this is an issue or not, because there is nothing in the docs or even package.json that indicated what versions of Node.js are actually the supported versions.

1. Is this an issue that Node.js 0.6 stopped working?
2. What are the versions of Node.js that are supported?
3. Can the version range be at least added to engines.node in package.json?

**Comment by TooTallNate** [comment]
1. We should probably fix whatever broke.
1. Virtually every node version IMO.
1. Fine by me, but perhaps kind of redundant if the goal is `"node": "*"`.

**Comment by calidion** [comment]
it is most probably a problem caused by npm, where the range versions always break packages..

**Comment by dougwilson** [comment]
Thanks for the clarification, @TooTallNate ! I'm happy to make a PR with a suggested fix, just wanted to check if you even cared about the version first before bothering :) I agree that adding `"node": "*"` would be redundant. It sounds to me like there is no official minimum version right now, rather leaving it up to the "market" to decide (by users making PRs with suggested fixes).

So the issue is just that `util._extend` doesn't exist in Node.js 0.6 (plus, it _is_ an underscore-prefixed function, so... _shrugs_). Anyway, without going through the complications of trying to introduce a dependency, The smallest portion of `_extend` was just inlined in PR #452

**Comment by dougwilson** [comment]
Looks like the PR is merged now 🎊 ping me on the next npm publish whenever you get to it 😄

**Comment by TooTallNate** [comment]
Published in 2.6.7.
