### ISSUE TITLE
Optionally disable timestamps

### ISSUE THREAD

**Issue by silverbucket** [visionmedia/debug#453]
When a node process is managed by systemd, systemd already provides timestamps in addition to the automatic prepending of timestamps by debug when not in a TTY. Therefore each line has double-timestamps.

```
Mar 19 16:29:19 dev sockethub[8187]: Sun, 19 Mar 2017 16:29:19 GMT express:router:layer new '/complete'
Mar 19 16:29:19 dev sockethub[8187]: Sun, 19 Mar 2017 16:29:19 GMT express:router:route get '/complete'
Mar 19 16:29:19 dev sockethub[8187]: Sun, 19 Mar 2017 16:29:19 GMT express:router:layer new '/'
Mar 19 16:29:19 dev sockethub[8187]: Sun, 19 Mar 2017 16:29:19 GMT express:router:route new '/delayed'
Mar 19 16:29:19 dev sockethub[8187]: Sun, 19 Mar 2017 16:29:19 GMT express:router:layer new '/delayed'
Mar 19 16:29:19 dev sockethub[8187]: Sun, 19 Mar 2017 16:29:19 GMT express:router:route get '/delayed'
Mar 19 16:29:19 dev sockethub[8187]: Sun, 19 Mar 2017 16:29:19 GMT express:router:layer new '/'
```

`DEBUG_NOTIMESTAMPS=1` or something similar would be a great feature to have.

**Comment by EirikBirkeland** [comment]
Timestamps show up in PM2 also. I am interested in toggleable, namespaced logging, not timestamps.

**Comment by amejiarosario** [comment]
This is an issue in `Heroku` as well. I have double dates in the logs 👎 
cc: @TooTallNate @EirikBirkeland

**Comment by EirikBirkeland** [comment]
I forked and changed the code, works for me :) Thanks though.

**Comment by Qix-** [comment]
Closing in favor of #582. Please move discussion there.
