### ISSUE TITLE
printing the date using Formatters doesn't work

### ISSUE THREAD

**Issue by lmj0011** [visionmedia/debug#456]
**logger.js**
```js
const moment = require('moment')
const debug = require('debug')
const log = debug('adonuxt-rp:log [ %s ]', moment().format())
const error = debug('adonuxt-rp:error [ %s ]', moment().format())
debug.log = console.info.bind(console) // https://www.npmjs.com/package/debug#output-streams

const logger = {
  log,
  error
}

module.exports = logger
module.exports.default = logger
```

I have that module imported throughout my app and is using it like so
`logger.log('Successfully created')`

**The output is not what I expect**
```
  adonuxt-rp:log [ +398ms ] Successfully created
```

Why is my date output defaulting to the millisecond output?

I'm expecting an output similiar to this:

```
adonuxt-rp:log [ 2017-05-14T04:08:26-05:00 ] Successfully created
```

**Comment by TooTallNate** [comment]
The API doesn't really work like that. The `debug()` function in your example only takes a single argument: the namespace.

**Comment by lmj0011** [comment]
What should do in order to get the date to ouput?

**Comment by Qix-** [comment]
Closing in favor of #582. Please move discussion there.
