### ISSUE TITLE
No compatible version found: debug@2.6.7

### ISSUE THREAD

**Issue by suprsidr** [visionmedia/debug#459]
Valid install targets:
npm ERR! notarget 2.6.6, 2.6.5, 2.6.4, 2.6.3, 2.6.2, 2.6.1, 2.6.0, 2.5.2, 2.5.1, 2.5.0, 2.4.5, 2.4.4, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.0, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.8.1, 0.8.0, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.0, 0.5.0, 0.4.1, 0.4.0, 0.3.0, 0.2.0, 0.1.0, 0.0.1

node v6.10.3
npm  v3.10.10

**Comment by engtomhat** [comment]
Running into the same issue when installing it as part of mocha

error node v4.5.0
error npm  v2.15.12
error version not found: debug@2.6.7

**Comment by suprsidr** [comment]
I should have mentioned debug is a dependency of connect

**Comment by jasondaihl** [comment]
I'm getting the same error, it looks like v2.6.7 was not published.

```
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: debug@2.6.7
```

**Comment by azeldis-lv** [comment]
Same build-breaking errors here as well

**Comment by thebigredgeek** [comment]
Weird!  I got an email about this early this morning as well.

https://www.npmjs.com/package/debug

^ As you can see, 2.6.7 is clearly live

![screen shot 2017-05-17 at 10 16 09 am](https://cloud.githubusercontent.com/assets/2799276/26166882/f57bb71a-3ae9-11e7-87c0-4c49ee01d456.png)

Can I get a screenshot of the `stdout` you are seeing from `npm`?

**Comment by TooTallNate** [comment]
It's definitely published: https://www.npmjs.com/package/debug

<img width="348" alt="screen shot 2017-05-17 at 10 17 26 am" src="https://cloud.githubusercontent.com/assets/71256/26166914/0f5e0c1e-3aea-11e7-9293-89b14861dc6a.png">

Seems like a weird caching issue.

**Comment by chrisrink** [comment]
I'm getting this issue as well due to a dependency in babel-core. So I image everyone is about to have this issue. Is there a way you can republish as a new version?

**Comment by thebigredgeek** [comment]
@chrisrink can you try to clean npm and yarn cache and see if that fixes it?

**Comment by thebigredgeek** [comment]
@chrisrink can you clean npm and yarn cache and see if that fixes the issue?

**Comment by chrisrink** [comment]
Actually, I was wrong. It wasn't a dependency on babel-core. It was a dependency on the devserver -> express and that probably uses connect. Removing the dependency fixes my issue but I will try to clean my npm proxies cache and see if that works too.

**Comment by chrisrink** [comment]
@thebigredgeek  - Looks like it was an issue with my proxy repo. I invalidated the cache in the repo and everything is all good. Thanks for the helpful reminder ;)

**Comment by suprsidr** [comment]
Seems to have cleared up now. Feel free to close unless other are still having issues. Thanks you :)

**Comment by azeldis-lv** [comment]
I am also using a proxy repo (working on getting the cache cleared there).  Is there a reason why everyone with a proxy repo got stuck on 2.6.6?

**Comment by thebigredgeek** [comment]
No clue.  I pinged Laurie Voss on twitter and sent a support email to npm.  I'll post what I find here

**Comment by engtomhat** [comment]
Yes. Looks like a proxy repo issue. I checked my proxy and didn't find 2.6.7.
I'll work on getting it refreshed. Thanks everyone :)
