### ISSUE TITLE
Feature Request? Ability to pass in true / false to "useColors()" to force enable/disable it?

### ISSUE THREAD

**Issue by joshuairl** [visionmedia/debug#463]
Since browser / userAgent sniffing is not universal for all devices / webviews... I think it may be useful for us to be able to programmatically disable it at runtime in the browser at least.

Just a thought, great work!

**Comment by joshuairl** [comment]
or well, ability to have another function called forceUseColors = false;
Since useColors is merely a getter in this case.

**Comment by TooTallNate** [comment]
Globally:

```js
const createDebug = require('debug')
createDebug.useColors = () => false

const debug = createDebug('foo')
debug('blah')
// no colors
```

Per debug instance:

```js
const createDebug = require('debug')

const debug = createDebug('foo')
debug.useColors = false
debug('blah')
// no colors
```

Hope that helps!
