### ISSUE TITLE
npm WARN enoent ENOENT: no such file or directory, open '<root>/node_modules/supertest/package.json' 

### ISSUE THREAD

**Issue by karbon62** [visionmedia/debug#466]
Hi,

I've got a problem here where using npm to reinstall appium has produced several errors. 

Im trying to reinstall Appium and have tried to run the following commands to fix my problem with npm; "Clean Cache" & "re-install". Unfortunately it didn't fix it for me. Seems to have spawned another issue.

/Users/Karbon62/.npm/_logs/2017-06-05T14_42_36_153Z-debug.log

Logs that were generated before cleaning cache: file:///Users/Karbon62/.npm/_logs/2017-06-05T12_47_17_209Z-debug.log

**Comment by Siton-Systems** [comment]
This is a very "unhelpful" error message. I also have this error - please give a more clear error message on this issue ("enoent ENOENT" it's like jibberish hhh). I saw a lot of stackoverflow Q about this error (again this unclear message).  

Maybe try this:
https://stackoverflow.com/questions/31952747/npm-throws-enoent-warnings-on-every-install-uninstall-ls
**Or:**
https://stackoverflow.com/questions/9484829/npm-cant-find-package-json
https://www.npmjs.com/package/npm-autoinit

Anyway, i am not NPM master. I hope someone her will give you the best answer.

**Comment by karbon62** [comment]
cheers @Siton-Systems, appreciate the help!

**Comment by Herod** [comment]
run npm init and then you should be fine

**Comment by Karla-Isabel-Sandoval** [comment]
@Herod - i'm also getting the ENOENT error message.
after running `npm init` my terminal output is 
```~ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (Hyacinth)


```

**Comment by Qix-** [comment]
This doesn't really have anything to do with the `debug` package here. `ENOENT` means `Error: No Entity`, otherwise known as "file not found". It is among the list of [`errno` codes](http://www.ioplex.com/~miallen/errcmp.html).

Not sure what the initial error message was about, but judging from the positive response to `npm init` as a 'solution' I'd guess you're seeing a _warning_ about `package.json` not being present. If so, you can either ignore it or create one yourself (`npm init` works just fine for this).

Closing since this isn't `debug` related :)

**Comment by Karla-Isabel-Sandoval** [comment]
@Qix- Thank you kindly for the awesome clarification you provided. It's greatly appreciated.

**Comment by yogeshwar143** [comment]
npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sait110/.npm/_logs/2017-11-03T13_14_34_858Z-debug.log

**Comment by yogeshwar143** [comment]
npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sait110/.npm/_logs/2017-11-03T13_14_34_858Z-debug.log

**Comment by yogeshwar143** [comment]
npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/sait110/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/sait110/package.json'
npm WARN sait110 No description
npm WARN sait110 No repository field.
npm WARN sait110 No README data
npm WARN sait110 No license field.

**Comment by yogeshwar143** [comment]
npm start
npm ERR! path /home/sait110/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/sait110/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by yogeshwar143** [comment]
bower install
bower                           ENOENT No bower.json present

**Comment by hacktivist123** [comment]
Run Npm init and create a package.json file yourself , worked like a charm for me
