### ISSUE TITLE
please release a 1.0.5 that updates ms to v2.0.0

### ISSUE THREAD

**Issue by sam-github** [visionmedia/debug#469]
debug 1.x is widely depended on still, and its getting flagged over and over for bringing in older versions of `ms` that had security vulnerabilities reported against it.

Its a false positive, but a whole lot of build chains and users of debug, directly or indirectly, would be very, *very*, appreciative if you release a 1.x update to `debug` that uses the same version of `ms` you use in master, `2.0.0`. Its API compatible with the `ms` used now for 1.x, at least for the humanize call `debug` makes (the incompatibility - and the vulnerability - is around a parse function that `debug` doesn't use).

I can't PR the change because I'd need a 1.x branch to target, but its this:

```
debug ((1.0.4) *%) % git diff
diff --git a/package.json b/package.json
index 4ee4dc5..b348b90 100644
--- a/package.json
+++ b/package.json
@@ -16,7 +16,7 @@
     "Nathan Rajlich <nathan@tootallnate.net> (http://n8.io)"
   ],
   "dependencies": {
-    "ms": "0.6.2"
+    "ms": "^2.0.0"
   },
   "devDependencies": {
     "browserify": "4.1.6",
```

**Comment by TooTallNate** [comment]
Please see v1.0.5.

**Comment by sam-github** [comment]
Thank you!
