### ISSUE TITLE
Dependecy error: Cannot find module `tty`

### ISSUE THREAD

**Issue by dalisoft** [visionmedia/debug#472]
* Execute file: `node.js`
* Module required: `tty`
* Unexcepted?: Cannot find module `tty`
* Excepted: Module `ttys` should be insteadof `tty`

**Comment by TooTallNate** [comment]
Are you running with Node.js?

`tty` is definitely a module even in the latest Node.js:

```
> process.version
'v8.2.1'

> tty
{ isatty: [Function],
  ReadStream: { [Function: ReadStream] super_: { [Function: Socket] super_: [Object] } },
  WriteStream: { [Function: WriteStream] super_: { [Function: Socket] super_: [Object] } } }
```

**Comment by Qix-** [comment]
Not to mention it's been around since version 0.7.

**Comment by dalisoft** [comment]
It is node.js but for mobile device
