### ISSUE TITLE
v2.6.8 - When `useColors === false` - date inserted

### ISSUE THREAD

**Issue by amurchick** [visionmedia/debug#474]
```
/**
 * Adds ANSI color escape codes if enabled.
 *
 * @api public
 */

function formatArgs(args) {
  var name = this.namespace;
  var useColors = this.useColors;

  if (useColors) {
    var c = this.color;
    var prefix = '  \u001b[3' + c + ';1m' + name + ' ' + '\u001b[0m';

    args[0] = prefix + args[0].split('\n').join('\n' + prefix);
    args.push('\u001b[3' + c + 'm+' + exports.humanize(this.diff) + '\u001b[0m');
  } else {
    args[0] = new Date().toUTCString()
      + ' ' + name + ' ' + args[0];
  }
}
```

Why if I am don't want use colors - new Date().toUTCString() inserted before `name`?

**Comment by siburny** [comment]
From [readme](https://github.com/visionmedia/debug#millisecond-diff) file:

> When stdout is not a TTY, Date#toISOString() is used

**Comment by amurchick** [comment]
> When stdout is not a TTY, Date#toISOString() is used
It seems to be optional feature - not all people wants `Date#toISOString()` in this case.

**Comment by TooTallNate** [comment]
Use the new `DEBUG_HIDE_TTY_DATE ` env var : https://github.com/visionmedia/debug/commit/56a3853b95990a22079d646601aa01e93eceb1c7
