### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by VinceFanZ** [visionmedia/debug#477]
<img width="993" alt="2017-07-18 12 33 27" src="https://user-images.githubusercontent.com/7631809/28309139-07210ac0-6bdb-11e7-950d-ac60adae3a42.png">

**Comment by wildeyes** [comment]
Experiencing this with webpack 2 and `{ presets: ['es2015', { modules: false }] }` in my babel-loader.

**Comment by acacha** [comment]
Me too. Removing { modules: false } solves the problem...

**Comment by Qix-** [comment]
This is a bug in your packager. The above is the standard way to export.
