### ISSUE TITLE
Seemingly Unable to run on Google Cloud Functions

### ISSUE THREAD

**Issue by keplersj** [visionmedia/debug#479]
I've been trying to use this module on Google Cloud Functions in order to get debug messages from some of my dependencies however I can't seem to be able to get anything to log to GCF's StackDriver Logging utility.

1st Issue: Can't set environment variables without using `process.env` in script. Because of this I can't just `DEBUG=* node [...]` I'd have to add `process.env.DEBUG = "*"` to the start of my script.

2nd Issue: `process.stderr` is seemingly ignored. I'm not sure what Google's doing behind the scenes, but I was trying to hack `debug` into working by redirecting stderr, which `debug` uses by default, to the log.

3rd Issue: Google seems to do some sort of magic with `console.*()` behind the scenes for logging to StackDriver.

Honestly, I can't tell at this point if this is an issue that I should report to you guys or Google. And I can't be certain that all of my points above are 100% correct. But, I figure I should at least get the conversation going somewhere.

**Comment by TooTallNate** [comment]
Hey there @keplersj thanks for the report. Let me just start with that I've never used Google Cloud Functions so I'm no expert in that field.

 1. Ok well that's kind of a bummer. If Google doesn't offer any other way of setting the env variables then setting them at the beginning of the script seems like the way to go. Alternatively you could invoke `debug.enable('whatever')` before creating any debug instances.
 1. debug uses `console.log()` by default, so should be stdout, not stderr.
 1. Not really sure what to recommend on this one but sounds related to the second issue. What magic are you referring to exactly? debug basically just invokes `console.log()` by default.

**Comment by samthecodingman** [comment]
@TooTallNate Are you sure about your second point? [`src/node.js#L135`](https://github.com/visionmedia/debug/blob/2c0df9baf7aefae2ea830e9d5eb2be64f0e71f18/src/node.js#L134-L136) suggests that it is writing directly to `stderr` by default, not `console.log`.

Regarding the original issue, I wrap `debug` when I deploy to Firebase Functions (which is a fork of GCF). I'll provide my wrapper below in the hope that it will help others fix their issue. To get it working, I use the following initializer code:

```js
/**
 * Configure debug library/instance for use on Cloud Functions.
 * `process.env.FUNCTION_NAME` will normally be truthy when deployed and falsy offline.
 * @param  {Object} debug - the debug library or instance to configure.
 * @param  {(Boolean|Object)} force - If truthy, the changes are made even if
 *                                    not executed from a deployed function.
 * @return {Object} - the value of debug
 */
function configureDebug(debug, force) {
  // If not deployed (and not forced), return immediately.
  if (!process.env.FUNCTION_NAME && !force) return debug;

  // rebind after stack driver injections
  debug.log = console.log.bind(console);
  debug.error = console.error.bind(console);

  // unless otherwise specified, when deployed, don't use colors.
  if (process.env.DEBUG_COLORS == null) {
    debug.useColors = () => false;
  }

  return debug;
};

const functions = require('firebase-functions');
const debug = configureDebug(require('debug'));
// functions.config()[namespace][varName] is the static runtime configuration for Firebase Functions.
debug.enable(functions.config().debugging.debug); 
```

Google Cloud does support [runtime configurations](https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest/), however I don't think they are useful in Functions because they use a REST API and would be too slow. Unfortunately, until something faster comes along, hard-coding your debug values might be the way to go.

An alternative that I have used in the past is to prefix my cloud function's name with `debug_` or `debugAll_` and use:
```js
let funcName = process.env.FUNCTION_NAME;
if (funcName) {
  if (funcName.startsWith('debug_')) {
    debug.enable('f:' + funcName.slice(6) + ',stcm:*'); // I prefix debug in my libs with `stcm:`
  } else if (funcName.startsWith('debugAll_')) {
    debug.enable('*');
  }
}
```
This worked fine on Firebase Functions, whether the `FUNCTION_NAME` environment variable is also present on GCF, I don't know.

**Comment by piuccio** [comment]
Just had a similar problem, however in my case I'm trying to debug a library (simple-oauth2) pulled in from a node_modules.

I gave up trying.

**Comment by techieshark** [comment]
Using `.enable()` and `.log` allowed this to work with Google Cloud Functions:

1) Deploy a .env with non-sensitive settings, like DEBUG:
```
DEBUG=your_module
```
Then in your code:

```js
require('dotenv').config(); // reads .env into process.env

let debug = require('debug');
debug.enable(process.env.DEBUG);

// set all output to go via console.info [so this works w/ Google Cloud Functions]
debug.log = console.info.bind(console);

logger = debug('your_module');
logger('some error');
```

See [this change](https://github.com/visionmedia/debug/commit/ab5083f68a7e4c1ab474ff06cd5995d706abf143) to the README about `enable()` and [this bit](https://github.com/visionmedia/debug/blob/ab5083f68a7e4c1ab474ff06cd5995d706abf143/README.md#output-streams) about changing to `console.log`.

**Comment by Qix-** [comment]
Hey @keplersj, did the above responses answer your question?

**Comment by keplersj** [comment]
I haven't been on the team that I encountered this issue with for a few months now, so I can't definitively say if this resolves the issue or not. From what I remember @techieshark's answer seems like a good and applicable solution. Perhaps @piuccio can way in, but otherwise I think that this issue is good to close.

**Comment by Qix-** [comment]
Awesome, thanks :)
