### ISSUE TITLE
Problems running debug in Win10; none of the found solutions work

### ISSUE THREAD

**Issue by 2beens** [visionmedia/debug#482]
Still having the same issue ( #219  ) on Win10. 
I have tried every method mentioned there (and elsewhere), but nothing seems to work, I still get the message: "'DEBUG' is not recognized as an internal or external command,
operable program or batch file."
Gist link which contains the npm complete log:
https://gist.github.com/2beens/871a90f07b8a6a1e83d5c612efeda661

**Comment by TooTallNate** [comment]
You are not setting the env var correctly for Windows. That is the Unix syntax that you are using. Did you read https://github.com/visionmedia/debug#windows-note ?

**Comment by 2beens** [comment]
But of course. That was actually the first thing I tried. Also, as I can see from the comments, I am not the only one experiencing this issue on Win10.

**Comment by npasparuhov** [comment]
I also met a problems with win 10 using $env:DEBUG = "server-" to set the proper env, also try some other "solutions" and nothing work

**Comment by fcastilloec** [comment]
Has anybody found a workaround for this? I found a bug report on `electron` that none of the `console.*` where being shown to the terminal. In that thread, the only workaround (more of a "hack" quoting the author) is this https://github.com/electron/electron/issues/6946#issuecomment-309449176
That works for CMD and PowerShell.
