### ISSUE TITLE
debug 3.0.0 in a Browser

### ISSUE THREAD

**Issue by ilyaigpetrov** [visionmedia/debug#491]
Prior to v3.0.0 I used this code:
```js
debug.enable('weer:*');
```
But there is no `.enable` in v3.0.0, so I tried this to no avail:
```js
localStorage.debug = 'weer:*'
```
How to enable debug v3.0.0 in a browser?

**Comment by TooTallNate** [comment]
`debug.enable()` is still in v3.0.0
