### ISSUE TITLE
[ts] Property 'log' does not exist on type 'IDebug'.

### ISSUE THREAD

**Issue by viztastic** [visionmedia/debug#492]
When I attempt to set 

```javascript
import debug = require("debug");
debug.log = console.info.bind(console);
```

I get an error on the second line saying `[ts] Property 'log' does not exist on type 'IDebug'.`

I believe this is due to the type definition missing the `.log` property on the uppermost function.

**Comment by thebigredgeek** [comment]
Yup looks like it.  We should get a PR going on the typescript definition to update it to the latest interface

**Comment by TooTallNate** [comment]
Correct me if I'm wrong but it looks like it's been there from the very beginning https://github.com/DefinitelyTyped/DefinitelyTyped/commit/fe09ccfd68e9fcab455b584e5b2d82f40cd95ae4#diff-b39fd593e361bdd01107cbe98ee055bdR22.

**Comment by thebigredgeek** [comment]
Hmm that's strange.  Totally didn't see this
