### ISSUE TITLE
debug 3.0.x messes colors in WebStorm?

### ISSUE THREAD

**Issue by igornostali** [visionmedia/debug#493]
Hi everyone,

I'm working in WebStorm and have been enjoying debug colors for a good while. However, after an update from debug@v2.6.x to debug@v3.0.x all of the colors are gone being replaced by a straight red.

Downgrading back to debug@v2.6.x - colors are back.

Please refer to attached image. Sequelize uses debug@latest and entries are shown in red, perhaps they used to be colored before update.

app-user:scripts: are my entries written with debug@v2.6.x. Change I debug to v3.0.x, they are turned red.

Any thoughts?

![debug-3 0 x](https://user-images.githubusercontent.com/8713251/29829220-78adcb1a-8ce7-11e7-9be3-eda3f9f537e1.png)

**Comment by Qix-** [comment]
@TooTallNate did debug v3 change to outputting to stderr? That's my first guess.

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/blob/master/src/node.js#L126 < yup.  You can override:

```js
const debug = require('debug');
debug.log = console.log.bind(console);
```

**Comment by Qix-** [comment]
Yeah :/ IMO Webstorm should just be issuing `\x1b[31m` at the beginning of lines and allowing the program to output its own colors.

**Comment by thebigredgeek** [comment]
To be clear, you can parse the output text before passing to `console.log` if you override `debug.log`, so really you can fix this however you'd like in application code

**Comment by TooTallNate** [comment]
Closing since there's nothing actionable on our end for this one.

**Comment by segrey** [comment]
Hi,
Indeed, WebStorm doesn't support stderr coloring at the moment (https://youtrack.jetbrains.com/issue/IDEA-137769). It's not an easy fix, because it will lead to API breakage. But this task it is on my list. Meanwhile, why is it impossible to configure output stream for debug package, like before: `DEBUG_FD=1`?

**Comment by Qix-** [comment]
@segrey Thanks for handling it!

Configuring output streams isn't common in unix environments. `debug` would be the first package I've ever seen that allows you to select which file descriptor you want to output on. Usually you let the shell redirect descriptors.

**Comment by segrey** [comment]
Agree, configuring output stream isn't common, but it was working like this before :). Alright, will try to fix it on WebStorm's side.

**Comment by skn3** [comment]
for anyone looking for a quick fix, as mentioned above you can bind to the console. Remember to do it like so:

```javascript
require('debug').log = console.log.bind(console);
```
