### ISSUE TITLE
No colors with docker-compose up.

### ISSUE THREAD

**Issue by Kostanos** [visionmedia/debug#498]
Hi, when I run docker image with sh or bash colors works perfectly.
But when I run `docker-compose up` with `tty: true`, I see always `m` character on each log line, and no color, I also found that if there is some space before `debug` colors are working well.
For example `nodejs nodemon` tool is showing some debug with space and without space (see screenshot).

Probably it is something more docker-compose related, but I wonder why nodemon logs some time comes with color and sometimes with `m` character??

Also `ms` at the end of the line is with colors.

```
fn_ws_api       |   nodemon:watch watching dir: /root/app/lib/models/ModelBase.js +0ms
fn_ws_api       |   nodemon watch is complete +0ms
fn_ws_api       | mws:info:db Connecting.. +0ms
fn_ws_api       | mws:info:index Server is listening on port - 9002 +0ms
```
![image](https://user-images.githubusercontent.com/1136702/29999981-867d0fea-9029-11e7-8fd9-b8406475dfcb.png)

**Comment by thebigredgeek** [comment]
As an aside, why are you running as root?

**Comment by Kostanos** [comment]
Do you think this may affect?

**Comment by thebigredgeek** [comment]
No haha.  Just curious.  Most people I know try to avoid root.  Usually you can expose `8080` or something inside the container and then bind to some other port on the host. Usually you use HAProxy or NGinx or ELB to forward from `80` down to some other non-protected host port on your actual hardware, which is in turn mapped to another port internally within the container :P

**Comment by thebigredgeek** [comment]
I think for Compose it might just be the way it handles stdout/stderr.  Remember, compose is piping the stream from container-specific stdout/stderr into it's own stdout/stderr.  I could be wrong, but I think that might be why.  @TooTallNate thoughts?

**Comment by Kostanos** [comment]
this image is inside private VPC subnet, with only one simple microservice app, no need other users etc... the outside proxy (nginx) is forwarding traffic to it.

Regarding compose, you are right, it is piping stream, what I don't understand why in some moments it process color well in some not..

**Comment by Qix-** [comment]
Most likely because it's `nodemon` running your program and not using Pseudo-terminals, and in fact not `docker-compose`'s fault. That would explain why `nodemon` has proper debug output and the child process doesn't.

Just a guess.

**Comment by Kostanos** [comment]
nodemon works perfectly actually. When I run from inside container manually, it shows everything.

The issue is definitely in docker-compose + debug.
docker-compose even eats some characters on simple `console.log(...)` after `debug(...)` which never happens if I don't use debug.

![image](https://user-images.githubusercontent.com/1136702/30070209-bbe1dcd4-9230-11e7-80a5-7831316e4b81.png)

You may notice:

- 1 line - debug (without color)
- 2 line - debug (with color, because some spaces before probably)
- 3 line - console.log (should be test111.2, but only 2 seen) - never happens when debug is not used
- 4 line - console.log (correct)
- 5 line - console.log (should be test111.4 but only 4 seen) - never happens, weird as here we see it after previous console.log and not debug
- 6 line - debug (correct)

So I assume there is some incompatibility with docker-compose and debug;

**Comment by TooTallNate** [comment]
If I were to guess, nodemon is getting tripped up on the 256 color ANSI escape codes /cc @Qix-

**Comment by Kostanos** [comment]
@TooTallNate I tried to run app without nodemon and the issue persists.

Thank you.

**Comment by TooTallNate** [comment]
Ok so can you share some repro code?

**Comment by Kostanos** [comment]
Sure, just simple npm app with only two lines: https://gist.github.com/Kostanos/5e86e5e3f0f13fa76b65e18f6192bec7

My output of this one is:

![image](https://user-images.githubusercontent.com/1136702/30525225-a353ef46-9bd0-11e7-850e-fe3e31529da0.png)

**Comment by TooTallNate** [comment]
I get the expected output actually:

<img width="366" alt="screen shot 2017-09-18 at 12 10 39 am" src="https://user-images.githubusercontent.com/71256/30525377-d5e7530a-9c05-11e7-83a2-cc30a38948ad.png">

What version of `docker` and/or `docker-up` are you using? What OS? etc.

Here's mine:

```
$ docker --version
Docker version 17.06.2-ce, build cec0b72

$ docker-compose --version
docker-compose version 1.14.0, build c7bdf9e
```

**Comment by Kostanos** [comment]
```
$ docker --version
Docker version 17.05.0-ce, build 89658be

$ docker-compose --version
docker-compose version 1.9.0, build 2585387

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

Will update docker-compose now, let see if it will be resolved.

**Comment by Kostanos** [comment]
With newer docker-compose version it works perfect:
```
docker-compose version 1.15.0, build e12f3b9
```
so it was the docker-compose issue.

Thank you @TooTallNate for your time and help!

**Comment by dan-stormgeo** [comment]
A simple workaround which consists in starting docker-compose in background, writing the output to a file and then tailing the file.
```
docker-compose up --build | tee /tmp/docker.log > /dev/null &
tail -f /tmp/docker.log | while IFS= read -r line; do printf '%b\n' "$line"; done
```
