### ISSUE TITLE
support plain ES

### ISSUE THREAD

**Issue by thepian** [visionmedia/debug#499]
Isn't it time to support plain ES bundling rather than CommonJS. If you build for the browser, you quite often use ES source module importing.

**Comment by TooTallNate** [comment]
What is plain ES bundling?

**Comment by thebigredgeek** [comment]
Was about to ask the same thing.  I think he means the module `import` syntax rather than CommonJS `require`.  I don't know if this makes sense for a library this simple.  Any particular use case @thepian ?

**Comment by micky2be** [comment]
@thebigredgeek  When used for browsers. `import` is pretty standard nowadays.

**Comment by thebigredgeek** [comment]
Not without using Webpack or Babel though, right?  Is there a benefit to using the ES Import Syntax in this lib?

**Comment by micky2be** [comment]
Wait! Was it about rewriting the lib in ES6? Or to export debug so it supports ES6 import?
The former doesn't matter indeed. The latter will help writing code from:
`import * as debug from 'debug';` to simply `import debug from 'debug';`

**Comment by Qix-** [comment]
Isn't that just a matter of `module.exports.default = module.exports`?

**Comment by thebigredgeek** [comment]
Happy to review a PR for that @Qix-
