### ISSUE TITLE
debug example colors are not matching

### ISSUE THREAD

**Issue by Kikobeats** [visionmedia/debug#502]
I was checking colors at https://debug-browser-colors.now.sh

Looks like printed colors is different than log color

<img width="718" alt="screen shot 2017-09-13 at 10 45 29" src="https://user-images.githubusercontent.com/2096101/30368222-d8ae9f78-9870-11e7-865d-732e316daf50.png">

BTW; where is the code of this example?

**Comment by TooTallNate** [comment]
/cc @Qix- 

The code for the example is here: https://github.com/visionmedia/debug/blob/master/examples/browser/colors.html

**Comment by TooTallNate** [comment]
Thanks for the report @Kikobeats! Fixed in f54e7f56bc7f94fc87592506f3b0019cbd957f9c (https://debug-browser-colors.now.sh/ has been fixed as well).
