### ISSUE TITLE
how to use debug with PM2?

### ISSUE THREAD

**Issue by bi-kai** [visionmedia/debug#503]
how to use debug with PM2?
`DEBUG=* pm2 start app.js`
There is no debug logs.

**Comment by DanielHeckrath** [comment]
Isn't it possible to use the ecosystem.config.js to configure different environment variables when starting a process with PM2?
See [https://github.com/Unitech/pm2/wiki/Applications-Declaration](https://github.com/Unitech/pm2/wiki/Applications-Declaration)

Should be possible to include `DEBUG=*` in the `env` section of your desired process

**Comment by bi-kai** [comment]
That works, and there is another question, the debug logs are all in PM2's error log, not in out.log, do you know why?

**Comment by DanielHeckrath** [comment]
When you use debug on nodejs it writes to stderr by default (see [node.js](https://github.com/visionmedia/debug/blob/master/src/node.js#L134-L136))

It is possible though to redirect the output of a logger to another stream https://github.com/visionmedia/debug/blob/master/examples/node/stdout.js

**Comment by bi-kai** [comment]
That's greet!
