### ISSUE TITLE
Redirect debug output from required modules?

### ISSUE THREAD

**Issue by AlCalzone** [visionmedia/debug#505]
Hey all, I have a NodeJS-application in which I'm trying to redirect the debug output from modules I require. Not sure if I'm doing something wrong or what I want is not possible, so I thought I'd ask.

My situation is as follows:
```
App => has a custom debug log I want to redirect the logs to
|-- Module A => logs debug messages with debug("namespace-a")(message...)
    |-- Module B => logs debug messages with debug("namespace-b")(message...)
```
In the app, I am using the following code to replace the log function of the sub modules with my custom one:
```
process.env.DEBUG = "*";
const debugPackage = require("debug");
const debuggers = [debugPackage("namespace-a"), debugPackage("namespace-b")];
for (const d of debuggers) {
    d.log = (str) => customLogFunction(str);
}
```
However I'm not getting any redirected logs. Am I missing something?

**Comment by DanielHeckrath** [comment]
I think what your doing should work, not sure why it fails though. I've created a small gist here https://gist.github.com/DanielHeckrath/eea2a3150ebc42cf940b1494d73ffe0d based on your snippet where you can see that it works.

You have to keep in mind that the log function is only set on the instance of the debugger your creating in your array. It is not bound to the log tag.

**Comment by AlCalzone** [comment]
> You have to keep in mind that the log function is only set on the instance of the debugger your creating in your array. **It is not bound to the log tag.**

That would be the problem then. I'm not logging to "namespace-a" or "namespace-b" in my app. Module A logs to "namespace-a". Module B logs to "namespace-b". When those modules are used inside my app, I want to intercept their log messages.

Is there a way I can retrieve the debug instances created in my modules from my app and change their log function?

**Comment by TooTallNate** [comment]
The problem is that when you do `debugPackage("namespace-a")` it creates a _new debug instance_ every time, so it's not going to affect another "namespace-a" instance that is in a different file.

Instead, you can overwrite the `debugPackage.log` function in the same way, which will affect _all_ created debug instances.

```js
debugPackage.log = customLogFunction;
```

**Comment by AlCalzone** [comment]
Sadly that also doesn't work. In my app, debugPackage.instances is empty and the overwritten log function never gets called.

**Comment by TooTallNate** [comment]
So you probably have > 1 copy of `debug` in your node_modules tree (different versions, etc.)

**Comment by AlCalzone** [comment]
```
├─┬ iobroker.tradfri@0.3.0
│ ├── debug@3.1.0
│ └─┬ node-coap-client@0.4.4
│   ├── debug@3.1.0
│   └─┬ node-dtls-client@0.2.1
│     ├── debug@3.1.0
│     └─┬ node-aead-crypto@1.0.2
│       └─┬ node-pre-gyp@0.6.36
│         └─┬ tar-pack@3.4.0
│           └── debug@2.6.8
```
The first three (until dtls-client) are the ones I'm interested in. It should probably work then, since they are all @3.1.0. Or can the outdated version from tar-pack screw me here?
