### ISSUE TITLE
Json and some other file missing 

### ISSUE THREAD

**Issue by sharazghouri** [visionmedia/debug#510]
[bcrypt] Success: "E:\xampp\htdocs\Npm\node_modules\bcrypt\lib\binding\bcrypt_lib.node" is installed via remote
npm WARN saveError ENOENT: no such file or directory, open 'E:\xampp\htdocs\Npm\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'E:\xampp\htdocs\Npm\package.json'
npm WARN Npm No description
npm WARN Npm No repository field.
npm WARN Npm No README data
npm WARN Npm No license field.

+ bcrypt@1.0.3
added 112 packages in 36.621s

**Comment by TooTallNate** [comment]
Sorry, but this doesn't have anything to do with `debug`.
