### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'fd' of undefined

### ISSUE THREAD

**Issue by lsiden** [visionmedia/debug#511]
My browser console is showing:

    node.js?2506:76 Uncaught TypeError: Cannot read property 'fd' of undefined
        at Function.useColors (node.js?2506:76)
        at createDebug (debug.js?be6c:120)
        at eval (helpers.js?fd0b:5)
        at Object.<anonymous> (bundle.js:formatted:251)
        at __webpack_require__ (bundle.js:formatted:37)
        at eval (translator.js?ec05:1)
        at Object.<anonymous> (bundle.js:formatted:1296)
        at __webpack_require__ (bundle.js:formatted:37)
        at eval (index.jsx?4657:5)
        at Object.<anonymous> (bundle.js:formatted:1947)

This is happening because index.js is loading node.js and not browser.js.
The variable 'process' is defined by process.type is undefined, although process.browser === true.
I think it needs to check for process.browser.
I don't know why this began happening suddenly.

The comment in index.js says: 

	/**
	 * Detect Electron renderer process, which is node, but we should
	 * treat as a browser.
	 */

I'm using webpack dev server and I'm having a hard time figuring out where 'process' is getting defined, even with Chrome dev tools.

I looked in here: https://github.com/Kilian/electron-to-chromium/blob/master/index.js but found nothing that helps.

**Comment by lsiden** [comment]
Okay, I cloned and patched this locally and got a related error in another package that uses 'process'.  So I think it's something else.  I'll try to keep you posted, in case others have a similar problem.

**Comment by lsiden** [comment]
I found the problem.  In my package.json, I had this:

    "babel": {
      "presets": [
        "es2015",
        "react"
      ],
      "plugins": [
        "transform-object-rest-spread",
        [
          "module-resolver",
          {
            "root": [
              "./src",
             "node_modules"
            ],
            "alias": {
              "@alc": "alc",
              "@lib": "lib",
              "@fixture": "__fixture__",
              "@languages": "languages"
            }
          }
        ]
      ]
    },

I replaced babel.plugins.module-resolver.root with this:

            "root": [
              "./src"
            ],

[babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) has been a real nightmare for me.  I really like the convenience when it works, but I wish there were an alternative that was easier to configure without breaking everything.

**Comment by parikshit223933** [comment]
I was facing same issue with socket.io-client.
I have socket.io-client version 2.4.0 which internally uses debug version 3.1.0

whose node/browser selection criteria is:

```javascript
if (typeof process === 'undefined' || process.type === 'renderer') {
  module.exports = require('./browser.js');
} else {
  module.exports = require('./node.js');
}
```
which is slightly different from current debug selection criteria. i.e.

```javascript
if (typeof process === 'undefined' || process.type === 'renderer' || process.browser === true || process.__nwjs) {
	module.exports = require('./browser.js');
} else {
	module.exports = require('./node.js');
}
```

But we are running on angular 13, whose remaining packages use debug version 4.3.3
Probably I need to upgrade my socket.io-client version to the latest one. which uses debug version ~4.3.2 at the time I am writing this. Hopefully this will solve the problem.

I am pretty sure this will solve my problem because inside socket.io-client, when I try to print `process`, it gives me this:
```javascript
{
  nextTick: [Function (anonymous)] {
    __zone_symbol__OriginalDelegate: [Function (anonymous)]
  },
  title: 'browser',
  browser: true,
  env: {},
  argv: [],
  version: '',
  versions: {},
  on: [Function: noop],
  addListener: [Function: noop],
  once: [Function: noop],
  off: [Function: noop],
  removeListener: [Function: noop],
  removeAllListeners: [Function: noop],
  emit: [Function: noop],
  prependListener: [Function: noop],
  prependOnceListener: [Function: noop],
  listeners: [Function (anonymous)],
  binding: [Function (anonymous)],
  cwd: [Function (anonymous)],
  chdir: [Function (anonymous)],
  umask: [Function (anonymous)],
  __zone_symbol__nextTick: [Function (anonymous)]
}
```

which has browser: true which will do my job and instead requiring ./node.js it will require ./browser.js

**Comment by parikshit223933** [comment]
It worked.
