### ISSUE TITLE
not working with cross-env

### ISSUE THREAD

**Issue by heinhoang** [visionmedia/debug#513]
wins10
node 6.9
"debug": "~2.6.3",
"cross-env": "^5.0.5",
generate project using [express generator](https://expressjs.com/en/starter/generator.html)

In `package.json` setting script like this:
`"start": "cross-env DEBUG=project-name:* & npm start",`
It runs server but debug's not working?

**Comment by abenhamdine** [comment]
It works for me on Windows 10 64 bits 

"cross-env": "^5",
 "debug": "^3.1.0",

**Comment by Qix-** [comment]
@heinhoang did @abenhamdine answer your question?

**Comment by heinhoang** [comment]
hey, thanks. I close this now
