### ISSUE TITLE
if you use it from within docker

### ISSUE THREAD

**Issue by georgearrowwood** [visionmedia/debug#515]
if you use it from within docker, it does not work as expected, instead of showing default behaviour with colours and milli seconds between messages it shows full time, to make it work as default, you need to add:
DEBUG_COLORS=true
to command line 
I had to debug code to make it work, this behaviour could be documented,  added in to readme file

**Comment by johnelliott** [comment]
@georgearrowwood was this while viewing docker-compose output? I see console.error and console.log working, but debug doesn't appear 🤷‍♂️

**Comment by Qix-** [comment]
This is a bug, the color support really needs to be cleaned up.

**Comment by Qix-** [comment]
I think we're going to switch entirely to #582 and #612 in order to solve this problem. Thanks for bringing it up :) Closing in favor of those since there's a lot of duplicated discussion.
