### ISSUE TITLE
Line Numbers do not show in the browser

### ISSUE THREAD

**Issue by krismeister** [visionmedia/debug#516]
With Debug v3.1.0, line numbers always point to the debug file `browser.js` (loading from `node_modules/debug/src/browser.js`)
![screen shot 2017-10-10 at 12 18 45 am](https://user-images.githubusercontent.com/1367719/31369183-a6cfcfa0-ad50-11e7-93e9-502d478c5377.png)

I see some closed issues on this topic: https://github.com/visionmedia/debug/issues/105
Seeing the correct line numbers would be a very nice feature.

Also, thanks for the great work.

**Comment by richdyang** [comment]
+1

**Comment by TooTallNate** [comment]
The original issue was closed because there is no actionable fix, so unfortunately I'm going to have to do the same for this one. Maybe browsers will someday support a feature to skip over that line of the stack trace but at this time it is impossible.

**Comment by j-walker23** [comment]
fyi this can be solved in Chrome with https://developer.chrome.com/devtools/docs/blackboxing.

I added two paths, and now my file/line no is correct for console logs.

**Comment by richdyang** [comment]
@j-walker23 Thanks. So smart solution. Even nobody think of this workaround.!

**Comment by petahbred** [comment]
Thanks @j-walker23

**Comment by j-walker23** [comment]
@petahbred @chaoyangnz  You're welcome!
