### ISSUE TITLE
listen for logs to namespaces

### ISSUE THREAD

**Issue by tflanagan** [visionmedia/debug#518]
I'm trying to tidy up my logs and would love to be able to split the logs up by the debug namespace(s). 

Currently, I have to overwrite the process.stdout.write function and parse each line looking for the namespaces.

As this is incredibly inefficient, I would love to get an event emitter in place where I can listen for any logs and get the namespace, message, etc passed to any handlers.

**Comment by Qix-** [comment]
Yeah there are a few issues asking for something like this. I'll open an RFC for it in a bit.

**Comment by Qix-** [comment]
See #556 :)
