### ISSUE TITLE
alternate environment variable

### ISSUE THREAD

**Issue by bmacnaughton** [visionmedia/debug#519]
I started working with some code that used debug and have found that it really helped me gain insight into the code. It works quite nicely - thanks.

I'm thinking it would be quite useful as a log-level-type facility for our app, e.g., DEBUG="app:3" or DEBUG="app:severe". But in doing that I'd like to be able to change the environment variable from DEBUG to APP_LOG_LEVEL or something more aligned with its function.

It's easy enough to clone and change the environment variable/prefix but I thought I'd float the idea of whether this was aligned with your thoughts on debug. One thought I had on implementation was that if the argument to `createDebug()` was an object as opposed to a string then allow setting options via the object. The simplest would be to change the prefix, e.g.,  `DEBUG` to `APP_LOG_LEVEL` though it might be nice to enable setting the other environment variables directly, along with the namespace, of course.

**Comment by Qix-** [comment]
Sorry, this would be a breaking change for a very subjective reason.
