### ISSUE TITLE
npm not starting 

### ISSUE THREAD

**Issue by Scottoca** [visionmedia/debug#529]
Hey guys, I'm fairly new to using terminal in general. I'm trying to set up an angular 2 environment for development but I keep getting these errors when I run 'npm start' 

Can anyone help please?

iMac13:quickstart imac13$ npm start

> angular-quickstart@1.0.0 prestart /Users/Admin/quickstart
> npm run build

> angular-quickstart@1.0.0 build /Users/Admin/quickstart
> tsc -p src/

../node_modules/@types/jsonwebtoken/index.d.ts(52,14): error TS2304: Cannot find name 'object'.
../node_modules/@types/jsonwebtoken/index.d.ts(79,76): error TS2304: Cannot find name 'object'.
../node_modules/@types/jsonwebtoken/index.d.ts(95,57): error TS2304: Cannot find name 'object'.
../node_modules/@types/jsonwebtoken/index.d.ts(104,57): error TS2304: Cannot find name 'object'.
../node_modules/@types/jsonwebtoken/index.d.ts(105,57): error TS2304: Cannot find name 'object'.
../node_modules/@types/jsonwebtoken/index.d.ts(114,77): error TS2304: Cannot find name 'object'.
../node_modules/@types/jsonwebtoken/index.d.ts(115,102): error TS2304: Cannot find name 'object'.
../node_modules/@types/jsonwebtoken/index.d.ts(133,73): error TS2304: Cannot find name 'object'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Admin/.npm/_logs/2017-12-04T09_43_54_225Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Admin/.npm/_logs/2017-12-04T09_43_54_242Z-debug.log
iMac13:quickstart imac13$

**Comment by Qix-** [comment]
This has nothing to do with this module.
