### ISSUE TITLE
`debug` key in localStore

### ISSUE THREAD

**Issue by chaoyangnz** [visionmedia/debug#535]
It's better to change `debug` key name to `DEBUG`, because on nodejs, we use `DEBUG` environment variable, but on browser, we need set localStorage key name with `debug`. A bit little confusing.

**Comment by OmgImAlexis** [comment]
@richdyang that's because they're going with the naming scheme it's used for. Environment variables should be uppercase where as localStorage keys don't have to be.

This isn't really an issue.

**Comment by Qix-** [comment]
Agreed.
