### ISSUE TITLE
Can not used in webworker process

### ISSUE THREAD

**Issue by ghostuz** [visionmedia/debug#536]
Cause localStorage is undefined in webworker process. so maybe we can use global variable or better way to make debug.js can worked in webworker process.

**Comment by hoangmy92** [comment]
I think you could fake the localStorage
https://gist.github.com/engelfrost/fd707819658f72b42f55

**Comment by ghostuz** [comment]
hmm. seem this is a great idea. just need fake localStorage. then set Debug variable. the debug should worked. 

thanks.

**Comment by williamstein** [comment]
In my application I :

- call `debug.load()` in the main thread to figure out what the state of debug is.  This works in both nodejs and the browser.
- then send a message via postMessage to the worker thread with the value of `debug.load()`, and
- finally call debug.enable(...) explicitly in the worker thread with the received debug value.
