### ISSUE TITLE
What do you think about a simple shortcut for emulating 'levels'?

### ISSUE THREAD

**Issue by flaviostutz** [visionmedia/debug#538]
I implemented https://github.com/flaviostutz/debug-server which I created for shortcutting some initizations I had to do on my various app files. 

If it is in interest of 'debug' project, I could merge my enhancements as a PR here. What do you think?

**Comment by Qix-** [comment]
Debug isn't a logging mechanism, it's a debugging mechanism. There are no concepts of 'levels', but instead namespaces. I don't think this is something that will be added as it adds another layer of complexity.
