### ISSUE TITLE
Not available as window.debug when installed with ember addon

### ISSUE THREAD

**Issue by erichonkanen** [visionmedia/debug#540]
Hello, just curious if anyone would have any knowledge on how to properly install this in conjunction with ember-debug-logger inside an ember addon?

If I install it in my normal ember app it works fine, but when I moved the logger into an addon, it seems that `window.debug` looks like this `function debug(fn) { [Command Line API] }`

I tried adding this library itself as a dependency but I'm not sure how to get it onto the window object as window.debug?

Thanks

**Comment by Qix-** [comment]
This might be better asked over at the ember repository :)
