### ISSUE TITLE
Publish UMD bundle for use in browser

### ISSUE THREAD

**Issue by LukeSheard** [visionmedia/debug#545]
With the rise of unpkg as a CDN for published bundles, would it be acceptable to publish a browser consumable bundle with the NPM package?

**Comment by Qix-** [comment]
No. Please use webpack.

**Comment by bertho-zero** [comment]
Anyone who excludes the node_modules from the build process must change their config to include debug. Or create an alias.

In any case, this is not the most practical thing.

**Comment by Qix-** [comment]
Please see https://github.com/sindresorhus/ama/issues/446#issuecomment-281014491. Using babel is the future at this point. Please modernize your build steps to use new versions of `debug`.
