### ISSUE TITLE
How to get installed

### ISSUE THREAD

**Issue by hamburger123456** [visionmedia/debug#546]
Hi,
I do not have a server or notes.
But I would like to use only the browser implementation. In your browser dict is a sample color.html witch shoud work. Unfortunately there is a debug.js required witch is not provided. Is there any chance to get it. (Without to run notes?) Thanks in advance.

**Comment by Qix-** [comment]
You need webpack and npm. Please google for some guides as there is way too much that has already been written about exhaustively and the process is entirely out of scope for this issue tracker.
