### ISSUE TITLE
Override diff time

### ISSUE THREAD

**Issue by rdadoune** [visionmedia/debug#548]
It'd be nice if there was a way to override the diff time. There are times when I'm less interested about the time between debug calls and more interested about the time it took to do something. I'm not sure what the best way to do this would be but here are a couple ideas:

```javascript
const debug = require('debug')('app:controller');
debug.markTime();
//... Some long running task
debug('Task complete');
// => app:controller Task complete +2s
```

```javascript
const debug = require('debug')('app:controller');
const hirestime = require('hirestime');
const getElapsed = hirestime();
//... Some long running task
debug('Task complete', { time: getElapsed() });
// => app:controller Task complete +2s
```

Otherwise with the current implementation limitations, output looks something like this:

```javascript
const debug = require('debug')('app:controller');
const hirestime = require('hirestime');
const getElapsed = hirestime();
//... Some long running task
debug(`Task complete took ${getElapsed()}`);
// => app:controller Task complete took 12ms +2s
```
Or you have to make two debug logs which still isn't ideal
```javascript
const debug = require('debug')('app:controller');
debug(`Start task`);
//... Some long running task
debug(`Task complete`);
// => app:controller Start task +5s
// => app:controller Task complete +12ms
```

It's not a major issue but it'd be so much prettier to have only my custom timing displayed and color coded.

What are your thoughts?

**Comment by rdadoune** [comment]
I should also mention, I'd be happy to submit a PR on this.

**Comment by Qix-** [comment]
:-1: this would introduce so much extra code for a use-case that is mis-using the library.

Please don't seek to change these readouts as it reduces their usefulness and trustworthiness.

**Comment by rdadoune** [comment]
It's one line of code actually
```
debug.markTime = () => (prevTime = new Date());
```

**Comment by Qix-** [comment]
So you override the entire debug context's timer? How is that useful for anyone?

**Comment by rdadoune** [comment]
Yes, it's the equivalent of calling `debug` with no output. How is that harmful? It's useful because I can see how long something took to run.

**Comment by Qix-** [comment]
Use a different namespace if you want different times. I don't think we'll do this - it's almost definitely an anti-pattern.
