### ISSUE TITLE
can't disable namespace

### ISSUE THREAD

**Issue by genadyp** [visionmedia/debug#550]
environment: node

I use same namespace across few files.
When I disable namespace in one file
```
    let namespaces = enabledNamespaces()
    const index = namespaces.indexOf(namespace)
    namespaces[index] = `-${namespace}`
    debug.enable(namespaces.join())
```
in other other file I see that debug doesn't have this namespace in the list of names, but the namespace still enabled  and there is an output.

**Comment by Qix-** [comment]
See #425
