### ISSUE TITLE
logging timestamp not showing

### ISSUE THREAD

**Issue by danilohgds** [visionmedia/debug#553]
Hi guys,

I am using the library with git bash and the terminal is not outputting the timestamps to the logs. Are there any special settings I have to do so logs will show timestamp?

**Comment by vapurrmaid** [comment]
@danilohgds 

I found the solution. I'm using
- git bash 2.16.0
- node v9.9.0
- debug 3.1.0

I ran:

```
export DEBUG=* && npm run start
```

Note that unlike running on a cmd, I couldn't get it to work with just `&`, I needed to use 2.

**Comment by Qix-** [comment]
Closing in favor of #582. Please move discussion there.
