### ISSUE TITLE
Return multiple debuggers

### ISSUE THREAD

**Issue by franciscop-invast** [visionmedia/debug#554]
I cannot believe I just found about this module after few years using Node.js. It looks really great and perfect for few of my workflows. I will be using it in both personal projects and at work, thanks for making it.

I was thinking that [creating multiple instances](https://github.com/visionmedia/debug#usage) in a single place is a bit messy, with either multiple `require()` or with a temp variable. So I propose to allow for returning an array when several arguments are passed for easy destructuring:

```js
// Proposed:
const [a, b] = require('debug')('mymodule:a', 'mymodule:b');

// Current:
const a = require('debug')('mymodule:a');
const b = require('debug')('mymodule:b');
```

Or to only pass an argument, with it being an array with multiple levels. I like that this mimics the output better (string => fn, array => array of fn):

```js
// Proposed:
const [a, b] = require('debug')(['mymodule:a', 'mymodule:b']);

// Current:
const a = require('debug')('mymodule:a');
const b = require('debug')('mymodule:b');
```

Please let me know if any of these (or both, with [[flat-array](https://www.npmjs.com/package/flat-array), or similar) are interesting for making `debug` more flexible.

This is a new functionality but it is retro-compatible since the docs specify a single string parameter, and this would be either multiple parameters or a parameter of different type.

I am willing to do a PR (on my spare time, not with this work account) with this functionality if this is a wanted feature

**Comment by czaarek99** [comment]
I'd say that there is no reason for implementing this. Don't you think your example is actually worse and more confusing for someone else that will be reading the code in the future? The current way the code is split up over two (or three) lines leads to quick readability.

Your current example might be fine but after just three or four ones it becomes a huge mess. Take a look at this:
```javascript 
const debug = require("debug");
const [a, b, c, d] = debug(["module:a", "module:b", "module:c", "module:d"]);
```
vs this:
```javascript 
const debug = require("debug");
const a = debug("module:a");
const b = debug("module:b");
const c = debug("module:c");
const d = debug("module:d");
```

I think this is something that you could implement yourself very easily in your own projects if you need it:
```javascript 
const debug = require("debug");
function multipleDebug(modules...) {
    const debuggers = [];
     for(const module of modules) {
         debuggers.push(debug(module));
     }

    return debuggers;
}
```

**Comment by franciscop-invast** [comment]
I found a way that is very similar without need for changing anything:

```js
const [a, b] = ['mymodule:a', 'mymodule:b'].map(require('debug'));
```

You could make it tighter if there are going to be many debuggers inside a single file as you suggested:

```js
const [a, b] = ["a", "b"].map(w => "mymodule:" + w).map(require("debug"));
```

But that is horrible for legibility. Also I keep the files fairly tight, so I guess my average will be 1-5 debuggers/file.

Something tight IMHO would be something like this:

```js
const [a, b, c, d] = require('debug')('mymodule', ['a', 'b', 'c', 'd']);
```

But that's too different from debug now and my first snippet in this comment solves my current usercase perfectly. Thanks!
