### ISSUE TITLE
npm : npm ERR! path C:\dumy1\dumy2\package.json

### ISSUE THREAD

**Issue by 13590dhimant** [visionmedia/debug#555]
I have created one solution containing more than 1 projects inside the Visual Studio 2017. 

Main solution file is reside inside the directory C:\dumy1\dumy2

But my Angular project is located C:\dumy1\dumy2\AngularDemo

When I try to start **npm start** from nuget package, I get the following error.

npm : npm ERR! path C:\dumy1\dumy2\package.json
At line:1 char:1
+ npm start
+ ~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm ERR! path C:\dumy1\dumy2\package.json:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

my package.json file is located inside the C:\dumy1\dumy2\AngularDemo

NOTE: I already set the AngularDemo as a Startup project but it couldn't help me.

Thanks in advance.

Regards,
Dhimant

**Comment by Qix-** [comment]
This has nothing to do with this module.
