### ISSUE TITLE
debug text is red

### ISSUE THREAD

**Issue by zatziky** [visionmedia/debug#557]
Do you have any idea why is the text color of `debug(...)` always red? 

![image](https://user-images.githubusercontent.com/2794365/37391888-f3a2753a-276c-11e8-8528-59549a9d1c4a.png)

I can't find any option that could influence the text color. Is it only our project? Here is how we use it:

```
const debug = require('debug')('amio-websocket:db-connector')

debug('Connection to MongoDB is open now.')
```

**Comment by jacobq** [comment]
This is not the behavior I see in my application. Perhaps some other tool in/around your application is setting the color and debug is just using whatever previous color was set?

**Comment by TooTallNate** [comment]
Are you running it through Docker? Docker colors stderr output as red.

**Comment by Qix-** [comment]
Many things output stderr as red. This is not something we can fix, sorry.

**Comment by zatziky** [comment]
@TooTallNate @jacobq  No, I'm running it using from [Jetbrains PhpStorm](https://www.jetbrains.com/phpstorm/). It really has something to do with the IDE. If I use their **npm module** then all the text colors are red. When using `npm run-script ...` or `npm run ...` the color is black:
![image](https://user-images.githubusercontent.com/2794365/37640730-3dc99f68-2c17-11e8-8418-6b63889e8903.png)

I'll raise a bug in Jetbrains. Thank you for your questions. ;)
