### ISSUE TITLE
Colors not shown when process output is piped

### ISSUE THREAD

**Issue by JavoByte** [visionmedia/debug#558]
Hi there,

I'm actually using this library for my projects and discovered that if the script using `debug` is spawned via `child_process` and the output is `pipe` colors are not shown since `debug` the piped output is not the terminal output stream.

So, is there anyway to get this working? If output is `inherit` works OK but I cannot subscribe to the child process stream events.

**Comment by JavoByte** [comment]
Figured it out. Just need to set `DEBUG_COLORS: true` when spawning the process.

**Comment by GioLogist** [comment]
@JavoByte +1 !
