### ISSUE TITLE
distinguish different iframe on one page on Browser

### ISSUE THREAD

**Issue by Yalhu** [visionmedia/debug#559]
I have a iframe on the top page and both of them have debug, how show I namespace them?
I use debug via browserify-as-a-service build, version is 3.1.*.
```javascript
// top
localStorage.setItem('debug','both:*');
var top=debug('both:top');
// iframe
localStorage.setItem('debug','both:*');
var ifr=debug('both:iframe');
var a=debug('both:a');
var b=debug('both:b')
```
How should I display debug one of top and iframe ,or both of them? Or disable both of them when bulid on line? 
`localStorage.removeItem('debug')` works weird. It doesn't display at once if I made a change. Is there any document for the principle of debug?

**Comment by Qix-** [comment]
I'm not sure what you're asking - could you elaborate a bit?
