### ISSUE TITLE
Can not show the actual file calls debug (browser, using webpack)

### ISSUE THREAD

**Issue by qiulang** [visionmedia/debug#564]
The only "advantage" console.log over debug in browser is console.log can show the actual file calls it, while using debug can only show something like `browser.js?172d:133`, which is debug's code

```
function log() {
  // this hackery is required for IE8/9, where
  // the `console.log` function doesn't have 'apply'
  return 'object' === typeof console
    && console.log
    && Function.prototype.apply.call(console.log, console, arguments); //this is the line 133
}
```

So is it possbile to show the actual file calls debug ?

**Comment by erikkallen** [comment]
this seems to have some information about it https://stackoverflow.com/questions/9559725/extending-console-log-without-affecting-log-line

**Comment by erikkallen** [comment]
I have some success using blackboxing as described here https://developer.chrome.com/devtools/docs/blackboxing I added the pattern ```debug*``` and it seems to work

**Comment by qiulang** [comment]
Just want to add that `blackboxing` has been changed to call `ignorelist` since 2021
