### ISSUE TITLE
Include timestamp in all log lines

### ISSUE THREAD

**Issue by jpenna** [visionmedia/debug#565]
I searched the repo and the most similar thing seems to be the `DEBUG_HIDE_DATE` env var, which was to remove timestamp for non-TTY consoles - which is not that similar also.

I would like to have a timestamp in all lines. Something like this:

```
18:06:13 collector:persist ERROR File size didn't change (logs) +0ms
18:06:13 collector:persist ERROR File size didn't change (error) +0ms
```

I could override the `console.error/log/...` methods, but I am already using a lib for logging, I didn't want to add another step on this. 

I didn't think it through, I'd like to hear what you think first, if this would be useful to the library, otherwise I can do a fork myself or get another lib (even though I like this one..).

**Comment by Qix-** [comment]
Closing in favor of #582. Please move discussion there.

**Comment by ajorpheus** [comment]
If you stumble across this issue while trying to enable timestamps for GHA log, here is the good bit:

`GitHub Actions now provides timestamps by default with "shift + T" in the logs.`

**Comment by fredkid123** [comment]
Is there a way to change the default behavior to show Timestamps (instead of have to always do "shift + T" once...)
