### ISSUE TITLE
NPM 6 - vulnerability - Regular Expression Denial of Service

### ISSUE THREAD

**Issue by yogenpatel** [visionmedia/debug#570]
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nodemon [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nodemon > undefsafe > debug                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by outsideris** [comment]
As <https://nodesecurity.io/advisories/534>, 
it already fixed in [2.6.9](https://github.com/visionmedia/debug/releases/tag/2.6.9) and [3.1.0](https://github.com/visionmedia/debug/releases/tag/3.1.0).
