### ISSUE TITLE
Is debug() executed when no DEBUG flag is passed?

### ISSUE THREAD

**Issue by ronanww** [visionmedia/debug#575]
Hi, I'm wondering if the debug lines are being executed when running an app without the DEBUG environment variable being set? Just curious to know because I'll add expensive CPU string transformation functions on it that I'd like to execute only when I'm debugging, for example

```
debug(expensiveMethod(log));
```

**Comment by DiegoRBaquero** [comment]
It does not, but you are passing as argument the result of a function call, which does call it anyways.
