### ISSUE TITLE
Is there a way to output data using console.debug instead of console.log in browser

### ISSUE THREAD

**Issue by vedmant** [visionmedia/debug#576]
HI, 

I wanted to be able to control debug output using browser log level setting (verbose, info, warning), console object has appropriate methods like console.debug, console.log, console.warn. But what I see from the source code is that only console.log is used. Could we change that to at least console.debug if it's available?

**Comment by thebigredgeek** [comment]
You can override the `debug.log` function and point it to whatever you want.

**Comment by vedmant** [comment]
Thanks, I'll check that!
