### ISSUE TITLE
Enable/disable in Web & Shared Worker

### ISSUE THREAD

**Issue by dansiviter** [visionmedia/debug#589]
It doesnt appear possible to enable/disable debug via global mechanisms (i.e window.localStorage or `process.env.DEBUG`) when using Web or Shared workers. Only alternative is via `#enable(...)` which isn't often practice when developing.

**Comment by Qix-** [comment]
Yeah it's kind of a niche use-case I think. Maybe @tootallnate will have some ideas.

**Comment by Qix-** [comment]
Yeah unfortunately, I can't see how this could be solved by `debug` in an elegant way. I think some pluggability being introduced in 5.x might yield a more elegant solution from the community.

**Comment by markomarkovic** [comment]
The simplest way to achieve this, I think, is to just send a message to the worker, something like this:

```myWorker.postMessage(['setDebug', localStorage.debug])```

and then inside worker listen for that message, and enable debug

```
import * as Debug from 'debug'
[...]
self.onmessage = (e) => {
  if (Array.isArray(e.data)) {
    const [eventName, payload] = e.data
    if (eventName === 'setDebug') {
      setDebug(payload)
    }
  }
}

function setDebug(namespace) {
  Debug.enable(namespace)
}

```
API for enabling it remains the same using localStorage.
