### ISSUE TITLE
[RFC] Uncurried usage

### ISSUE THREAD

**Issue by markasoftware** [visionmedia/debug#591]
For example, `debug('namespace', 'message')`. It is easy to check the length of `arguments` and act accordingly. I could make a PR for this pretty quickly but want to make sure the the project's maintainers are on-board first.

**Comment by markasoftware** [comment]
It is more idiomatic since JS functions are not curried by default, and many people do not use functional programming at all, making the use of curried functions at odds with their normal coding style. It's not a very big deal at all.

**Comment by Qix-** [comment]
Well function currying isn't a part of javascript, so I wouldn't really group it in as a commonplace feature.

**Comment by Qix-** [comment]
Denying this, sorry. It's a philosophical decision with no practical reasoning.
