### ISSUE TITLE
Query regarding library licensing

### ISSUE THREAD

**Issue by gmpuran** [visionmedia/debug#596]
Hi Team,

Just came across the following file in debug library:

https://github.com/visionmedia/debug/blob/master/Makefile

On line #1, there is a reference to a StackOverflow URL. As the StackOverflow subscriber's content is licensed under CC-By-SA, should this library be licensed under similar license?

Just wanted to clarify, as we see the debug library is present in many popular libraries as a dependency like body-parser, express and more. These popular libraries are likely to be included in various commercial applications, would it affect the license for such applications?

Please advise.

Thanks in advance!

**Comment by Qix-** [comment]
No. Please review what CC-By-SA requires. It does not require that the parent work is also licensed similarly. The only mainstream license that requires that is GPL, which is why it's not commonly used.
