### ISSUE TITLE
ANSI escape codes bug

### ISSUE THREAD

**Issue by danielchatfield** [visionmedia/debug#60]
It is possible that I am just looking at this wrong but I'm 90% sure [this code](https://github.com/visionmedia/debug/blob/master/lib/debug.js#L117-L120) is wrong.

``` javascript
fmt = '  \u001b[9' + c + 'm' + name + ' '
  + '\u001b[3' + c + 'm\u001b[90m'
  + fmt + '\u001b[3' + c + 'm'
  + ' +' + humanize(ms) + '\u001b[0m';
```

What this is doing is making the output pretty colours.

`c` holds the number corresponding to a colour (https://en.wikipedia.org/wiki/ANSI_escape_code#Colors)

Since the `9c` codes aren't actually standard (I haven't come across something which doesn't implement them though) it is understandable to include the equivalent `3c` code before the `9c` one as if the 'Intense' colour spec hasn't been implemented then it will display the 'non-intense' version instead. This is what I think the above code is meant to be doing but it isn't since the `3c` escape code is in the wrong place (if a system didn't implement the `intense` spec then the message would be colored and the `name` would not be which is the opposite of what it should be).

Another improvement would be to use hexadecimal e.g. `\u001b[36m` -> `\x1b[36m` as it is smaller.

This is my suggestion:

``` javascript
fmt = '  \x1b[3' + c + 'm\x1b[9' + c + 'm' + name + ' '
  + '\x1b[30m\x1b[90m'
  + fmt + '\x1b[3' + c + 'm'
  + ' +' + humanize(ms) + '\x1b[0m';
```

I wanted to get some feedback before submitting a pull request.

**Comment by MatthewMueller** [comment]
We just came across something that doesn't implement `\u001b[9`: https://papertrailapp.com/

**Comment by TooTallNate** [comment]
It should be literally the same bytes being written to the socket though. What is the standard coding you speak of?

**Comment by MatthewMueller** [comment]
Oh hmm... Haven't looked too much into it, but I was referring to @danielchatfield's original post:

> Since the 9c codes aren't actually standard (I haven't come across something which doesn't implement them though) it is understandable to include the equivalent 3c code before the 9c one as if the 'Intense' colour spec hasn't been implemented then it will display the 'non-intense' version instead

**Comment by danielchatfield** [comment]
If you look at the "SGR (Select Graphic Rendition) parameters" section of https://en.wikipedia.org/wiki/ANSI_escape_code you can see that the 90-97 parameters are not standard and some things (e.g. papertrailapp) have not implemented them. It is thus sensible to do the following:

`[standard colour (30-37)][high intensity colour(90-97)]text[reset]`

So that if something doesn't support the 90-97 parameters it will still be coloured but with the non-intense version.
