### ISSUE TITLE
Remove bower.json?

### ISSUE THREAD

**Issue by Qix-** [visionmedia/debug#602]
I was slightly absent during the Bower days - is `bower.json` relevant anymore? Can it be removed? It appears **Bower has been officially deprecated**<sup>[[1]](https://community.plone.org/t/bower-is-now-officially-dead/4246)[[2]](https://github.com/bower/bower/commit/e8b94ecbd07376996eb0bea6cb30c20deb7e89b6#diff-04c6e90faac2675aa89e2176d2eec7d8L6)[[3]](https://github.com/FrontendMasters/front-end-handbook-2017/issues/71)</sup>.

**Comment by TooTallNate** [comment]
Definitely needs to go 👍

**Comment by Qix-** [comment]
What's a proper deprecation method? It's technical a major bump. Would just a PR that is held off on merging until we're ready for a major release?

**Comment by Qix-** [comment]
Sounds good. I'll update the readme.
