### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by guyellis** [visionmedia/debug#605]
With the flurry of releases/versions that were just published, please can you update the `CHANGELOG.md` file so that we can see a summary of what happened and better understand where the breaking changes in 4.x are? Thanks.

**Comment by guyellis** [comment]
Or if the https://github.com/visionmedia/debug/releases page is where that information should be referenced can you link it from Changelog?

**Comment by voxpelli** [comment]
I very much agree with the above, the CHANGELOG should either be updated or point to the releases section on GitHub

**Comment by Qix-** [comment]
Yes, I plan on it. In the meantime, please see the post-mortem in #603 for a description of the versions that were released.

To be clear, versions should be deprecated in a way that acts like the snafu didn't happen - as if only `debug@4` was the only version released.

**Comment by Qix-** [comment]
Hi - the releases page has been updated. Thanks for the issue!
