### ISSUE TITLE
[4.0.1] breaking! => src/browser.js  references non-transpiled code (breaks non-modern browsers)

### ISSUE THREAD

**Issue by yowainwright** [visionmedia/debug#608]
![debug-error](https://user-images.githubusercontent.com/1074042/45396342-e5ae0b80-b5ef-11e8-8163-1943898082ab.jpg)

- [Breaking commit](https://github.com/visionmedia/debug/commit/99c95e3d54b07a918ad65bc148a2930ea8bfdd02)
- **error:** `./src/browser.js` which references [`common.js`](https://github.com/visionmedia/debug/blob/master/src/browser.js#L250) contains ES6 breaking non-modern browser compatability.

**Comment by Qix-** [comment]
This is intended. `debug@4` drops Node 4 support.

**Comment by yowainwright** [comment]
It seems the actual break happened in `4.0.1`. If the break was in `4.0.0`, this change would be expected.

It would be nice to have a note in the README or CHANGELOG. 

Thanks for your time and effort.

**Comment by Qix-** [comment]
Nope, the break was definitely in `4.0.0`. You can see in the large letters where it says Node 4 support is removed on the [releases page](https://github.com/visionmedia/debug/releases/tag/4.0.0).
