### ISSUE TITLE
broken node 4.x

### ISSUE THREAD

**Issue by leon-wu** [visionmedia/debug#609]
there are a few of 3rd party open source libraries with a dependency on 'debug': '*',

in 4.0.1, it does not support 4.x anymore because in 4.x it requires 'use strict' for let statement.

Can we get 4.x support back?

/home/circleci/my-project/node_modules/koa-route/node_modules/debug/src/node.js:132
/home/circleci/my-project/node_modules/monk/node_modules/debug/src/node.js:132
	let val = process.env[key];
	^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by leon-wu** [comment]
unfortunately i saw the release notes 'This release drops support for Node 4.'

understand but some 3rd party libraries does not bump the version very well, will talk to them.

**Comment by Qix-** [comment]
> with a dependency on 'debug': '*'

Don't ever do that. It's the _objectively_ wrong way to do things.

**Comment by dougwilson** [comment]
@Qix- I'm sorry you're going to have to deal with these issues for the foreseeable future. You see, the original author of `debug` authored a lot of modules in his time and always used `"debug": "*"` in them. The fallout will be large, especially if the later maintainers never changed it back to a version range. I feel you.

**Comment by Qix-** [comment]
Yeah, that's never good. The assumption that a public API will never change is guaranteed to cause problems. Best practices dictate never to use `"*"` as a dependency range.

I expected this would happen though, debug is rather archaic and I knew a lot of old packages did weird things with it. It's time to bring it into modern times though.
