### ISSUE TITLE
let outside strict in Node 5.9

### ISSUE THREAD

**Issue by mblarsen** [visionmedia/debug#611]
Looks like the Node 4 deprecation has token down a few more versions.

See this test case https://travis-ci.org/mblarsen/mongoose-hidden/jobs/427542577#L619

```
/home/travis/build/mblarsen/mongoose-hidden/node_modules/debug/src/node.js:132
	let val = process.env[key];
	^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by Qix-** [comment]
Node 5.9 is [not supported](https://github.com/nodejs/Release) in `debug@4`. Please upgrade your Node versions to align with the LTS schedule.
