### ISSUE TITLE
SyntaxError: Unexpected token > in grunt-contrib-connect@0.3.0

### ISSUE THREAD

**Issue by pampersautomation-infy** [visionmedia/debug#613]
Hi,

I am getting Syntax error while building on the following file. src/main/webapp/node_modules/grunt-contrib-connect/node_modules/connect/node_modules/debug/src/node.js:120

Following are the versions.

grunt-contrib-connect@0.3.0 node_modules/grunt-contrib-connect
 └── connect@2.7.11 (fresh@0.1.0, pause@0.0.1, cookie-signature@1.0.1, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.0.5, debug@4.0.1, formidable@1.0.14, send@0.1.1)

connect@2.7.11 is using the latest release of debug. Looks like it is causing the issue.

Thanks.

**Comment by Qix-** [comment]
You're most likely on an old version of Node. What is the full error message? Those are generally required to help debug any problem in software.

**Comment by Qix-** [comment]
@pampersautomation-infy please see `"node":"v0.10.33"` - you're using a version of node from almost 4 years ago. I'm surprised you get **anything** to work with it seeing as how most popular packages have moved to ES6.

If you check the releases page as I've mentioned several times in recent issues regarding this exact error, you'd see that Node 4 support was dropped.

Also, you're installing modules that have upgraded their versions of `debug` and thus have released new versions that are breaking you. This isn't the fault of `debug` - please open issues in those respective repositories.
