### ISSUE TITLE
CRA build script: Failed to minify

### ISSUE THREAD

**Issue by teddybee** [visionmedia/debug#614]
I am using the create-react-app script for a React project.
Unfortunately when I was building a release bundle I got this error:

> Failed to minify the code from this file:
>         ./node_modules/debug/src/browser.js:155

Packages are: create-react-app@1.5.2 react-scripts-ts@2.17.0 and debug 4.0.1.
Nodejs version is 10.9
Are there any workaround to fix this?

**Comment by abenhamdine** [comment]
same here.

**Comment by abenhamdine** [comment]
related https://github.com/visionmedia/debug/issues/610
perhaps it would be useful to add a notice in readme to inform users that debug is no more transpiled to es5 and thus can't works with CRA 1.X which use uglifyJS (cra 2.X will use terser)

**Comment by teddybee** [comment]
I have a temporary fix, I wrapped all code that depends on debug like this:
```
if (process.env.NODE_ENV !== 'production') {
    debug = require('debug');
}
```

**Comment by abenhamdine** [comment]
Another workaround is to downgrade to a pre-es6 version, eg debug@3.1.0

**Comment by kucenko** [comment]
I have tried import from dist `import debug from" debug / dist / debug ";` and it is work
But I am waiting for fixing this problem

**Comment by Qix-** [comment]
There's no "fix" here. Debug is ES6. Projects need to stop using Uglify and switch to Terser or Babili or something else - Uglify is no longer maintained.

You can use the `debug/dist/debug` import but it is **not officially supported** and could break at a later time. It's still not decided how to package things like this for the browser.

**Comment by vvatikiotis** [comment]
This should be in the release notes.

**Comment by Qix-** [comment]
@vvatikiotis it is.
