### ISSUE TITLE
help - cannot enter app name

### ISSUE THREAD

**Issue by chrisdel101** [visionmedia/debug#618]
**node v8.11.4
oSX 10.13.5 
Express 4.14.1**

I'm having general problems. I can get debug to work using this only: 
`DEBUG=* node ./bin/www`. But then I see all the output for all express processes.
It will not accept my app name, which appears to here `process.env.npm_package_name`. 

I enter it like this `DEBUG=appName node ./bin/www`

This is true-
`if(debug.enabled){
    console.log('true')
}`

Logging the functions back works; they are not undefined. 

In my app.js I've included this. 
```
const log = debug('app:log')
const error = debug('app:error')
log.log = console.log.bind(console); 
log('hello')
error('error')
```
When I used `DEBUG=*` the error and log are both green, rather than one being red and one being green. 

Sorry to post a help request here. If it's out of line I can move it to SO. 
I found some good stuff here, but none of it seemed to work for me https://stackoverflow.com/questions/26112075/express-debug-module-not-working

**Comment by Qix-** [comment]
```
log.log = console.log.bind(console);
```

This is unnecessary, firstly.

```
DEBUG=*=
````

Not sure if that's a typo but the second `=` shouldn't be there.

Your code as-is works fine for me.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/885648/45976079-05d3c680-c003-11e8-819a-af7275fde283.png">

What version of `debug` are you using?

**Comment by chrisdel101** [comment]
Yes that was a typo. Fixed,. 

I was on 2.6.0, whatever came with Express. Now I'm on 4.0.1. 

It seems it is not accepting the name of my app. Where is this pulled from? From the name in package.json? 
It still only works with `DEBUG=*`, but the `error` and `log` are different colors now.

I need it to work with `DEBUG=myApp` to not see all the logs. 
<img width="426" alt="screen shot 2018-09-24 at 5 07 11 pm" src="https://user-images.githubusercontent.com/14151974/45979195-54da2580-c01c-11e8-99b6-a987c3c44134.png">

**Comment by Qix-** [comment]
What do you mean "it's not accepting the name of my app"? That doesn't make sense to me.

**Comment by chrisdel101** [comment]
`console.log(process.env.DEBUG)` matches what is written on the name line of the `package.json`. Even though this variable is set to the name of my app, it is not calling the function. Only `*1` will call the function.

**Comment by Qix-** [comment]
Right - you put in `DEBUG=foo:bar` - whatever you pass to `debug()` you must also put in the `DEBUG` variable. We don't look at `package.json` at all.

**Comment by chrisdel101** [comment]
This is what I meant. I was not passing in the correct name: that's what I meant by it is 'not accepting it.' Rather though,  it was accepting it, but my input did not match anything so was useless.

The Problem: I didn't know where the "app name" in `DEBUG=appname` came from.  This post suggests it should come from the `name` field. I thought it referred the name of the entire app, coming from here, `rocess.env.npm_package_name,` and not just the single module in question.

Thanks alot for clarifying this!!!

**Comment by Qix-** [comment]
Yeah, sorry about that, that post is wrong. :) When in doubt, check the readme 💃
