### ISSUE TITLE
How do I show the exact millisecond diff instead of +1s

### ISSUE THREAD

**Issue by qiulang** [visionmedia/debug#626]
Hi,
When the millisecond diff  is more than 1 second, debug will only show +1s, now I have to resort to 

`console.time() and console.timeEnd()`

So can debug show the exact diff ? 

Thanks!

**Comment by Qix-** [comment]
Does #485 do what you want?

**Comment by qiulang** [comment]
No it is not exactly what I want. I want debug to show the exact time diff, e.g. `+2500ms` (just an example) instead of showing `+1m` and b/c I can't find a way to do that I am using `console.time() and console.timeEnd()` now.

I check #485, but has that proposal been implemented ? I saw it was close but I didn't find `.begin` or `.time` in source code.

**Comment by Qix-** [comment]
@qiulang no it's not finished yet, hence why the PR is still open.

**Comment by qiulang** [comment]
So could I get a `+2500ms` instead of `+2s`?  
My original question is not related to the #485

**Comment by Qix-** [comment]
See #582.

**Comment by Qix-** [comment]
Closing in favor of #582.
