### ISSUE TITLE
NPM "errorerror: ENOTDIR: not a directory"

### ISSUE THREAD

**Issue by phemie** [visionmedia/debug#632]
I get this error whenever i try to use any ng command such as "npm -g ls --depth=0;", I get this error

 error: ENOTDIR: not a directory, open '/Users/root/.npm-global/lib/node_modules/@angular/.DS_Store/package.json
├── @angular/cli@7.0.4
└── npm@6.4.1

**Comment by Qix-** [comment]
That has absolutely nothing to do with this repository.
