### ISSUE TITLE
npm showing vulnerability in debug package

### ISSUE THREAD

**Issue by Snigdhabhatnagar** [visionmedia/debug#633]
Even after updating to the latest version of 'debug' and npm-upgrade, my npm is still showing vulnerabilities in the same. why is it so?
![bug](https://user-images.githubusercontent.com/35984472/47949156-2416d580-df64-11e8-9b2f-21f40fc9f33f.png)

**Comment by Qix-** [comment]
Low impact vuln, not sure why this wasn't reported to us directly..... Irresponsible on their part.

Thanks for the heads up, I'll take a look shortly.

**Comment by Qix-** [comment]
Oh. You're using a package that uses `debug@3.0.0` - I misread your screenshot (which is generally why it's favorable to post real test 😉).

It was patched. Please upgrade - there's nothing for us to do.
