### ISSUE TITLE
Using debug instead of console.log for browser

### ISSUE THREAD

**Issue by picwellwisher12pk** [visionmedia/debug#635]
I am very new with this things. can you guide me a little how I can use `debug` on browser? I am using Webpack to make a Firefox addon. Any help is appreciated.

**Comment by Qix-** [comment]
Please consult Google, not this repository. This is very basic npm + node + webpack knowledge. I won't write a guide for you, sorry.

**Comment by picwellwisher12pk** [comment]
I always try Google first. I have done my research. But anyway. Thanks

**Comment by Qix-** [comment]
You include `debug` in package.json and use webpack to bundle up your app. Beyond that, there shouldn't be any `debug`-related problems, and instead Google is going to help you more than I can because there are swarms of articles about how to use the various tools you've listed.

**Comment by picwellwisher12pk** [comment]
I did that and it only worked for console, not on browser console.

**Comment by Qix-** [comment]
Did you read this?

https://github.com/visionmedia/debug#browser-support

**Comment by picwellwisher12pk** [comment]
Yes I did but not much help, as using Browserify is whole new chapter for me just to use debug. 
Thanks for help anyway. I can understand your time is very valuable.
