### ISSUE TITLE
Extending IDebugger doesn't retain the .log  function

### ISSUE THREAD

**Issue by uphlewis** [visionmedia/debug#646]
const debug = require('debug');
    const log = debug('app');
    log.log = console.log.bind(console); //log to stdout

    log('Stdout test'); //writes "app Stdout test" to stdout 
    log.extend('extended')('Stdout test'); //writes "app:extended Stdout test" to stderr 

Bit annoying if i want to have a base IDebugger for stdout and another for stderr, but i have to re-bind console.log whenever i want to extend the stdout debugger.

**Comment by Qix-** [comment]
Yep, confirmed. Great catch :)

**Comment by Qix-** [comment]
Backported to `4.1.1`.

**Comment by apparatusdeus** [comment]
Is this now part of 4.1.1 because I'm currently using that build but when I extend the log function is missing.
