### ISSUE TITLE
enabling without environment vars makes no sense

### ISSUE THREAD

**Issue by activedecay** [visionmedia/debug#662]
after reading the documentation, this seems like a lot of steps to get a minimally printing logger (without using environment variables)
```
const debug = require('debug')
const log = debug('log')
debug.enable('log')
log('clearly this should print, but it does not')
```
surprisingly, there's no output.

however, if i do this, it works. this is not documented. 
```
const log = require('debug')('log')
log.enabled = true
log('this actually prints')
```

it would be great if this were documented.

**Comment by activedecay** [comment]
oh, after reading the issues, seems like this is the way to do it.
```
require('debug').enable('printer'); //enable namespace
const log = require('debug')('printer'); //reload debug
```
you have to enable the thing, then require debug again.

that's subtle! this needs to be documented

```
# Enable without using environment variables
To enable a logger without using environment variables, you must enable the namespace first, then require again and create your logger.
```

**Comment by Qix-** [comment]
> without using environment variables

Actually, closing this. `debug` is not supposed to be a general purpose logging framework. It's supposed to be used to debug your code when you need it. Check this: https://12factor.net/config

You shouldn't be enabling namespaces programmatically, IMO. The current APIs suffice.
