### ISSUE TITLE
Bug: When loaded inside node with --experimental-modules no colors

### ISSUE THREAD

**Issue by frank-dspeed** [visionmedia/debug#665]
node --experimental-modules index
```js
// index.mjs
import Debug from 'debug';
import './other.mjs'
Debug('viewModel=>')('init')
```

```js
// other.mjs
import Debug from 'debug';
Debug('other=>')('init')
```

both return with the same color in my case always red

**Comment by Qix-** [comment]
That's a coincidence. The namespaces are hashed based on the name. Install `supports-color` as a dependency to get more color.
