### ISSUE TITLE
it can not work on IE?

### ISSUE THREAD

**Issue by garysun90** [visionmedia/debug#668]
![image](https://user-images.githubusercontent.com/13114904/50672463-40da9280-1013-11e9-9321-6799cf42916a.png)
![image](https://user-images.githubusercontent.com/13114904/50672469-47690a00-1013-11e9-9d87-f9f6226daba7.png)
![image](https://user-images.githubusercontent.com/13114904/50672477-4d5eeb00-1013-11e9-9c14-1f238c2bd84f.png)

**Comment by Qix-** [comment]
I can't read Chinese, sorry. Can you translate? There's nothing wrong with the code here.

**Comment by alampros** [comment]
I'm seeing the same issue on IE11 (ugh) at the same place.

Pretty sure it's that arrow function syntax. I'm going to including `node_modules/debug` in my babel-loader scope and see if that shuts IE up.

**Comment by Qix-** [comment]
IE is pretty notoriously bad at handling debug beyond version 2 or 3. If you're targeting IE you'll need to compile for it, just like most modules nowadays.

**Comment by micky2be** [comment]
@Qix- please hear the people. IE11 is still heavily supported. As a library, it should work out of the box.
You can't ask developers to guess which module they have to transpile or not.
You should at least offer an es6 version and a transpiled version yourself.

If you wanna stand by your decision, make sure to document it in the Readme.
Cheers ;)

**Comment by Qix-** [comment]
@micky2be No. Transpile your dependencies just like everyone else does.
