### ISSUE TITLE
How to use in a create-react-app and webpack 4?

### ISSUE THREAD

**Issue by kopax** [visionmedia/debug#670]
I have installed `debug`:

```bash
$ npm install --debug
```

The installed version is **4.1.1**

I have the following source code:

```js
import React from 'react';
import { Switch, Route, Redirect } from 'react-router-dom';
import debug from 'debug';
const logger = debug('Routes');

const list = [];
const makeRoutes = (routes) => {
  routes.forEach((route) => {
    if (list.filter((l) => l.key === route.name).length === 0) {
      route.from ?
        logger(`creating redirect ${route.name} with to ${route.to}`) || list.push(<Redirect key={route.name} {...route} />)
        : logger(`creating route ${route.name} with path ${route.path}`) || list.push(<Route key={route.name} {...route} />);
      routes.childRoutes && logger(routes.childRoutes);
      routes.childRoutes && makeRoutes(routes.childRoutes);
    }
  });
  return list;
};

export default ({ routes }) => (
  <Switch>
    {makeRoutes(routes)}
  </Switch>
);
```

I am trying to enable debugging by doing: 

```bash
echo "DEBUG=:*" | tee -a .env
```

I have also tried to install [craco](https://github.com/sharegate/craco) and add the following webpack configuration: 

```js
  webpack: {
    plugins: [
      new webpack.DefinePlugin({
        'process.env.DEBUG': JSON.stringify(process.env.DEBUG),
      }),
    ],
  },
````

The documentation say that it also work for browser, how can I enable debug output in my console using [create-react-app](https://github.com/facebook/create-react-app/) and [webpack 4](https://webpack.js.org)

Thanks in advance and keep up the good work!

**Comment by Qix-** [comment]
It's not `:*`, it's just `*`.

**Comment by kopax** [comment]
So `DEBUG=* npm start` would be suffisient or does webpack configuration must be tweaker to include this in the application context?

**Comment by Qix-** [comment]
No, it's a runtime variable - what you have there (`DEBUG=* npm start`) should suffice.

**Comment by kopax** [comment]
Thank you
