### ISSUE TITLE
Remove ES6 explained

### ISSUE THREAD

**Issue by artemave** [visionmedia/debug#673]
Yesterday I submitted a pr - #672 - to remove es6  . It got rejected. Since it also got locked, I am creating this issue to explain why this is useful.

First let's go through the reasons not to do it, outlined in the "new issue" template:

> Modern best
practices dictate the use of tooling like
Babel and @babel/preset-env in order to
target the browsers that make sense for
your project.

This is true for the application code. This is not true for the library code used by the application. Because when you start transpiling `node_modules` things get really really slow. This is why people don't do it. This is why [webpack advice is not to do it](https://webpack.js.org/loaders/babel-loader/#babel-loader-is-slow-)

> We use ES2015+ for a reason.

The ES6 code using `const`, `let`, spread operator and arrow function, all nice features of ES6 but the readability improvements aren't that significant, especially considering the size of the codebase.

-----------

Few other thoughts.

Apart from people who use `debug` for their browser code, there is another type of users: people who build libraries for people to use in their browser code.

For those libraries to claim IE compatibility, they either need to use a fork similar to mine or lock `debug` module to the last non es6 version. Application developers will likely do the same - very few people want to transpile `node_modules` if they can avoid it. This is asking a lot of your users.

And finally, that big all caps warning - `DO NOT SUBMIT ISSUES ASKING TO REMOVE ES6. IT WILL BE CLOSED. IT WILL BE LOCKED.` - suggests that this kind of issue comes up frequently!

Truth is, they will keep asking. So maybe it's better to do it anyway? Even if it's not aligned with your view as a maintainer. That would be a good way to resolve this. That would make some users happy and would save your time closing ES6 issues! And would allow you to put that issue template to a better use. Sounds like a win-win-win :)

**Comment by Qix-** [comment]
> For those libraries to claim IE compatibility, they either need to use a fork similar to mine or lock debug module to the last non es6 version.

Or they use Babel. `debug` is not the only package people use. This is a dying argument.
