### ISSUE TITLE
Remove ES6 - continued from #673

### ISSUE THREAD

**Issue by artemave** [visionmedia/debug#674]
Continued discussion from #673.

I just wanted to clarify this bit:

> Or they use Babel.

As a library author, how would I use Babel to fix one of the dependecies? Sure I can produce a browser bundle with my code + dependencies, but what if my library has a common js interface? `debug` will be pulled from npm when people install my module. There is nothing _I_ can do to stop _them_ from hitting the issue.

By the way, this is a bit of an awkward conversation where each statement/reply pair is in their own ticket. I wish @Qix- wasn't locking the discussion all the time.

**Comment by Qix-** [comment]
https://babeljs.io/docs/en/babel-preset-env
https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953
https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages
https://www.sitepoint.com/transpiling-es6-modules-to-amd-commonjs-using-babel-gulp/
https://hackernoon.com/7-different-ways-to-use-es-modules-today-fc552254ebf4
http://browserify.org/
https://github.com/rollup/rollup-plugin-node-resolve
https://github.com/rollup/rollup-plugin-commonjs

Seriously, please Google this. There are a ton of resources for this. `debug` will not be removing ES6 code from its codebase.

**Comment by bowsersenior** [comment]
There's a simple workaround that does not involve wasting hours and hours battling babel/webpack/eslint configs to transpile `debug` to ES5 since there is already an ES5 version of debug in the `dist` folder. Importing it will define the debug object globally, so for browser usage you can do something like this:

```javascript
import 'debug/dist/debug';

const myDebug = window.debug('myNamespace');
```

**Comment by Qix-** [comment]
Please don't use the `dist` folder. Please use a transpiler or update your tools.

**Comment by artemave** [comment]
@bowsersenior you can use es5 compatible fork https://www.npmjs.com/package/debug-es5

**Comment by Qix-** [comment]
Please don't advertise your packages here. I can't guarantee the security of your fork because you are not a trusted maintainer of `debug`.

Locking.
