### ISSUE TITLE
How to disable it on production?

### ISSUE THREAD

**Issue by VyacheslavVV** [visionmedia/debug#676]
As I understand the proposed way to disable it`s output is to set "DEBUG" to an empty value.
But if in local storage I manually add "debug=*" I get all the output. Is there a way to force disable it?

**Comment by macten30** [comment]
i think i got

man. 14. jan. 2019 kl. 09.54 skrev VyacheslavVV <notifications@github.com>:

**Comment by Qix-** [comment]
> But if in local storage I manually add "debug=*"

If you're using `debug` in client-side code, it will _always_ be there. It's not like a C `#define LOG(x) ((void)0)` where the actual code goes away when you build for production...

Not really sure what you're asking for here.

**Comment by macten30** [comment]
i eill let it run it cause and say thx ore the uppersiy id what i dont know
but up to you ehat you shall do should debug

man. 14. jan. 2019 kl. 10.27 skrev macten30 <notifications@github.com>:

**Comment by VyacheslavVV** [comment]
Thank you for the reply.
It`s a shame that this package may not be excluded from the production build.

**Comment by macten30** [comment]
yes do what makes people happy and hopefully i get happy to

man. 14. jan. 2019 kl. 10.36 skrev VyacheslavVV <notifications@github.com>:

**Comment by Qix-** [comment]
@VyacheslavVV 	How do you expect to "exclude" it from the production build? How would we handle that? How would code that requires `debug` handle that? All of the co-located calls to `debug(...)` would have to be removed.

What you're asking for _doesn't exist_ in the world of Javascript unless you bolt on your own pre-processor.

Unset the `DEBUG` environment variable if you want to silence this package. It's pretty well laid out in the Readme.

**Comment by macten30** [comment]
didnt i just told you that i did not give a flying fuck if you want these
so cold xxx shit keep it im trying to do my best under pressure

man. 14. jan. 2019 kl. 13.49 skrev Qix <notifications@github.com>:

**Comment by macten30** [comment]
no im happy for your deeds but just dont need it to be a topic

man. 14. jan. 2019 kl. 13.52 skrev macten30 <notifications@github.com>:
