### ISSUE TITLE
memory leak when instance is created inside a function.

### ISSUE THREAD

**Issue by overflowz** [visionmedia/debug#678]
Hi, I just noticed that when you create debug instance in a function, it is starting to leak the memory without freeing. Here's how you can reproduce it:

```js
const debug = require('debug');

const loop = () => {
  const d = debug('namespace:that:i:want:for:this:function');
  d('hello world');
  setImmediate(loop);
};

loop();
```

If you run this and look at memory, it is leaking a lot without freeing them.
also does not matter if I set environment to DEBUG=* or not, it still leaks. Any thoughts?

EDIT: tested on 3.1.1 and 4.1.1 as well (had 3.1.1 version and then I upgraded to latest one to check if it was fixed).

EDIT2: using node version 10.13 and Windows 10 x64.

**Comment by Qix-** [comment]
This isn't a typical use-case for `debug`, though.

However, I agree that this shouldn't be leaking. I'll flag it as a bug.

**Comment by overflowz** [comment]
well, I found myself pretty much comfy to create instances within a functions, it helps to understand logs much better though (for me), like what function is doing what, etc. But yeah, leaks should not be happening at any cost, dunno.

**Comment by Qix-** [comment]
No, that wouldn't solve it. This will get solved with #645 as the only reason why we're storing references to debug instances is to enable/disable them after they've been created.

I think there's a solution to this in the works, just not directly.

I'll leave this open for now. Good catch, though.

**Comment by overflowz** [comment]
Yeah, I saw that and there were no other usages for it but enabling/disabling the instances.

about #645, I'm not sure, though. I'd either remove the saving part completely (which will remove enable/disable feature) or save instances uniquely by namespace (IMO it is more reasonable to have unique namespaces, since having same namespace in different places could be misleading, dunno).

**Comment by Qix-** [comment]
> save instances uniquely by namespace

**Comment by overflowz** [comment]
Oh, didn't knew about the dynamic part (not using it, hehe). So yeah, will be waiting for them.

Cheers.

**Comment by brandonros** [comment]
> Just found out, that you have to call destroy() on it if you want it to not leak.
> 
> I'm not sure how good this case is but, at least it should be documented like big red fancy text or something since I lost quite a lot of time to understand why my app was leaking though.

Is there anyway we can get https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/debug/index.d.ts updated to expose the `destroy` method?

**Comment by Qix-** [comment]
@brandonros feel free to open a PR there.

**Comment by brandonros** [comment]
@Qix- The open source community amazes me. The time it took you to tell me to open a PR, you could have opened the PR...

**Comment by Qix-** [comment]
Hi @brandonros, I'm currently dealing with moving into my new apartment across the planet, a full time job, a new full time job on the way, and some heavy family issues.

Nobody is paying me to do any of this.

I have been primarily mobile for the last 3 weeks. I have little problem responding to issues on GH, but am relatively incapable of doing much coding.

I apologize if my schedule doesn't revolve around *you*, sir.

**Comment by ibc** [comment]
Wow! so if I create dynamic  `debug` instances (such as in the constructor of a class) they will leak when the class instance no longer exists!

```js
class Foo {
  constructor(id) {
    this.debug = debug(`foo:${id}`);
  }
}

const foo = new Foo(1234);
```

so if I create many `Foo` instances it will leak `debug` instances!

IMHO it should be clearly documented that this may happen and that a `destroy()` method exists to prevent that. The `destroy()` method is not even documented in the README. I will send a PR documenting it.

**Comment by Qix-** [comment]
This is a bug, the `destroy` method is unnecessary and this bug shouldn't exist. v5 will have this fixed, but when v5 occurs is still up in the air as it's going to be a laborious release.

**Comment by ibc** [comment]
Thanks. Just wondering: how is this supposed to be fixed? AFAIU the leak happens because debug instances are stored in an array, and they are stored in an array to make it possible  for `debug.enable()` and `debug.disable()` to affect existing debug instances. What is the solution for this without an explicit method called by the app?

**Comment by Qix-** [comment]
`WeakMap`. IE10 support ends this month, which means it's an opportune time to use it as everything LTS or newer right now supports beside IE10.

**Comment by overflowz** [comment]
As far as I know, WeakMap is not iterable and only keys you can have there can be instances only. May I know how are you going to solve that problem with that? I am really curious though.

**Comment by ibc** [comment]
Exactly. `WeakMap` or `WeakSet` cannot be used for this. You don't have access to its content. You just can know whether they contain an object (a debug instance in this case) or not.

**Comment by Qix-** [comment]
You're right; a WeakSet could have been used to implement this if need be, but it turns out this isn't necessary.

I went ahead and proposed a fix in #740 because frankly I'm tired of people bringing this issue up, lol.

Please test it.

**Comment by Qix-** [comment]
Published as `4.3.0` under tag `beta` (therefore it's not going to be automatically pulled unless you explicitly ask for it). Please let me know that it still works for you.

**Comment by jehon** [comment]
Great news!
Any idea when this 4.3.0 will go out?

**Comment by Qix-** [comment]
It is out. `npm i debug@4.3.0`. It's in beta because millions of people use this package so most releases stay on beta for a good while to make sure there aren't problems. Nothing is stopping you from using it.
