### ISSUE TITLE
supports-color breaks coloring

### ISSUE THREAD

**Issue by NaNraptor** [visionmedia/debug#683]
This line over here defines an ANSI extended color set for bright color which doesn't display correctly: (by incorrectly I mean it's just bold white color)

https://github.com/visionmedia/debug/blob/5c7c61dc0df0db4eb5de25707d8cd1b9be1add4f/src/node.js#L169

It shouldn't(?) have a traling `;1` after `${colorCode}`. So the line should like:

 ``const prefix = `  ${colorCode}m${name} \u001B[0m`; ``

This fixes the bug (for me :) )

EDIT: This supports my observation [256 colors](http://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html#256-colors)

Also from the article:

> Note that the bright versions of the background colors do not change the background, but rather make the foreground text brighter. This is unintuitive but that's just the way it works.

and the `;1` option only applies to `\u001b[44` ie background colors, while the `\u001b[38` option for foreground colors does not have such thing

**Comment by NaNraptor** [comment]
Sorry for the late reply, here are some screenshots.

The result is the same when using git bash(with cmd console and powershell):
![debug_old](https://user-images.githubusercontent.com/23401236/52417273-69a6e980-2ae3-11e9-89ce-ca4f5364ba2c.png)

Here is the result when I use the version from [my fork](https://github.com/NaNraptor/debug):
![debug_my](https://user-images.githubusercontent.com/23401236/52417372-a5da4a00-2ae3-11e9-8ea8-ca34a385d9cb.png)

**Comment by Qix-** [comment]
Could you do me a favor and change this line:

https://github.com/visionmedia/debug/blob/5c7c61dc0df0db4eb5de25707d8cd1b9be1add4f/src/node.js#L168

To this:

```diff
-const colorCode = '\u001B[3' + (c < 8 ? c : '8;5;' + c);
+const colorCode = '\\e[3' + (c < 8 ? c : '8;5;' + c);
```

Re-run and post the results here?

**Comment by NaNraptor** [comment]
Yes of course.

First run is when `;1` is still in the code, the second run is without it:

![debug_test](https://user-images.githubusercontent.com/23401236/52435270-51e25c00-2b09-11e9-841e-e9025e7728b6.png)

**Comment by Qix-** [comment]
Those look fine, they should be working. This is a bug in CMD.exe.

I'll open a ticket with Microsoft later.

**Comment by NaNraptor** [comment]
You are in fact correct, I tested it on a mac and it works just fine

**Comment by Qix-** [comment]
Bold has always been quite broken on Windows. Here's an open issue that probably has to do with this bug.

https://github.com/Microsoft/console/issues/109

For posterity, here's a bug where bold-off (`21m`) was completely missing that I filed in 2017.

https://github.com/Microsoft/WSL/issues/2174

cc @zadjii-msft is this a new problem that I should file, or is this the same as microsoft/console#109?

**Comment by zadjii-msft** [comment]
So, microsoft/console#109 is mostly just tracking the rendering of bolded text, which is still somewhere down the backlog and unsupported.

However, the bug here is that combining 256-color values (`38;5;210m` for ex) and boldness (`1m`) doesn't work correctly. I don't know when for a fact that was fixed, but I do believe it's fixed in Insider's now, and will be generally available with the next Windows update after 1809:

![image](https://user-images.githubusercontent.com/18356694/52488126-02854580-2b74-11e9-9b19-1a121e21f724.png)

**Comment by Qix-** [comment]
Wonderful, thanks for the quick response as always @zadjii-msft :)

I'm going to close this as fixed. Thanks for the report @NaNraptor, good find.

**Comment by webuniverseio** [comment]
@Qix, what if I make a PR that removes boldness based on environment variable? I'm working in a corporate environment and very likely that windows updates that will bring this feature will take a while :(. And it will depend on each of my coworkers to update their machine 😢. Thanks

**Comment by Qix-** [comment]
@webuniverseio I wouldn't approve that, unfortunately. I don't want to introduce more environment variables when we're working to remove them.

**Comment by webuniverseio** [comment]
@Qix- Thank you so much for your response. Unfortunately I'm trying to archive the opposite - get different colors with `supports-color`. I guess for now I have to use a workaround. 

I have a different proposal - what if everything will be in normal font when color is used? Even on windows 1809 I don't see bold text & even if was bold, not sure how much value would it add. I guess it can be useful when there is no color & perhaps it really helps to visually separate logs on other OS...

Please let me know what you think. Thank you!
