### ISSUE TITLE
Piping to NodeJS  Web inspector console format in Puppeteer

### ISSUE THREAD

**Issue by dtel** [visionmedia/debug#684]
I'm using puppeteer to evaluate some scripts and capture its console output to NodeJS environment. The package I'm using to run in Puppeteer uses the debug module.

The problem is the output in Nodejs comes in the web inspector format (%c) and hence not colorized. Is there a way to tell debug to output in NodeJS format when run in puppeteer (browser)?

**Comment by Qix-** [comment]
It's tricky - there's an issue about it where I implement a hack to do this, but it relies upon Node internals and thus might not work as expected.

See https://github.com/visionmedia/debug/issues/483#issuecomment-324493212.

Going to close as a duplicate.
