### ISSUE TITLE
Only ms colored

### ISSUE THREAD

**Issue by JRakhimov** [visionmedia/debug#690]
OS: Windows 10;
Node: 11.9.0;
Debug: 4.1.1;

![Photo](https://i.ibb.co/xhc7Hnp/1.png)

What am I doing wrong? supports-color is installed and useColors set to True too, debug.color => 208, 209 and this okay too. Help pls

**Comment by Qix-** [comment]
Please search the issues next time. Exact duplicate of #683. Microsoft has responded and said a fix is on the way.
