### ISSUE TITLE
Can't enable namespace disabled by `notThis`

### ISSUE THREAD

**Issue by bato3** [visionmedia/debug#693]
Usecase:

`set DEBUG=knex:query && node file.js`

```js
const DebugModule = require('debug')

//temporary disable logging 
let x = DebugModule.disable()
DebugModule.enable(x+ ',-knex:query');  // almost OK: knex:query,-knex:query

//and try re-enable
x = DebugModule.disable()
DebugModule.enable(x+ ',knex:query') // Don't work: knex:query,knex:query,-knex:query
```

I think that namespaces with identic name should be filtered before adding. (eg `knex:*,-knex:*`, not `knex:query,-knex:*`)

This is needed for temporary blocking and unlock namespaces eg by REST API.

**Comment by Qix-** [comment]
This is a known issue and is listed to be fixed via #425.

Going to close as a duplicate.
