### ISSUE TITLE
@FaShapouri It seems trying `npm install` in uninitialized npm package directory.

### ISSUE THREAD

**Issue by xiayongshou** [visionmedia/debug#694]
@FaShapouri It seems trying `npm install` in uninitialized npm package directory.
you should initialize package with `npm init`.
If you want to use debug without package initialize, just use `npm install debug`.

_Originally posted by @mooyoul in https://github.com/visionmedia/debug/issues/261#issuecomment-247752471_

thank you very much .your solution is very good!

**Comment by Qix-** [comment]
Please don't open issues to thank others.........
