### ISSUE TITLE
DEBUG_HIDE_DATE doesn't work with pm2 / in production?

### ISSUE THREAD

**Issue by dcsan** [visionmedia/debug#695]
DEBUG_HIDE_DATE

https://www.npmjs.com/package/debug#environment-variables

I can't seem to get this parameter to ever work in production,
 and logs have half the screen taken up by dates.
is there a magic value it has to be set to, or is just anything non-empty OK?
I'm just passing `true` on the command line:

    DEBUG=* DEBUG_HIDE_DATE=true pm2 start server.js --name $APPNAME

I'm using `pm2` to run the node processes, could that be related?
since:

> When stdout is not a TTY, Date#toISOString() is used, making it more useful for logging the debug information as shown below:

the output i get is of this format in the `pm2 logs`

    902|rap    | Mon, 11 Mar 2019 04:35:00 GMT RoomsModel new room

which looks a bit different from the output on your about page:
<image src="https://user-images.githubusercontent.com/71256/29091956-6bd78372-7c39-11e7-8c55-c948396d6edd.png" />

so I assume the sstdout is still thought of as a TTY

**Comment by dcsan** [comment]
so if there are alternatives to:

DEBUG_HIDE_DATE=true

or anything else I can look at please advise!

**Comment by Qix-** [comment]
This environment variable is going away in the future; see #582.

Closing as a duplicate; I know it's a bug but this is really the fix here.
