### ISSUE TITLE
How should I run debug in vue.js project?

### ISSUE THREAD

**Issue by xkubow** [visionmedia/debug#700]
my vue component:
```
<script>
import debug from 'debug'

const log = debug('app:logging')

export default {
...
  created(){
    log('testing logging');
  }
...
}
<script>
```

- did run the project in VS Code powershell:` $env:DEBUG='app:*'; npm run serve`
- did try cmder with `set DEBUG=app:* & npm run serve`
- did try set DEBUG in .env file got message `[dotenv][DEBUG] "DEBUG" is already defined in "process.env" and will not be overwritten`

What should I do to get this working corectly? I would like to see the message `testing logging` in console.

**Comment by Qix-** [comment]
https://github.com/visionmedia/debug/blob/master/README.md#browser-support

**Comment by xkubow** [comment]
I'm new to web developing. I'm using webpack. I set the localstorage in code and chcek the DevTools. But still dont see the message. Could you point me where/how to set the localstorage correcly so it is working.

**Comment by kculmback** [comment]
We use this in our Vue projects, in whatever js file is your main entry point
```javascript
import debug from 'debug'
const log = debug('app')

if (config.get('isLocal')) {
  debug.enable('app*,store*,module*,utility*')
  log('Initialized App')
}
```

The if statement is optional, we just only run `debug` if our config is set to dev mode.

**Comment by liudonghua123** [comment]
Just set `debug` item of `localstorage` and refresh your page, for example, see the following snapshot.

![image](https://user-images.githubusercontent.com/2276718/61993592-b5088080-b0a0-11e9-9a0c-1f31ee972a03.png)
