### ISSUE TITLE
Debug doesn't work in IE11

### ISSUE THREAD

**Issue by julia-dizhak** [visionmedia/debug#701]
```
args[0].replace(/%[a-zA-Z%]/g, match => {
        if (match === '%%') {
            return;
        }
        index++;
        if (match === '%c') {
            // We only are interested in the *last* %c
            // (the user may have provided their own)
            lastC = index;
        }
    });
```
The issue from bundle.js pointed to first line of this part of code

**Comment by Qix-** [comment]
Yes, please search before opening issues. Debug 4 doesn't work in ie11 without transpilation, such as with Babel.

**Comment by julia-dizhak** [comment]
We have react app and all js code under bundle with babel@7.0.0 with
```
"presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
```
But it's still doesn't work

**Comment by Qix-** [comment]
Can you show me the error please.

**Comment by Diokuz** [comment]
Even React supports es5 https://reactjs.org/docs/react-dom.html#browser-support

**Comment by Diokuz** [comment]
@julia-dizhak see https://github.com/visionmedia/debug/issues/689

**Comment by rmsheppard** [comment]
Node modules folder is usually not transpiled.  In order to fix this I had to do the following.

Update babel config
`
    module: {
      rules: [
        {
          test: /\.js$/,
          exclude: shouldExclude,
          use: ['babel-loader']
        },
`

Then the shouldExclude function is:

`
function shouldExclude(filename) {

  if (filename.indexOf('/project-name/node_modules/debug') > 0) {
    return false;
  } 
......... other code
  return true
}
`

**Comment by Qix-** [comment]
> Node modules folder is usually not transpiled

Says who?

**Comment by rmsheppard** [comment]
Considering the fact that Babel ignores that folder by default as well as not ONE other package has issues in the hundreds of dependencies in our large project.  It seems common practice for packages to be transpiled before published.  I mean if you want your builds etc to take longer by all means go right ahead.  

Now I can't say all authors do this and I'm not trying to place blame.  Just thought I would try to help someone else out if they were having the same issue.

**Comment by Qix-** [comment]
That's not a very accurate or fair answer in my opinion. 

Locking this, there's nothing more to discuss.
