### ISSUE TITLE
Not support 256 colors in windows

### ISSUE THREAD

**Issue by mileOfSunshine** [visionmedia/debug#703]
I think there is a bug in the codes.

https://github.com/visionmedia/debug/blob/5c7c61dc0df0db4eb5de25707d8cd1b9be1add4f/src/node.js#L169

Here are 3 groups of Ansi Escape Codes:

8 colors: `\u001b[30m ~ \u001b[37m`
16 colors:   `\u001b[30m ~ \u001b[37m`   +  `\u001b[30;1m ~ \u001b[37;1m`
256 colors:  `\u001b[38;5;${ID}m`    `ID: [0, 255]`

the code should remove `1;`

```js
 const prefix = `  ${colorCode}m${name} \u001B[0m`; 
```

**Comment by Qix-** [comment]
Why do you think this is a bug? `1m` is bold.

**Comment by mileOfSunshine** [comment]
According to my practice, 256 colors does not support `bold`. Below is my test result 

![image](https://user-images.githubusercontent.com/17926741/56938345-efab5d00-6b33-11e9-982a-1061c43a7f9b.png)

**Comment by Qix-** [comment]
256 came way after the VT-100. The VT-100 supported bold. Every terminal I've ever come across that supports any form of ANSI escapes supports bold. 256 colors doesn't haven't anything to do with 256 colors.

Please open a ticket with JShell, there's nothing actionable here.

**Comment by GGttyyy** [comment]
import os

os.system('cls')

for i in range(0, 16):
    line = ""
    for j in range(0, 16):
        code = str(i * 16 + j)
        line += "\u001b[38;5;" + code + "m " + code.ljust(4)
    print(line)
    print("\u001b[0m")

for i in range(256):
    print(f"\u001b[38;5;{i}m {i} Hello World! \u001b[0m")
