### ISSUE TITLE
Color support broken when loaded with `esm` support

### ISSUE THREAD

**Issue by dbo** [visionmedia/debug#704]
I know this issue reads weird, but when I load the following script with standard-things/esm the colored output is broken showing `undefined` suffices for `%`:

```bash
$ DEBUG=* node -r esm -e 'require("debug")("topic")("out: %O", { prop: "bar %" });'
```

Without loading esm it formats just fine:
```bash
$ DEBUG=* node -e 'require("debug")("topic")("out: %O", { prop: "bar %" });'
```

**Comment by Qix-** [comment]
Hi! You should file a ticket with ESM because we're not using anything special to detect color support here. Something ESM is doing is affecting this.
