### ISSUE TITLE
Doesn't work with dotenv anymore.

### ISSUE THREAD

**Issue by botond-veress** [visionmedia/debug#705]
The following code snippet works with the version `3.2.6` but it doesn't work with `4.1.1`.

```
import dotenv from 'dotenv';

dotenv.config();

const debug = require('debug');

const log = debug('app');
log('Something');
```

I've checked the 4.x change logs but I couldn't find anything related to this.

**Comment by Qix-** [comment]
There shouldn't be. What's your environment configuration related to debug?

**Comment by botond-veress** [comment]
@Qix- I am using babel with typescript.
```
"@babel/cli": "^7.4.4",
"@babel/core": "^7.4.4",
"@babel/node": "^7.2.2",
"@babel/plugin-proposal-class-properties": "^7.4.4",
"@babel/plugin-proposal-object-rest-spread": "^7.4.4",
"@babel/preset-env": "^7.4.4",
"@babel/preset-typescript": "^7.3.3",
"@babel/register": "^7.4.4",
"nodemon": "^1.19.0",
"typescript": "^3.4.5"
```

I am running it with babel-node:
```
"watch": "nodemon src/index.ts --exec \"babel-node --extensions '.ts','.js' src/index.ts\"",
```

**Comment by Qix-** [comment]
Okay but I mean what specifically isn't working?

**Comment by botond-veress** [comment]
I meant by "doesn't work" that it doesn't print the message.

**Comment by Qix-** [comment]
Right, so what is `DEBUG` set to?

**Comment by Qix-** [comment]
Right, so what is `DEBUG` set to?

**Comment by botond-veress** [comment]
It is set to `app`.

When I run it with `DEBUG=app yarn start` it logs to the console, but if I set it in the .env file it doesn't log anymore.
The `process.env` value is set to `app` in both cases.

Note that I am using this library for a while now, but it stopped working since today when I updated it to the latest version.

**Comment by Qix-** [comment]
Then you need to open a ticket with them; there's nothing I can do about that.

**Comment by botond-veress** [comment]
@Qix- I think you closed the issue prematurely. It *is* a `debug` issue, not a `dotenv` issue. As I mentioned earlier the environment variables are passed correctly to my application. `debug` stopped working after I updated the `debug` library.

**Comment by Qix-** [comment]
@botond-veress then that means debug has stopped accepting the `DEBUG` variable, which isn't the case. Please verify that DEBUG is in process.env.

**Comment by botond-veress** [comment]
@Qix- It is. That's why I opened the issue.
Once I update it to `4.1.1` it stops working. If I install the old (3.2.6) version it works just fine - without touching a single line of code (just like I mentioned in my very first comment).

**Comment by Qix-** [comment]
I'm not sure how out of many millions of downloads per week you're the only one facing the issue that `DEBUG` is not working. I'm not trying to sound rude, but there would be an army of people boating about this if it were broken.

**Comment by eddyw** [comment]
@botond-veress it works for me.
I suggest you try:
```javascript
import dotenv from 'dotenv'

const env = dotenv.config()

console.dir(env.parsed) // <<<<< should include `DEBUG: '*'` from env file, for example
console.dir(env.error) // <<<<< is it `undefined`?

const debug = require('debug')
const log = debug('app')

log('Something')
```

**Comment by xamgore** [comment]
@Qix- I am the third of that army ;)

In @eddyw example `env.parsed` contains correct `DEBUG` value and `env.error` equals to `undefined`. Downgrading the `debug` version to `3.2.6` resolves the issue.

**Comment by maxbeatty** [comment]
👋 maintainer of dotenv here. from what I was able to reproduce in https://github.com/motdotla/dotenv/pull/398 dotenv is working, debug is working, but mixing together with babel-node seems to not work as expected. if anyone would like to help complete the example in that PR (i.e. make it work), that will help identify which package, if any, needs an update ❤️ I'm also open to any other fully re-produceable examples (i.e. not code snippets in comments 😸)

**Comment by Qix-** [comment]
Thanks for checking in @maxbeatty :)

**Comment by eddyw** [comment]
@xamgore I'd suggest using `ts-node` instead of `babel-node`. If you don't want the type-checking on it, use `ts-node -T`. At least as a temporary solution on development if production build really needs babel to polyfill stuff on the server for old NodeJS. Otherwise, TS can transform class properties and rest/spread on its own (set `target: "es5"` or `target: "es6"`), so you wouldn't actually need babel if it's the only thing you need it for. It works out-of-the-box with debug & dotenv

**Comment by toritsejuFO** [comment]
This is still an issue. Here I was thinking I was the only one having the issue till I found this thread.

**Comment by Qix-** [comment]
This thread has nothing actionable. Please take it to the appropriate channels.
