### ISSUE TITLE
DEBUG =* node app.js stopped working

### ISSUE THREAD

**Issue by mcorning** [visionmedia/debug#706]
I just upgraded VS Code, and the first time it tried to use DEBUG from either the bash or ps terminal, i received a 'DEBUG' term not found error.

I even reinstalled DEBUG ("debug": "^4.1.1") to no avail.

**Comment by Qix-** [comment]
Please post the error. Can't do anything without it.

**Comment by mcorning** [comment]
It appears a space before = is the cause.

Rwap

________________________________
