### ISSUE TITLE
How to output locale date string instead of Iso date string ?

### ISSUE THREAD

**Issue by TitaneBoy** [visionmedia/debug#708]
Hello everyone. I would like to use the inner output datetime when using debug but I would like that debug output local datetime, not ISO (which is shifted by many hours).

Is it possible to set the timezone or something like that in order to have the same datetime as the computer where is running debug ?

Thanks in advance for your help

**Comment by TitaneBoy** [comment]
![image](https://user-images.githubusercontent.com/15614466/58495056-89225a80-8144-11e9-98dd-5f0616cd83ae.png)

**Comment by Qix-** [comment]
See #582, it would solve your problem.

Closing as a duplicate. :)

**Comment by qiulang** [comment]
@Qix-  I check #582, e.g. tried DEBUG_FORMAT you mentioned,  but I still don't get a local time string, can you elaborate a little bit ? 
Thanks!

**Comment by Qix-** [comment]
@qiulang It's not been implemented yet.
