### ISSUE TITLE
.env file with DEBUG written as multi line doesn't work

### ISSUE THREAD

**Issue by jameskentTX** [visionmedia/debug#710]
my .env file

DEBUG=controllers.x,
controllers.y,
controllers.z

Such multi line DEBUG doesn't work.

DEBUG=controllers.x,controllers.y,controllers.z
is working

I have a very long DEBUG and it's maintenance is difficult.
It would be so much easier if I could write DEBUG in multi line.
Is it possible?

**Comment by Qix-** [comment]
No, sorry, there's no point in this. Just write something that removes the newlines for you before storing it.
