### ISSUE TITLE
.inspect() properties are deprecated

### ISSUE THREAD

**Issue by cod3gen** [visionmedia/debug#714]
Getting deprecated warning message while using debug in nodejs, ref: 

> DEP0079: Custom inspection function on Objects via .inspect()
> Type: End-of-Life
> 
> Using a property named inspect on an object to specify a custom inspection function for util.inspect() is deprecated. Use util.inspect.custom instead. For backward compatibility with Node.js prior to version 6.4.0, both may be specified.

https://nodejs.org/api/deprecations.html#deprecations_dep0079_custom_inspection_function_on_objects_via_inspect

**Comment by Qix-** [comment]
útil.inspect is very much _not_ deprecated. It's custom properties called .inspect() that are. I'm not sure that we use them, this might be coming from your application.

**Comment by Qix-** [comment]
Just checked - these are coming from elsewhere in your application. We don't use them.
