### ISSUE TITLE
request/question: How to access debug log stream

### ISSUE THREAD

**Issue by BusaniNdlovu** [visionmedia/debug#716]
Greetings. Thank you for the amazing library. I'm curious as to how to access this libraries standard output and error stream. Is it printed and ephemeral or is it written to a file. My intention is to assert in my tests whether something was logged. Any insight would be much appreciated.

**Comment by Qix-** [comment]
Definitely ephemeral, but you can override the `.log` property in order to process debug messages. However, it's not the most elegant API admittedly.

Check out #556 which would solve a lot of the testing needs, too. Not sure when it will be implemented.

Does that help?

**Comment by BusaniNdlovu** [comment]
Thank you for the quick response. Yes, your insight is extremely helpful. I'll explore further. Else I'll implement some version of [#192](https://github.com/visionmedia/debug/issues/192) .

**Comment by Qix-** [comment]
Right now the ugly hack for Node would be to pass all of those strings to `strip-ansi` and then pass them to a file.

**Comment by BusaniNdlovu** [comment]
Sounds fun. I'll get my hands dirty. Also, it just occured to me that it may prove effective to wrap a sinon spy around the debug function, then do a getCalls().args on it. I'll let you know how that pans out for the benefit of others. But otherwise you may close the issue.

**Comment by Qix-** [comment]
You can definitely do that.

Keep in mind, however, that depending on how you're using `debug`, it might be an anti-pattern to test against what's passed to `debug`.

**Comment by BusaniNdlovu** [comment]
Thank you. I willl :)
