### ISSUE TITLE
Help - not displaying in Koa

### ISSUE THREAD

**Issue by chrisdel101** [visionmedia/debug#717]
I used `debug` in express and it works. 
~Also, in Koa, the logs that come out of the box are working - i.e in the `www` file there is a `var debug = require('debug')('demo:server')` that logs `[nodemon] ` properly.~ I don't think these are debug logs actually.

My start script looks like this `DEBUG=app:* NODE_ENV=development nodemon ./bin/www` 

```
const debug = require('debug')
debug('HELLO')
```
No matter where I put this the app just ignores it, even in my `app.js`. Any advice on why?

**Comment by Qix-** [comment]
Please read the docs again. You're creating a namespace called `HELLO`, not actually outputting anything.
