### ISSUE TITLE
Possible to print line number using npm debug module?

### ISSUE THREAD

**Issue by xhliu** [visionmedia/debug#718]
I am looking at a nodejs project using debug module to log. It does not show line number and file name. Anyway to show line number or both? There are so many `debug()` statements in it, changing every one to include line number or switching to another logging library would be really cumbersome.

#343 mentions the issue, but no conclusion is reached.

**Comment by ash0080** [comment]
try this one @everymundo/linenumber
wish to integrated in debug

**Comment by Qix-** [comment]
Falls very cleanly into #582 :) Feel free to comment there!
