### ISSUE TITLE
Add Ethereum name or address to package.json

### ISSUE THREAD

**Issue by lastmjs** [visionmedia/debug#721]
I would like to see an Ethereum name or address added to the ethereum field of the package.json file. This will allow consumers of the project to know a canonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have Ethereum addresses in their package.json files: https://sustainus.io

**Comment by Qix-** [comment]
Hey :) I appreciate the inquiry but I don't use Ethereum at all so this isn't necessary. If any of the other maintainers become active and would like to do so, they are free to do so.


Thanks! :)
