### ISSUE TITLE
Can't install 'debug' with yarn (or npm) — yarn gives “warning Pattern [”debug@^4.1.1“] is trying to unpack in the same destination”

### ISSUE THREAD

**Issue by robert-barcelona** [visionmedia/debug#724]
I'm trying to install debug using yarn

`yarn add debug --dev
`

but I get the following error

> warning Pattern ["debug@^4.1.1"] is trying to unpack in the same destination "/Users/abc/Library/Caches/Yarn/v4/npm-debug-4.1.1-3b72260255109c6b589cee050f1d516139664791/node_modules/debug" as pattern ["debug@^4.1.0","debug@^4.1.0","debug@^4.0.1","debug@^4.1.1","debug@^4.1.0","debug@^4.1.0"]. This could result in non-deterministic behavior, skipping.

I saw this post about the issue (https://stackoverflow.com/questions/54485533/what-does-yarn-really-mean-by-warning-pattern-debug4-1-1-is-trying-to-u) and, following the suggestions there, deleted the debug directory referenced, as well as the directory above it, but nothing works. I also tried deleting my node_modules, and added and removed debug several times but it doesn't solve the problem.

I even tried installing it with npm, and I didn't get any errors on installation but when I build my program I get

> Uncaught TypeError: Debug is not a function at Object.parcelRequire.redux/configure-store.js.@babel/runtime/helpers/toConsumableArray (configure-store.js:6)

I am running Yarn, 1.17.3, npm 6.7.0, Node 11.15, MacOS 10.x, and my package.json is as follows ('debug' isn't in there as I had to remove it):

```
{
  "name": "smart",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "parcel ./src/index.html",
    "lint": "eslint \"src/**/*.{js,jsx}\" --quiet",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.6.0",
    "@babel/core": "^7.6.0",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.6.0",
    "babel-eslint": "^10.0.3",
    "babel-preset-react": "^7.0.0-beta.3",
    "eslint": "^6.2.2",
    "eslint-config-prettier": "^6.1.0",
    "jest": "^24.9.0",
    "parcel-bundler": "^1.12.3",
    "prettier": "^1.18.2"
  },
  "dependencies": {
    "@emotion/babel-preset-css-prop": "^10.0.14",
    "@emotion/core": "^10.0.16",
    "@emotion/styled": "^10.0.15",
    "axios": "^0.19.0",
    "bulma": "^0.7.5",
    "eslint-plugin-react": "^7.14.3",
    "immer": "^4.0.0",
    "node-sass": "^4.12.0",
    "prop-types": "^15.7.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0"
  }
}

```

**Comment by Qix-** [comment]
This isn't anything I can fix - please check your local machine as there are millions of downloads a week without this issue.
