### ISSUE TITLE
What did debug 4 introduce to make babel fails to polyfill IE 11?

### ISSUE THREAD

**Issue by qiulang** [visionmedia/debug#729]
Hi,
This is a question. 
So when I use version 3 I can use  @babel/preset-env to polyfill IE 11.
But if I use version 4 polyfill fails for IE 11 I got SCRIPT1002

```
SCRIPT1002: Syntax error
chunk-vendors.js (25052,40) //which point to 

/**
 * Colorize log arguments if enabled.
 *
 * @api public
 */

args[0].replace(/%[a-zA-Z%]/g, match => {
		if (match === '%%') {
			return;
		}
		index++;

```

I try all the ways I can think of to polyfill version 4 but I still get this error.

**Comment by Qix-** [comment]
There's not enough information here to help you. This sounds like a Babel configuration problem, and that's not a typical Javascript syntax error that I've seen (plus it doesn't really say _what_ the syntax error is).

**Comment by qiulang** [comment]
My babel config is rather simple 

```
'@babel/preset-env',
{
	debug: true,
	targets: {
		chrome: '68',
		ie: '11',
		edge: '17',
		firefox: '68'
	},
	useBuiltIns: 'usage',
	corejs: 3
}
```

From here https://github.com/socketio/socket.io-client/issues/1328#issuecomment-536525472
it said 

> This happened after updating debug from v3 to v4 which uses spread operator in its distributable.
> Very often node_modules are excluded from babel compilation for performance reasons.

I have tried to let babel polyfill & transpile but without success. So I am asking for help.

**Comment by Qix-** [comment]
This isn't really the place to ask for Babel help, sorry. Our package doesn't do anything other packages don't do.

**Comment by qiulang** [comment]
I raised the issue to babel, according to them https://github.com/babel/babel/issues/10707#issuecomment-554203412 

> The error ReferenceError: exports is not defined is thrown from https://github.com/visionmedia/debug/blob/608fca962b34e2bda841db9a4416bab6b4a62803/src/browser.js#L7, which should be considered a bug of debug because browser does not ship CommonJS exports.

**Comment by Qix-** [comment]
Please see https://github.com/babel/babel/issues/10707#issuecomment-555563162 for my response.
