### ISSUE TITLE
Why is `enable()` not a function?

### ISSUE THREAD

**Issue by PaulWieland** [visionmedia/debug#733]
I'm using TypeScript and I have the following:

```JavaScript
let debug = require('debug')('mytest');
debug.enable();
```

Which causes a JS error stating that `debug.enable` is not a function.
However this works:

```JavaScript
debug.enabled = true;
```

What am I doing wrong?

**Comment by Qix-** [comment]
What makes you think loggers have an `.enable()` method?

**Comment by PaulWieland** [comment]
@Qix- I apologize, I pasted the wrong version of my code. I just updated it.

**Comment by Qix-** [comment]
Loggers don't have an `enable` method. Only the top-level `debug` module does.

```javascript
const debugMod = require('debug');
debugMod.enable('mytest');
const debug = debugMod('mytest');
```

Though this is an anti-pattern. You should **really, really** be using the `DEBUG` environment variable.

**Comment by PaulWieland** [comment]
Thanks for the clarification, got it now.

FWIW, I'm using `enable` because docker requires that you build a brand new container from an image to change the environment variables. To me this isn't an acceptable way to turn debugging on or off.

**Comment by Qix-** [comment]
You can declare environment variables at run time.

```
docker run -ti --rm -e 'DEBUG=myapp:*' some/image
```

**Comment by PaulWieland** [comment]
Yes I know, that’s declaring it during container creation from an image.

**Comment by Qix-** [comment]
Yep, is there a problem with that? Docker containers are meant to be destroyed and re-created.
