### ISSUE TITLE
[RFC] support deno

### ISSUE THREAD

**Issue by pinghe** [visionmedia/debug#736]
Whether to support running on deno ?

https://github.com/denoland/deno

**Comment by Qix-** [comment]
I've never used Deno, is there some reason why this doesn't work on Deno?

**Comment by pinghe** [comment]
The environment variable set does not take effect.

DEBUG=myapp:*  deno my.js

**Comment by Qix-** [comment]
Would `exports.default = exports` work here? @sindresorhus what was the rationale behind not doing this? I can't remember what the arguments were and Google wasn't pulling anything up.

@pinghe ultimately, the Deno community needs to have a workaround for legacy modules they wish to use on Deno. You can't create a new runtime with different standards and expect modules/packages/plugins/whatever from other, incompatible runtimes to magically work with it.

v5 will use modules, but I won't be changing v4 to do so.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/mem/issues/31

**Comment by Qix-** [comment]
Thanks, that's what I needed.

I'll fix this within the week.

**Comment by pinghe** [comment]
Thanks.

**Comment by trivikr** [comment]
Any update on this request for supporting Deno?
Latest update as of now https://github.com/visionmedia/debug/issues/736#issuecomment-573740989

**Comment by trivikr** [comment]
Update: Deno community built it's equivalent debug utility https://deno.land/x/debug@0.1.1
GitHub: https://github.com/denosaurs/debug

**Comment by Qix-** [comment]
Yeah, Deno is a completely different platform and language. I don't really see how we'd support that.

Going to close, thanks for the update @trivikr.

**Comment by tracker1** [comment]
Should be very similar to the browser module, but exported as esm.

**Comment by AddictArts** [comment]
> @pinghe ultimately, the Deno community needs to have a workaround for legacy modules they wish to use on Deno. You can't create a new runtime with different standards and expect modules/packages/plugins/whatever from other, incompatible runtimes to magically work with it.

It recently does, not sure when, but I ran into this issue. For anyone looking like I was using an import map, ex `import_map.json` will solve it.

```txt
       │ File: .\import_map.json
   1   │ {
   2   │   "imports": {
   3   │     "debug": "npm:debug"
   4   │   }
   5   │ }
```

and to make cli execution easier ...

```text
       │ File: .\deno.jsonc
   1   │ {
   2   │   "importMap": "./import_map.json",
   3   │   "tasks": {
   4   │     "run": "deno run --allow-read --allow-write --allow-env --allow-sys ./index.ts",
   5   │     "compile": "deno compile --allow-read --allow-write --allow-env --allow-sys --no-check --unstable ./index.ts"
   6   │   }
   7   │ }
```
