### ISSUE TITLE
Debug in NestJs Application With DI and dotenv

### ISSUE THREAD

**Issue by 360disrupt** [visionmedia/debug#750]
NestJs uses DI and `dotenv` for the [configuration](https://docs.nestjs.com/techniques/configuration). I moved the initialization of the `debug` instance into the service constructor to make sure `process.env.DEBUG` is set. What confuses me is that ` this.debugSensorBoot.namespace === process.env.DEBUG` is `true` but no log appears until it is manually enabled.

```
import debug from 'debug';
...
@Injectable()
export class SensorsService {
  debugSensorBoot: any;

  constructor() {
    console.log('process.env.DEBUG', process.env.DEBUG) // logs: process.env.DEBUG sensor:boot

    // (1) init debug
    this.debugSensorBoot = debug('sensor:boot');

    // (2) process.env.DEBUG is set - no logs appear
    console.log('this.debugSensorBoot', this.debugSensorBoot.namespace === process.env.DEBUG, this.debugSensorBoot.enabled) // logs: this.debugSensorBoot true false
    this.debugSensorBoot("Im not logging anything as I'm disabled") // does not log anything

    // (3) for example this works 
    this.debugSensorBoot.enabled = this.debugSensorBoot.namespace === process.env.DEBUG; // this is true as shown above
    this.debugSensorBoot("I log")
  }
```

I can add the `.enable` in the constructor as shown above but it seems quite hacky:

`this.debugSensorBoot.enabled = this.debugSensorBoot.namespace === process.env.DEBUG; ` and it wouldn't work if it is equal.

**Comment by Qix-** [comment]
It's hard to tell without a repro case but are you initializing the environment before or after you include `debug`?

**Comment by 360disrupt** [comment]
The import of debug happens before the config (.env) is loaded. And I think it's not possible to move that import statement into the constructor as it would be possible with `require`. 

The initialization of the instance is afterward. In that moment the config is loaded and `process.env.DEBUG` exists. 

I think passing an option like:

```
import debug from 'debug';
...
// later in the code e.g. constructor of a class
const debugInstance = debug('someInstance', {reloadEnv: true});

or

const debugInstance = debug('someInstance');
debug.reloadEnv();
```

Could solve that.

**Comment by Qix-** [comment]
> The import of debug happens before the config (.env) is loaded.

I really don't believe this being the case. Without reproduction code, I can't assert either way.

Going to close for now. Let me know if this needs to be re-opened.
