### ISSUE TITLE
very wierd behavior in move from debug@3 to debug@4

### ISSUE THREAD

**Issue by osher** [visionmedia/debug#756]
I got the wierdest behavior I have seen for years.

### Overview
I got a CLI tool project with e2e tests using `mocha@7` and coverage using `nyc@15`.
My local machine is an ubuntu, and on it, everything runs well - both tests and coverage, with whatever version of `debug`. However.
My CI runs in a docker image based on `node-12-alpine`, and in it, the mocha tests pass, but the coverage which runs the **exact same tests** just under `nyc` - fails... ...wh...??

Note that coverage step pass on the builder with `debug@3`, but not with `debug@4`...

### The setup
Here's more info about the setup and what it's doing.

Each e2e test spawns the CLI tool in a child-process using `child_process.exec`, and collects the outputs from both stderr and stdout streams, and makes assertions against them.

When I run tests everything work with both `debug@3` and with `debug@4`.
However - the coverage using `nyc@15` passes on my local ununtu - it fails on the `node-12-alpine` docker image with `debug@4` and passes only with `debug@3`...

### Failures - stdout/stderr are empty
The tests fail for coded assertions because the expected output on stdout/stderr is not present - they are both an empty strings!
This happens in all the cases the CLI tool is expected to exit with a non-zero code.

### specifically for `debug@4` and for `node:12-alpine`

The problems started when a project dependency started to work with `debug@4`.
And the wierd thing is that as long as the project uses `debug@3` and it's deeply nested dependency uses `debug@4` - it works well - as if the `debug@3` cascades.
But when the project uses debug@4 - i.e - ONLY debug@4 is loaded -  coverage usign `nyc` on `node:12-alpine`  - the collected stdout & stderr of the spawned e2e runs are empty....

### help?

As a temporary solution, I'm locking to `debug@3`, but would thank any information about why it happens, and/or what must I do to use latest version of `debug`.

It's also frustrating that I cannot leave a comment about it in `package.json` to warn future developers...

Any info will help.
Thanks...

**Comment by Qix-** [comment]
Can't really help without a reproduction case. Can you supply one?

**Comment by osher** [comment]
I'll do my best, but it could take a few days. I have a general idea of my immediate suspect...

**Comment by osher** [comment]
is there anything you can tell me about what changed concerning the work with the output streams?
I could not find anything in the "changelogs"

**Comment by osher** [comment]
I did not forget, I need to snooze on this... sorry

**Comment by Qix-** [comment]
> is there anything you can tell me about what changed concerning the work with the output streams?

Not much changed in that regard IIRC.

**Comment by osher** [comment]
I'm afraid I won't be able to get the time to produce an isolated reproduction for you.

I did put more details here, and came back to link it.
https://medium.com/everything-full-stack/the-peculiar-case-of-passing-tests-and-failing-coverage-4d8b35842a5a

If I will find a free evening I might come back, but I can't promise that now :disappointed:

**Comment by Qix-** [comment]
I can't imagine what would be causing this. To my knowledge, we did _absolutely nothing_ to the stdout/stderr streams. We just outputted to them.

Whatever your coverage system is using must be the culprit. `debug` is probably just the first module you noticed the bugs in because it's usually the first module people import or include as dependencies, and thus we get a _lot_ of "bug" tickets that aren't actually `debug`'s fault.

Good luck!

**Comment by osher** [comment]
check the blog post. all the details are there.

**Comment by Qix-** [comment]
Your blog post does not show any evidence of the claims `debug` does anything with the output streams. Please feel free to point me to code that does so.

**Comment by osher** [comment]
Oh, that's not what I'm saying.
What I'm saying is that in setups where `nyc` uses debug 4 and the
System-Under-Test uses debug 3, then outputs emitted by the SUT into debug
3 are lost.

**Comment by Qix-** [comment]
There's absolutely no reason why that should be the case. That's what I'm saying. This sounds like a bug with `nyc`'s munging of standard outputs. **Nothing changed between v3 and v4 in this regard.**
