### ISSUE TITLE
I almost did not pick debug...

### ISSUE THREAD

**Issue by nareshbhatia** [visionmedia/debug#759]
but really glad that I did 👍 

Here's the long story - I was looking for a debugging library for my own work. Obviously debug was very attractive because of its popularity. However when I read the docs, there was no mention of TypeScript! It was hard to believe that such a popular dialect was simply ignored. Searched the issues, found one (https://github.com/visionmedia/debug/issues/669), which was open since Jan, 2019 - not very promising. Yes, there was a mention of @types/debug, but looking at these type definitions without any docs made it difficult to understand the usage :-(

So I moved on to my second and third choice. They both supported TypeScript and at least had a small section devoted to it in the docs. Very promising! Used them for a bit, but somethings did not feel right, e.g namespace support was an afterthought.

So I came back to debug and looked harder to understand the TypeScript definitions. Finally found this [StackOverflow question](https://stackoverflow.com/questions/47724165/how-to-use-the-debug-module-with-typescript) that helped me move forward with debug. Now that I have started using debug, I love it!

Another thing that was puzzling me was the absence of logging levels. Only after digging into issues, did I understand the philosophy that debug is not a general purpose logger, it is simply meant for debugging, i.e. console.debug!

Now that I am a fan of debug, may I suggest to emphasize the above two points in the docs. It will save hours for people evaluating and choosing a debug library!

**Comment by Qix-** [comment]
Debug is a JavaScript library, not typescript. Typescript is not a dialect of JavaScript, it's its own language.

First instinct should be to check DefinitelyTyped. There's nothing actionable here.
