### ISSUE TITLE
can debug work with jest

### ISSUE THREAD

**Issue by jdmairs** [visionmedia/debug#760]
I can run myApp to print the booting message with the following:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/5624808/83046415-fe08c880-a014-11ea-96a1-42e0beb650fb.png">

But I cannot get any messages to display during Jest testing.
I have tried this

<img width="390" alt="image" src="https://user-images.githubusercontent.com/5624808/83046490-1842a680-a015-11ea-8d4b-8cecd33c31ac.png">

**Comment by Qix-** [comment]
Can you try running Jest with `--verbose`? Also, you don't need to include `node node_modules/.bin/xxx` - just do `xxx`. The `.bin/` directory is added to `PATH` automatically by `npm`.

For example, try this:

```
env DEBUG=* jest --verbose
```

**Comment by jdmairs** [comment]
I'm getting 8lbs of babel debug too even though I used the following:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/5624808/83062425-99596800-a02c-11ea-99c1-6ac4d97be449.png">

any thoughts?

**Comment by Qix-** [comment]
what do you expect `DEBUG=formatAsLite` to do?

If your application's debug namespace is `MyApp` then you should specify `env DEBUG=MyApp`.

**Comment by jdmairs** [comment]
Sorry...I was still in jest --watch mode when I made the changes to my package.json.
Jest reran but still displayed the babel debug.  Once I killed and restarted jest --watch --verbose with DEBUG=formatAsLite it worked as expected.

Thank you for your time!
