### ISSUE TITLE
Set different colors to my logs

### ISSUE THREAD

**Issue by Shreyas-vgr** [visionmedia/debug#761]
Is there a way to customize colors of the log messages printed to terminal ?.
I do several issues of mentioning usages of 'support-color', but I was not able to set this.
I see debug just provides a color attribute as string to be set, What string values does this accept?

**Comment by jjavery** [comment]
@Shreyas-vgr it's not in the API documentation, but debug.color = number works in the current version at least. I believe these are approximately the colors/numbers: https://jonasjacek.github.io/colors/

**Comment by Qix-** [comment]
@jjavery Is correct :)
