### ISSUE TITLE
ES Module Support?

### ISSUE THREAD

**Issue by Justsnoopy30** [visionmedia/debug#762]
Is there a possibility of this project supporting ES Modules?

**Comment by Qix-** [comment]
Not for a while, sorry. Perhaps in version 6.

**Comment by Justsnoopy30** [comment]
Oh.

**Comment by Justsnoopy30** [comment]
Could someone possibly could make a fork with ESM support I could use?

**Comment by Justsnoopy30** [comment]
Or another branch labeled ESM-Support?

**Comment by Qix-** [comment]
@Justsnoopy30 Please don't double- or triple-post.

Can you explain why ESM support is an absolute requirement for you?

**Comment by Justsnoopy30** [comment]
My entire project uses ESM. I do not use a bundler, so there is basically no way to import this on the browser as it doesn't provide an ESM export.

**Comment by Qix-** [comment]
I'm not sure how to help, unfortunately. Someone can fork, but I don't recommend it. INdustry standard at the moment is to use a bundler.

**Comment by Justsnoopy30** [comment]
Okay. I ended up getting what I wanted this website called "Pika CDN" which generates ESM compliant versions of npm packages, which I then downloaded and now I can import it as an ES Module.

**Comment by muuvmuuv** [comment]
It is a requirement for projects like Angular where the compiler uses ES Syntax and libs that are ES invalid because of one dependency that is not ES. Lodash did it greatly by providing an extra package called "lodash-es".

Ref: https://github.com/socketio/socket.io-client/issues/1375

**Comment by FossPrime** [comment]
Sorry to grave dig, but why was this closed as "completed"? As of TS 4.7, native ES Modules have full stack support, which means HMR bundlers and watchers like esbuild-kit/tsx now work orders of magnitude faster than what webpack+babel+nodemon could.

I'm problem is still at large from my testing, so not "completed": https://stackblitz.com/fork/github/feathersjs/playground/tree/037fe54/vite-chat with `DEBUG="feathers:*" npm run dev`

**Comment by Qix-** [comment]
Github didn't have close reasons at the time of closure, and when they introduced the feature defaulted all closed issues as "completed" as a sane default. Clearly no work was actually completed.

See https://github.com/debug-js/debug/issues/786#issuecomment-846043104 about ESM.
