### ISSUE TITLE
How to debug objects on one line by default

### ISSUE THREAD

**Issue by waterdrop01** [visionmedia/debug#764]
Hello,

when doing `debug(myObject)` it will get printed on multiple lines.

But if doing `debug('%o', myObject)` it gets printed on a single line.

My question: Is there a global way to control this behavior (without having to add `%o` to all my debug statements)?

Thanks!

**Comment by Qix-** [comment]
```javascript
// debug-wrap.js
const debug = require('debug');

module.exports = (...args) => {
    const inst = debug(...args);
    return (...args) => {
        if (typeof args[0] !== 'string') args.unshift('%o');
        return inst(...args);
    };
};
```

Try that.

**Comment by achepukov** [comment]
would be nice to have something like `debug.defaultObjectFormatter = '%o'`
