### ISSUE TITLE
Using `debug` module with ts and VS code debugger console

### ISSUE THREAD

**Issue by tuturis** [visionmedia/debug#769]
Hi is it possible for `debug` module to log into VS code debugger console? Is there any need to add additional configuration to the tsconfig.json or the VS code debugger configuration to make it log into the console? Currently, it does not seem to work

**Comment by Qix-** [comment]
Are you setting the environment variables?

**Comment by pixelvm** [comment]
Open [https://code.visualstudio.com/docs/nodejs/nodejs-debugging]()

See the launch configuation attributes about `outputCapture`. It's value should be `std`, and this can solve the problem.
