### ISSUE TITLE
4.1.1 fails to install on Mac OS Catalina; regression from 4.1.0

### ISSUE THREAD

**Issue by alflanagan** [visionmedia/debug#771]
It looks like the inotify package is checking for linux compatibility even though I'm installing to a Mac? It should install inotify as an optional dependency, so MacOS gets it and linux does not.
[2020-07-20T14_55_50_330Z-debug.log](https://github.com/visionmedia/debug/files/4948479/2020-07-20T14_55_50_330Z-debug.log)

**Comment by Qix-** [comment]
`dev` is the conflicting parent package, not `debug`. There's no way inotify is being pulled from `debug`.
