### ISSUE TITLE
How to keep debug in bundles(umd) when optimization.minimize is true in Webpack?

### ISSUE THREAD

**Issue by gztchan** [visionmedia/debug#772]
Under optimization.minimize is true, Webpack will remove all console.*. How can i keep them in bundles(umd)?

```js
new TersePlugins({
  terserOptions: {
    drop_console: false,
    pure_funcs: [],
  }
})
```

Above params doesn't work.

**Comment by Qix-** [comment]
Not sure, this is something to take up with Webpack.
