### ISSUE TITLE
How to enable all loging **ABOVE** a certain level.

### ISSUE THREAD

**Issue by Doogiemuc** [visionmedia/debug#780]
How could I enable logging above a given level, such as  INFO, WARN & DEBUG ?

When level warn is active with `set DEBUG=WARN`  then all warn *and* info messages but no debug messages shall be shown.

This would be a manual workaround:

```
var info= require('debug')('level.XXX')
var warn = require('debug')('level.XX')
var debug = require('debug')('level.X')
```

and then for example `set DEBUG=level.XX*`   But that seems cumbesome. Is there a better way?

**Comment by Qix-** [comment]
Debug isn't a logging library, it's meant to conditionally turn on _debug_ logs. There is no concept of log levels. Instead, break up your namespaces into different components and enable the ones you care about: `my_app:http_server`, `my_app:redis_connection`, etc.
