### ISSUE TITLE
PR for overriding formatArgs

### ISSUE THREAD

**Issue by basaran** [visionmedia/debug#782]
Hello,

May I send a PR to allow overriding the formatArgs method? Similar to debug.log? I found no way to disable the date from TTY, and this could be useful for other things as well.

```javascript
// apply env-specific formatting (colors, etc.)
var formatFn = debug.formatArgs || exports.formatArgs;
formatFn.call( self, args );
// exports.formatArgs.call( self, args );
```

so that later, once can do with their own module:

```javascript
    debug.formatArgs = function ( args ) {
        var name = this.namespace;
        args[0] = name + " " + args[0];
    };
```

**Comment by Qix-** [comment]
There's already plans for this in v5. See #556.
