### ISSUE TITLE
No release notes for 4.2.0

### ISSUE THREAD

**Issue by iansu** [visionmedia/debug#784]
I wanted to check what changed in 4.2.0 but there's nothing on the releases page.

**Comment by P4sca1** [comment]
For some reason `CHANGELOG.md` has been removed completely.

**Comment by Qix-** [comment]
Changelogs are not something I use as files; use the releases page.

I forgot to do so for 4.2.0 and 4.3.0 - I will update them shortly. Thank you for the reminder.

**Comment by Qix-** [comment]
Done.
