### ISSUE TITLE
Timestamp in browser mode

### ISSUE THREAD

**Issue by anton-johansson** [visionmedia/debug#787]
I'm testing out this library to track various events in my frontend code (React re-renders, registering of event listeners, unregistering of them, events for them, etc).

This is great, because I can easily say which events I want to track. I would like to print a timestamp at the start of each message in the browser console. However, the timestamp is of course shown **after** namespace, so it's making it a bit hard to read...

```
listener:event 15:30:41.968 - Setting value for property 'myProperty' to 'myValue' +901ms
render:TextField 15:30:41.971 - Rendering TextField for property 'myProperty' +881ms
listener:event 15:30:42.507 - Setting value for property 'myProperty' to 'myValueX' +539ms
render:TextField 15:30:42.509 - Rendering TextField for property 'myProperty' +537ms
```

Ideas?

**Comment by Qix-** [comment]
Yeah I agree it's strange but unfortunately it's not something I can change until v5. #556 will allow you to do this.
