### ISSUE TITLE
When bundling using rollup to umd getting broken import

### ISSUE THREAD

**Issue by esakal** [visionmedia/debug#791]
Hello,
It might be a configuration issue but I really cannot find the origin of it and already spent few days. Before I give up I wanted to double check it.

those are the plugins I'm using
```
 const plugins = [
      typescript({
        check: true,
        tsconfig: options.tsConfig,
        tsconfigOverride: {
          compilerOptions: {
            rootDir: options.entryRoot,
            allowJs: false,
            declaration: true,
            paths: compilerOptionPaths,
            target: config.format === 'esm' ? undefined : 'es5',
          },
        },
      }),
      resolve({
        preferBuiltins: true,
        extensions: fileExtensions,
      }),
      getBabelInputPlugin({
        cwd: join(context.workspaceRoot, sourceRoot),
        rootMode: 'upward',
        babelrc: true,
        extensions: fileExtensions,
        babelHelpers: 'bundled',
       exclude: /node_modules\/(?![debug])/
      }),
      commonjs()
     ];
```

and in my code I import debug `import Debug from 'debug';`

the build passes but I get a runtime error because it export the debug with module.exports which is not available in the browser. 

Looking for previous issues on that matter brings #468 but setting alias doesn't seem to work.

If this is not the right place to seek for help for this issue feel free to close the issue. 

Thanks!
Eran
![image](https://user-images.githubusercontent.com/4751797/96004806-7ea15780-0e44-11eb-9c1e-487ea3f01bf1.png)

**Comment by Qix-** [comment]
Because `debug` is not a UMD module, it's a CJS module. I'm not sure what you expect to be done here - until `debug` switches to ESM (which won't be any time before the v5 release at least) then you can't expect all modules to be compatible with whichever module scheme you expect.

**Comment by esakal** [comment]
Sounds right,  but for that reason i'm using commonjs rollup plugin to convert it to es. also babel is there to handle the es5 transform (to support for example arrow function). 

Also, I see other libraries dropping debug message to the console log which means that they managed to bundle it somehow into their code

**Comment by Qix-** [comment]
Adding a build step to `debug` doesn't fix your issue, though - you'd still get a commonjs module coming from the package manager. You might need to ask the rollup community why this isn't working as bundling `debug` works for most people and thus there isn't anything for us to do here.
