### ISSUE TITLE
DEBUG not enabled vscode debug in .env variables

### ISSUE THREAD

**Issue by icaptnbob** [visionmedia/debug#793]
I have this test code:

> const info = require('debug')('app:info');
> console.log('env NODE_ENV', process.env.NODE_ENV);
> console.log('env ANOTHER_VAR', process.env.ANOTHER_VAR);
> console.log('env DEBUG', process.env.DEBUG);
> info('Test info debug logging');
> console.log('debug status:', info.enabled);

If I run the program in vscode using the debug mode, it doesn't enable debug using the environment variables.
I have tried:
- setting the env variables in the launch parameters
            "env": { "NODE_ENV": "dev", "DEBUG": "app:*" },
- setting the variables in the .env file and setting the launch parameters to load the .env file
            "envFile": "${workspaceFolder}/.env",
.env file:

> NODE_ENV=dev
> DEBUG=app:info,-trace
> ANOTHER_VAR=WHatNow
> 

The output is:

> env NODE_ENV dev
> env ANOTHER_VAR undefined
> env DEBUG app:*
> // Missing line here, should contain "Test info debug logging"
> debug status: true
> 

When I run the program in a bash window using this command, it shows the info output
"Test info debug logging".
This is the full output:

> [nodemon] starting `node demo.js`
> env NODE_ENV dev
> env ANOTHER_VAR WhatNow
> env DEBUG app:debug,app:info
>   app:info Test info debug logging +0ms
> debug status: true
> 

I've tried setting info.enabled = true (as in ticket #774) - doesn't help. As you can see in the last line, it's already true. I've gone through a range of tickets, such as #696 and others, but can't find anything.
When I trace the app, in the file common.js, debug.enabled is false so the debug function simply returns.

> 
> 	function createDebug(namespace) {
> 		let prevTime;
> 
> 		function debug(...args) {
> 			// Disabled?
> 			if (!debug.enabled) {
> 				return;
> 			}
> .....
> 

Please assist.
Thanks
Brian

**Comment by Qix-** [comment]
This has to do with VSCode, not `debug` - as you've seen with bash, `debug` is working fine. The conditional you mention at the bottom is to see if that instance's namespace is enabled given the environment variable, but since VSCode doesn't provide one to your program (for whatever reason) then of course `debug.enabled` will be false.

There's something else about your VSCode configuration that is wrong; I don't use VSCode so I can't really help, unfortunately. You might want to open an issue over on the VSCode repository.

Good luck!

**Comment by yf-yang** [comment]
@Qix- I encountered the same issue, and I can't really understand your explanation.
> The conditional you mention at the bottom is to see if that instance's namespace is enabled given the environment variable, but **since VSCode doesn't provide one to your program (for whatever reason)** then of course debug.enabled will be false.
However, in the given example @icaptnbob provides, they called
```
console.log('env DEBUG', process.env.DEBUG);
```
and it outputs:
> env DEBUG app:*
Doesn't it mean environment variable `DEBUG` is correctly provided?

@icaptnbob Did you find a solution later?
