### ISSUE TITLE
About SelectColors, `support-colors` not take effect

### ISSUE THREAD

**Issue by shizheng163** [visionmedia/debug#795]
Hi, I already install the `supports-color` module, but i don't get i hope result.
And I notice the `node_modules/debug/src/browser.js` only set six color.
``` nodejs
exports.colors = [
  'lightseagreen',
  'forestgreen',
  'goldenrod',
  'dodgerblue',
  'darkorchid',
  'crimson'
];
```
if you can I want to you add a interace for manual select namspace color for user select

**Comment by Qix-** [comment]
Not sure exactly what you're asking, but `supports-color` in `debug` is only used for the Node side of things - not the browser.

**Comment by shizheng163** [comment]
yes, but I only use command to start node scripts, following is my code.

I use the command `node logtest.js --color=256`

log_wrapper.js
```
function createLogger(namespace) {
  const loggerWrapper = {};
  const logLevels = ['trace', 'debug', 'info', 'warn', 'error', 'fatal'];
  const minLevel = 0;
  for (let idx = 0; idx < logLevels.length; idx++) {
    const level = logLevels[idx];
    if (idx < minLevel) {
      loggerWrapper[level] = require('debug');
    } else {
      loggerWrapper[level] = require('debug')(`[${level}][${namespace}]`);
    }
  }
  return loggerWrapper;
}

module.exports=createLogger;
```
test.js

```
const logWrapper = require('./log_wrapper')('log');
logWrapper.trace('hello, node');
logWrapper.debug('hello, node');
logWrapper.info('hello, node');
logWrapper.warn('hello, node');
logWrapper.error('hello, node');
logWrapper.fatal('hello, node');
```

And I only hope you can support a interface, it can support user manual select color.

**Comment by Qix-** [comment]
> And I only hope you can support a interface, it can support user manual select color.

There is no plan to do that, since `debug` is not meant to be a logging library like you're using it. The colors are to discern between namespaces, nothing more.
