### ISSUE TITLE
Any way to restore "instances"  ?

### ISSUE THREAD

**Issue by sbender9** [visionmedia/debug#796]
We were using the `instances` variable to provide users an easy way to enable/disable debug.

Is there a way you could provide us a way to get that list while still fixing the memory leak?

thanks!

**Comment by Qix-** [comment]
Unfortunately no, there is no way to do that as we do not track them centrally. That was the whole cause of the memory leak to begin with, and it was undocumented.

Best to make a wrapper.

**Comment by sbender9** [comment]
Got it. Thanks!
