### ISSUE TITLE
4.3.1 no longer appears to work in browsers

### ISSUE THREAD

**Issue by onexdata** [visionmedia/debug#803]
I rolled back to 4.1.1 and everything works fine, however, in 4.3.1 debug stops working in the browser. I did not see anything in npm documentation that describes what to change, not sure if a breaking change in minor version is normal?

### Steps to reproduce:

localStorage.debug = "*"

// V4.1.1
let debug = require('debug')('test')
debug('hello') // test hello

// V4.3.1
let debug = require('debug')('test')
debug('hello') // [nothing, no errors or warnings either]

**Comment by Qix-** [comment]
Set your filter to show Verbose output (disabled by default in Chrome, still not sure why).

There was a switch to using debug a while back.

![image](https://user-images.githubusercontent.com/885648/102701145-3b080700-4254-11eb-8c89-d70c39c4064a.png)

**Comment by shenshouer** [comment]
Still no output in console when enable Verbose
