### ISSUE TITLE
When used in a browser, I think the library is a bit too big!

### ISSUE THREAD

**Issue by asins** [visionmedia/debug#805]
When used in a browser, I think the library is a bit too big.

The code is mainly caused by the Colors list and the reference to the humanize package.

1. For the colors list, it would be better if I use a function to generate it. According to the rules of the colors list, I simplified it to the following function to generate 186 colors.
```js
/**
 * 用于显示时的文字颜色列表
 */
export const colors = (() => {
  const list = [];
  for(let a = 0; a <= 0xf; a += 3) {
    const a16 = a.toString(16);
    for(let b = 0; b <= 0xf; b += 3) {
      const b16 = b.toString(16);
      for(let c = 0; c <= 0xf; c += 3) {
        const c16 = c.toString(16);
        if(
          !(a === 0 && b <= 9 && c < 0xc)
          && !(a > 9 && b > 9 && c > 9)
          ) 
          list.push(`#${a16}${a16}${b16}${b16}${c16}${c16}`);
      }
    }
  }
  return list;
})();
```

2. The humanize package only uses its internal `fmtShort` method, which is only used to add a time unit to the diff variable. I think this simple method is enough. such as:
```js
var oneSecond = 1000;
var oneMinute = oneSecond * 60;
var oneHour = oneMinute * 60;

function humanize(ms) {
  ms = parseInt(ms, 10);
  if (ms >= oneHour) {
    return Math.round(ms / oneHour) + 'h';
  }
  if (ms >= oneMinute) {
    return Math.round(ms / oneMinute) + 'm';
  }
  if (ms >= oneSecond) {
    return Math.round(ms / oneSecond) + 's';
  }
  return ms + 'ms';
}
```

**Comment by Qix-** [comment]
This will be completely configurable in v5. As for now, there's not going to be any effort to minimize the package beyond what it already is. You're asking for mere bytes to be removed. That's overoptimizing.

**Comment by asins** [comment]
@Qix- Isn’t it meaningful to reduce the byte size of the code running in the browser?

**Comment by Qix-** [comment]
Not when it's just a few bytes, no.
