### ISSUE TITLE
Debug disables itself on master if you catch workers messages.

### ISSUE THREAD

**Issue by Bas950** [visionmedia/debug#806]
When I catch the workers messages I won't receive any debugs from master since debug disables all the loggers running on it.

<details>
<summary>With worker.on("message")</summary>
<img src="https://user-images.githubusercontent.com/34792838/103968064-87fc4080-5163-11eb-85d7-afb0eee9da97.png"/>
<img src="https://user-images.githubusercontent.com/34792838/103968073-8a5e9a80-5163-11eb-95be-1c82fded9d8f.png"/>
</details>
<details>
<summary>Without worker.on("message")</summary>
<img src="https://user-images.githubusercontent.com/34792838/103968360-fe00a780-5163-11eb-876c-c73a69bcdc98.png"/>
<img src="https://user-images.githubusercontent.com/34792838/103968408-183a8580-5164-11eb-9b6b-7f04680c2873.png"/>
</details>

Is there a way to fix this? I couldn't find anything on it...

**Comment by Bas950** [comment]
Just found out that I can fix it by doing:
`debug.enable(process.env.DEBUG);`
in my index.ts

But I feel like this should be done by default?

**Comment by Qix-** [comment]
Can you post a reproduction case with some code? Code images don't help me much.

**Comment by Bas950** [comment]
> Can you post a reproduction case with some code? Code images don't help me much.

Okay now I even have it with and without the worker.on("message")

I made an example for you that you can download and test: https://github.com/Bas950/DebugBug
Just run `yarn` and then `yarn dev`, if you un-comment the debug.enable in the index.ts file, it will show you Main and Main:Loop debugs, without it, you will only see debugs from Main:Worker (which ofc run only on the worker).

**Comment by Bas950** [comment]
@Qix- Anything on this?

**Comment by Qix-** [comment]
No, not really. Your reproduction case is convoluted and kind of complex. There have been problems with dotenv before, can you manually try setting `export DEBUG='*'` in your terminal prior to running to see if that fixes the issue first?

**Comment by Bas950** [comment]
Sadly that doesn't fix it :/
But as said before `debug.enable(process.env.DEBUG);` does fix it...

**Comment by Qix-** [comment]
That's strange. I've never heard of or faced this issue before and that's certainly not a fix that should be necessary.

Can you try to reduce the reproduction case a bit?

**Comment by Bas950** [comment]
not really just whenever this is in the code it breaks 
![image](https://user-images.githubusercontent.com/34792838/111388630-ebe53d00-86af-11eb-8580-56116cc9e727.png)

**Comment by Qix-** [comment]
That doesn't really help me debug this issue, though. I can't see how adding an event handler would make any difference.

Unfortunately I don't think this is related to `debug` in particular and instead is an issue specific to your application. If you happen to reduce the reproduction case down to a minimal case, let me know.

Good luck!
