### ISSUE TITLE
How to use with create-react-app?

### ISSUE THREAD

**Issue by dave-dm** [visionmedia/debug#809]
I'm doing this

```
import Debug from 'debug'
window.Debug = Debug
window.mydebug = Debug('myapp')
Debug.enable('*')

function App () {
  localStorage.debug = '*'
  window.mydebug('hello')
  return 'hello'
}

export default App
```

Doesn't print anything.

Edit: Downgraded to 3.1.0 from 4.3.1 and it works now

**Comment by Qix-** [comment]
Please don't downgrade, that doesn't help me maintain this package.

Try putting `Debug.enable('*')` first, before you create your debug instance. Does that work?

**Comment by dave-dm** [comment]
> Try putting `Debug.enable('*')` first, before you create your debug instance. Does that work?

doesn't seem to work, and don't have time to test more, already wasted like 3 hours trying 100 different combination of settings

**Comment by Qix-** [comment]
@dave-dm Sorry I couldn't help you, then. There are a lot of existing tickets about using Debug with CRA that you can search. If you don't have the time to debug with me, then I understand :) Good luck!

**Comment by avevlad** [comment]
maybe it will help you

![image](https://user-images.githubusercontent.com/2889662/143421629-b2130443-7531-4b32-bed7-e0be3cb8d344.png)
