### ISSUE TITLE
Cannot get debug working with TypeScript 4.0.5

### ISSUE THREAD

**Issue by danday74** [visionmedia/debug#810]
I've tried using debug with imports in TS 4.0.5 but cannot get it working, tried for 5 hours and I'm not a noob (professional web developer) and have had it working in many previous projects.

https://stackoverflow.com/questions/47724165/how-to-use-the-debug-module-with-typescript

I tried all the approaches (many times) in the above SO post.

My project uses Angular 11 and TS 4.0.5

I am trying to log to the browser console.

I've spent far too long trying to fix this so I am not going to spend even more time reproducing it. However, I wonder whether there is any known issue with TS4? thx

**Comment by Qix-** [comment]
> so I am not going to spend even more time reproducing it.

There's nothing I can do to help you then. There's no known issue with TS4 and there shouldn't be, either. You've given me very little information to go on.
