### ISSUE TITLE
Request: Add small note in README for using debug in child processes

### ISSUE THREAD

**Issue by aaarichter** [visionmedia/debug#811]
Hi,

Due to the `process.isTTY` check, it can happen that colors are not shown in child process when `stderr` is piped.

https://github.com/chalk/supports-color/issues/94#issuecomment-457881470 gave an easy solution to fix this problem. 
**Request**: It would be nice if the readme would mention this workaround.

example code from my project, where a worker with the actual server is forked and passed to node repl. Without setting `DEBUG_COLORS: 1`, there won't be any colors 😿 .
 
```js
worker = fork(WORKER_WRAP_PATH, [workerPath], {
  stdio: [
    /* stdin: */ 0,
    /* stdout: */ 'pipe',
    /* stderr: */ 'pipe',
    'ipc',
  ],
  env: Object.assign({}, process.env, {
    DEBUG_COLORS: 1 // without this settings, colors won't be shown
  }),
});

worker.stderr.pipe(process.stderr, { end: false });
```

**Comment by srivalli630** [comment]
2.6.9

**Comment by Qix-** [comment]
PR welcome
