### ISSUE TITLE
debug library not working in conjunction with amqplib (rabbitmq)

### ISSUE THREAD

**Issue by josh4mento** [visionmedia/debug#812]
We run our app in two "modes":
1. Our REST API (express js)
2. Our background processor (amqplib)

Our REST API that starts using nodemon runs completely fine with debug, however our background processor does not work with debug. 

We declare `DEBUG=app:*` in our .env file and yes, we do see it when we console log but for some reason when we do the following, nothing reports when running our background processor.

We do see that one of amqp's dependencies called [bitsyntax](https://github.com/squaremo/bitsyntax-js#readme) uses debug. I am wondering if it does anything to turn off debug but cannot find anything in their code that does that. 

Are there any troubleshooting steps that I can take to resolve this problem?

```javascript
import amqp from 'amqplib/callback_api'
import dotenv from 'dotenv'
import debug from 'debug'

const testLog = debug('app:worker')

const rabbitmq = `amqp://${process.env.RABBITMQ_USER}:${process.env.RABBITMQ_PASS}@${process.env.RABBITMQ_HOST}`
console.log(process.env.DEBUG) // app:*
const worker = () => {
  try {
    amqp.connect(rabbitmq, (err, conn) => {
      // ...
      testLog('this does not show up')
      console.log('this does show up')
      // ...
    })
  } catch (err) {
    // ...
  }
}

worker()
```

**Comment by josh4mento** [comment]
After doing some hunting, on workers the following code needs to be enabled:

``` javascript
debug.enable(process.env.DEBUG)
```

**Comment by Jeffrey819** [comment]
It is helpful

**Comment by danialdezfouli** [comment]
It happens **debug** because does not recognize **dotenv** while it's configured even before loading the debug package!

`debug/src/node.js: line 157`
```javascript
function load() {
  console.log(process.env.DEBUG);     // undefined
  return process.env.DEBUG;
}
```

**Comment by Qix-** [comment]
There isn't much I can do about this. `debug` reads the environment variable just like any other package does. Please open an issue with dotenv if you think that's the issue.

**Comment by efreibe** [comment]
I've done several tests about it, I found that when you use imports, all import calls are asynchronous, so when another library already imports debug, it will catch ENV variables BEFORE dotenv has a chance to redefine them.

Here is an example:

```javascript
import { config } from 'dotenv'

config()

import { another_function } from 'another_lib_that_uses_debug'
```
that code is not working because the imports are asynchronous and are executed before main module.

So I've done a little modification to my code:

```javascript
import('dotenv')
  .then(({config}) => config())
  .then(() => {
    const { another_function } = await import('another_lib_that_uses_debug')
    // ... rest of the code for index.js
  })
```

That works correct and let dotenv do its magic.
