### ISSUE TITLE
Can't hide logs from library i'm using - DEBUG environment variable issue

### ISSUE THREAD

**Issue by ivonigC** [visionmedia/debug#813]
I use a library that's using debug for the logging but unfortunately it's triggering console.log every 100ms. I tried everything with the DEBUG environment variable to stop it but couldn't find a solution. Here are the logs:

![image](https://user-images.githubusercontent.com/78804894/107937754-a6d0cc80-6f84-11eb-82de-a3be741cce64.png)

Here is what I tried:

DEBUG=*,-nschwarz:cluster*
DEBUG=*,-nschwarz:cluster*
DEBUG=-nschwarz:cluster:TASK*
DEBUG=nschwarz:cluster*,-nschwarz:cluster:TASK*

Here is where the logger is implemented in the library:
https://github.com/nathanschwarz/meteor-cluster/blob/main/src/logs.js

I don't use debug as a direct dependency, it's just a dependency of this package. 

Thanks in advance for your help.

**Comment by Qix-** [comment]
Can you show me the exact she'll command you ran to set the variables?

**Comment by ivonigC** [comment]
I tried on our development environment which is hosted on clever-cloud by setting the environment variable that are injected at startup but didn't work.

I also tried locally with commands like:

"start": "DEBUG=*,-nschwarz:cluster:TASK meteor run --settings settings.json"

But didn't work.

The App is based on meteor. According to the owner of the package i'm using it may explain some complication as environment variable are assigned at compilation not at runtime for packages.

I also started to install debug as part of the app and did debug.disable() but didn't work. Also did debug.disable() inside the Meteor.startup(() => {}) function but also didn't work.

**Comment by Palad73** [comment]
.

**Comment by Qix-** [comment]
Try

```json
"start": "DEBUG='*,-nschwarz:cluster:TASK' meteor run --settings settings.json"
```

and let me know if that works.

**Comment by wuyushan513** [comment]
ok
