### ISSUE TITLE
process.env.DEBUG not working?

### ISSUE THREAD

**Issue by iDVB** [visionmedia/debug#815]
First, I'm not reopening your [recent debate](https://github.com/visionmedia/debug/issues/814) on inline changes to `process.env`. 
I **support** the ability to do so, it just that it doesn't seem to be working for us anymore.

There are specific cases where the ONLY way to set things is via inline code setting those vars.
For us, this is Lambda@Edge which do NOT support env vars as regular functions do.

So for us, this is the only way.
The top of our functions look something like this...
**index.js**
```
process.env.DEBUG = 'logger:*';

const AWS = require('aws-sdk');
const Promise = require('bluebird');
const crypto = require('crypto');
const _ = require('lodash');
const logger = require('../_common/utils/logger');
...
```

**/_common/utils/logger**
```
const debug = require('debug');
const log = debug('logger:logs');
log.log = console.log.bind(console);

module.exports = log;
```

**Note:** We **are** using webpack to bundle our lambda functions (Edge Functions need to be tiny). Not sure if that has anything to do with why it would not work.

This was working previously, and now seems to have stopped working.
What are we doing wrong?

**Comment by kcng0** [comment]
a

**Comment by kcng0** [comment]
GitHub Enterprise Server only: This is all possible on GitHub Enterprise through GitHub Connect. It may take up to an hour to refresh the alerts and make them visible. After waiting a reasonable amount of time, if you are still not seeing the yellow bar in the Dependency Graph, you may want to contact your administrator. In the mean time, to move along with the course, we'll give you a hint - the recommended upgraded version is 2.6.9.

**Comment by Qix-** [comment]
There hasn't been an update to debug in a long time, so when did it stop working? There shouldn't be anything changing on debug's end.

The problem with assigning to `process.env.XXX` is order of operations. If you don't modify `process.env` before you require `debug` the _first_ time, then it won't pick up the environment variables at all.

This usually causes problems with e.g. webpack as the order of includes becomes a little muddy when packaged up. If you want, find the `debug` code in the bundle and temporarily edit it to `console.warn(process.env)` right before it reads the `DEBUG` variable and see what it says.

**Comment by iDVB** [comment]
Thanks @Qix- 
Still haven't been able to get this to work for LAmbda@Edge since we can't use Env Vars with edge functions.... and it seems no matter where I place `process.env.DEBUG = "*"` I can't get it to work.

This goes for local to my function code.... as well as our node module that we install and use that also uses debug.... can't get either of those to log.

Would love some suggestions on how we can get this working. Maybe is there a way to inject that into the bundle?

**Comment by Qix-** [comment]
It needs to come before the first import of `debug`.

**Comment by iDVB** [comment]
Thanks @Qix-, 
What about when my npm module I authored is using debug, and I want a "consuming" project of that module to get my module to output debugging console.log? 

I tried adding it to before the import of my module (which in turn uses debug) but that does not seem to work.

**Comment by Qix-** [comment]
> and I want a "consuming" project of that module to get my module to output debugging console.log

So you want to override the enabled namespaces? Please don't do that. Debug is meant to be configurable granularly, by the end user. Subverting that design means you force the user to see.potentiallt verbose output and incur a performance hit

**Comment by iDVB** [comment]
I don’t think that’s what I’m asking about?
If I set the namespace in my module (bundled) to “module:mine” and then in
the consuming code before importing my module I set DEBUG=“module:mine”,
should that not work to allow my module to emit debugging logs?

Cause it currently does not seem to work for me, nor does setting it to
DEBUG=“*”

**Comment by iDVB** [comment]
Nm, turns out there is another issue at play unrelated to Debug which may
be causing this. I’ll give an update once we sort it out.

Thanks!
