### ISSUE TITLE
[browser]Why not use `process.env.DEBUG` directly?

### ISSUE THREAD

**Issue by hsxfjames** [visionmedia/debug#817]
The code in [src/browser.js#L226](https://github.com/visionmedia/debug/blob/master/src/browser.js#L226):
```javascript
typeof process !== 'undefined' && 'env' in process
```
will prevent webpack to recognize and substitute it into real value of `process.env.DEBUG`. For example, I set my environment variables using `webpack.EnvironmentPlugin`:
```javascript
new webpack.EnvironmentPlugin({
    NODE_ENV: nodeEnv,
    DEBUG: '*',
    // more...
}),
```
Then the `load` function will be compiled to something like this:
```javascript
t.load=function(){
    var e;try{e=t.storage.getItem("debug")}catch(n){}
    !e&&"undefined"!==typeof process&&"env"in process&&(e="*");
    return e
}
```
But if we change the `if` statement to `if (!r && process.env.DEBUG) { ... }`, we will get the correct code:
```javascript
t.load=function(){
    var e;try{e=t.storage.getItem("debug")}catch(n){}
    e||(e="*");
    return e
}
```

**Comment by Qix-** [comment]
Because not everyone uses webpack/relies on webpack's non-standard cleverness, and `process` is not available in the browser.
