### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by Cheng-Xiwei** [visionmedia/debug#824]
GitHub Enterprise Server only: This is all possible on GitHub Enterprise through GitHub Connect. It may take up to an hour to refresh the alerts and make them visible. After waiting a reasonable amount of time, if you are still not seeing the yellow bar in the Dependency Graph, you may want to contact your administrator. In the mean time, to move along with the course, we'll give you a hint - the recommended upgraded version is 2.6.9.

**Comment by Qix-** [comment]
wtf is going on with the spam here. It's been non-stop for days.

@sindresorhus do you have any idea? There's been a particular commit that just gets hammered with "neat!" "thanks!" etc. garbage, a few old, closed issues get hit as well, and then now this.

Wtf is going on lol

**Comment by sindresorhus** [comment]
@Qix- I many of these every day. No idea why or what the point is.

**Comment by Qix-** [comment]
Okay so it's not just me haha. Thanks anyway 😅 I'll let you know if github says something.
