### ISSUE TITLE
Coveralls file published with repo_token

### ISSUE THREAD

**Issue by eddiemonge** [visionmedia/debug#825]
The published npm package contains a `.coveralls.yml` which has a `repo_token` field. I don't know if this is security issue as I don't know what the token is for (and do not want to try testing it everywhere). It should probably be a npmignore line to keep it out of the package

**Comment by Qix-** [comment]
Coveralls isn't in the repository anymore. Hasn't been for quite a while - that's safe to ignore.

Thanks for the ticket though :)
