### ISSUE TITLE
Mark v4.3.2 with latest tag instead of beta

### ISSUE THREAD

**Issue by DJviolin** [visionmedia/debug#830]
Version 4.3.2 still marked with beta tag. If it's unintentional, please switch to the latest tag. This way it won't show up in outdated package list under NPM / Yarn. Thank You!

**Comment by Qix-** [comment]
It is not unintentional, though it hasn't received any complaints. I'll move it to latest shortly.

**Comment by RennyLi** [comment]
This is great!

**Comment by Qix-** [comment]
Went ahead and updated `latest` tag, give it some time to flush out of the cache and let me know if there are any problems.

Thanks for the heads up!
