### ISSUE TITLE
Enhancement: Have option to twist log multiple in local to single line in production 

### ISSUE THREAD

**Issue by tonynguyenit18** [visionmedia/debug#832]
This would be great if we can have away to login multiple in local and one line in production.
If we use `%O` we will have multiple line log out in screen (intended cuz it make easy to debug in development)
![image](https://user-images.githubusercontent.com/37351890/121270293-a3729f80-c8eb-11eb-82e6-6182ae6f339d.png)
But it's not good (too long for one single error) when having it Cloudwatch
![image](https://user-images.githubusercontent.com/37351890/121270381-cef58a00-c8eb-11eb-86cf-86d039f03949.png)

It would be better if we can config auto use `%O` (multiple line) in development and `%o`(single line) in production via an ENV Var

**Comment by Qix-** [comment]
Hi there, see #656 and the first two items on that list. They'll (eventually) do exactly what you're looking for.
