### ISSUE TITLE
How to use with typescript?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [visionmedia/debug#833]
Sorry if this is more of a general typescript question. Trying to use this module in typescript like so:

```
import debugModule from "debug"
const debug = new debugModule("my_module")

```
When I run tsc, I get:
_main.ts:4:15 - error TS2350: Only a void function can be called with the 'new' keyword._

**Comment by KapitanOczywisty** [comment]
You need to install also `@types/debug` and drop `new` keyword, `debugModule` is a function, not a constructor.

**Comment by GeoffreyPlitt** [comment]
That worked. thanks!

**Comment by akarshan1996** [comment]
Hey @KapitanOczywisty,

I have posted a question on StackOverflow. The link is below, please have a look at it whenever you get a chance. I have been stuck with the issue for the last 3 days.
`https://stackoverflow.com/questions/69303753/getting-error-typeerror-debug-is-not-a-function-while-running-the-test-cases`


Thanks.
