### ISSUE TITLE
microbundle bundles of the "debug" package with "--target node" results on ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by icaro-capobianco** [visionmedia/debug#834]
# microbundle bundles of the "debug" package with "--target node" results on ReferenceError: navigator is not defined

https://github.com/icaro-capobianco/debug-microbundle-repro

Workaround is to have debug included as external either through the --external flag or by avoiding unknown dependencies altogether.

https://github.com/developit/microbundle/issues/880

**Comment by Qix-** [comment]
There's nothing really to do here, `debug` is used by millions of projects without issues surrounding this at the moment. I've never seen this bundler before so I assume they're probably doing something wrong.

Please let me know if that's not the case.
