### ISSUE TITLE
How to bundle "debug" for an ambiguous environment?

### ISSUE THREAD

**Issue by kettanaito** [visionmedia/debug#836]
Hey. Thank you for the project.

I have more of a question than an issue per se: how to bundle this package for an ambiguous environment?

> I understand that this may be an issue on my side but I'd be much grateful if you helped to stir me into the right direction.

## Context

I'm using `debug` in a library that can run in both Node.js and the browser. When bunding `debug`, however, its source code gets executed and it thinks that it runs in Node.js, since the compile (TypeScript) is a Node.js process. This results in all browser-related code being stripped off right at this logical fork:

https://github.com/visionmedia/debug/blob/d177f2bc36d3b8b8e9b1b006727ef5e04f98eac7/src/index.js#L6-L10

Is there a way to bundle `debug` preserving this `if` statement?

Perhaps there are existing projects that utilize `debug` in ambiguous environments, it'd be helpful to see a reference of how they configure their bundlers. Thank you.

**Comment by kettanaito** [comment]
Here's [my project](https://github.com/mswjs/interceptors) where you can find `tsconfig.json`.

**Comment by Qix-** [comment]
Not sure how to help, the if statement should not be getting stripped out. That's a problem with your bundler doing some sort of build-time optimization.

Not sure how I can help unfortunately, perhaps open a ticket with whichever bundler you're using to ask how to disable that behavior.

For what it's worth, (whenever I get around to doing it) debug v5 will have a more elegant solution to this problem.

Good luck!

**Comment by kettanaito** [comment]
Thank you for a quick reply, @Qix-!

While putting down this issue I've noticed that the project doesn't actually use any bundler. It compiles the source code with `tsc`. Perhaps that's the issue. I'll try how `debug` behaves when bundled with something like Rollup and a CJS plugin. Hope that'll resolve the issue.
