### ISSUE TITLE
Colors not showing on nodejs log on Amazon Linux2 EC2s 

### ISSUE THREAD

**Issue by igal1c0de4n** [visionmedia/debug#843]
I use debug in a nodejs app I deploy on Amazon Linux EC2s. 

When I used Amazon Linux 1 I was able to ssh and see the debug levels and colors using tail/head/cat. 
On Amazon Linux 2, when I ssh in I don't see colors around the levels tags. Instead, I see the ansi color coding characters before/after the tags and EOL. 

So the log looks like a pile of gibrish:
```
[ec2-user@ip-172-31-54-15 log]$ tail -f web.stdout.log
Sep 12 11:56:28 ip-172-31-54-15 web: 12/09/21, 11:56:28.932   #033[37;1mstoryMethods:LOG #033[0mpostPublish invalidation already queued for storyId 9f844c13-d592-4167-bca4-2f217c67f780 #033[37m+2m#033[0m
```

Can anyone provide advice: 
How to get colors back into my EC2 logs? I miss them very much 🙏🏼

**Comment by Qix-** [comment]
Whatever is writing those log files is replacing the actual characters with some ASCII equivalent (`#033` isn't a real escape code, I've never seen that before). There's nothing I can really do to help you here since I'd need to be on the machine to debug.

Good luck!

**Comment by igal1c0de4n** [comment]
Thanks @Qix- 
What I can test? Would it help if I give you ssh access to the machine?

**Comment by Qix-** [comment]
Always helpful :) This repository gets a lot of traffic and I'm sure someone else will face the same thing at some point.

**Comment by igal1c0de4n** [comment]
I haven't found a solution just yet, but this thread seems to be related:
https://serverfault.com/questions/1017974/outputting-json-logs-on-elastic-beanstalk-with-amazon-linux-2
